### ISSUE TITLE
A Plague Tale: Innocence (752590) - artifacts

### ISSUE THREAD

**Issue by AwesamLinux** [daniel-schuermann/mesa#101]
**Describe the bug**
With ACO there is graphic artifacts

**Screenshots**
LEFT: ACO - RIGHT: LLVM
![plague](https://user-images.githubusercontent.com/43387963/62571771-8190d780-b892-11e9-817d-f6826d59042c.png)
(pay attention especially to the back of the hair)

I also compared this to the most recent Padoka Unstable PPA driver using LLVM 
![20190806210428_LLVM_1-19 2 0-devel](https://user-images.githubusercontent.com/43387963/62571851-ae44ef00-b892-11e9-8998-b44904efdf97.jpg)

**RenderDoc capture:**
https://drive.google.com/open?id=1pgZfngl5zrpnfOHdx__TraD6z413je7m

**System Information**
- GPU: RX VEGA 56
- GPU Driver Screenshot 1: 19.1.0+aco+git1565023722-70bb3c0becd-1bionic3 (Valves PPA)
- GPU Driver Screenshot 2 1:19.2-git190714221300.4e102a6-b-padoka0 (Padoka Unstable)
- Kernel version:  5.2.5-050205-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-1

**Additional context**
I also have an open issue of this game on the Proton github (of other problems):
https://github.com/ValveSoftware/Proton/issues/2739

**Comment by daniel-schuermann** [comment]
Hey, thx for the report. Unfortunately, the capture seems to have the issue baked-in, so that it looks (almost) exactly the same with llvm and aco. I figured a very small difference which is resolved with 3b777a1dd7eb1a41a9bc29f8f5844e17f23daffa. Could you check if the issue is gone with this patch?

**Comment by SR-dude** [comment]
I tried the capture, but it wasn't compatible with my RX 580.

**Comment by Johnnynator** [comment]
I can't spot any visual difference between aco and llvm now, so I suspect it is fixed.
(and before I get the Perf question again, I saw the roughly the same framerate with aco was with llvm)

**Comment by daniel-schuermann** [comment]
@Johnnynator I assume you are referring to an ingame-comparison and not the capture? Then, which GPU are you using?
@AwesamLinux Can you please confirm if the issue is fixed?

**Comment by Johnnynator** [comment]
@daniel-schuermann Yes ingame, GPU is a RX 580

**Comment by AwesamLinux** [comment]
@daniel-schuermann 
Good news, I just tried with 19.1.0+aco+git1565281340-ea03ec56ed1-1bionic1 from the experimental PPA. 

No longer seeing the artifacts, looks the same with ACO now:
![Screenshot from 2019-08-09 17-19-29](https://user-images.githubusercontent.com/43387963/62790469-812f5100-bacb-11e9-86a8-9dcd8ddf7a64.jpg)

So I'm closing this issue, thanks! :)
