### ISSUE TITLE
World of Final Fantasy black corrupted screen

### ISSUE THREAD

**Issue by dlove67** [daniel-schuermann/mesa#102]
**Describe the bug**
When launching World of Final Fantasy with ACO enabled (whether with vertex shaders or not) the screen is completely black except for 2D elements.

**Screenshots**
Correct LLVM rendering:
![Screenshot from 2019-08-08 20-47-35](https://user-images.githubusercontent.com/8529044/62748293-c4cb8180-ba1d-11e9-95e9-4d0040f5770a.png)

Incorrect ACO rendering:
![Screenshot from 2019-08-08 20-35-36](https://user-images.githubusercontent.com/8529044/62748305-d01ead00-ba1d-11e9-9d20-e77d80dddfb0.png)

**RenderDoc capture:**
[Can't upload the renderdoc capture, so here it is from my google drive](https://drive.google.com/open?id=1NmoGTcnR2x1eO82Ta7mlyWzC4PkjxbLG)

**System information:**
 - GPU: AMD Radeon Vega 64
 - ACO version: Current build from the ppa: 19.1.0+aco+git1565281340-ea03ec56ed1-1bionic1 

**Additional context**
I am launching via lutris as World of Final Fantasy needs the patch listed [here.](https://bugs.winehq.org/attachment.cgi?id=63338&action=diff)

**Comment by daniel-schuermann** [comment]
This is either an DXVK or game bug as it binds an MSAA texture where the shader expects a simple 2D image. LLVM gets away by luck, and I have not yet decided if and how we work around that issue.

**Comment by pendingchaos** [comment]
Should be worked around with aba8c9f0c7b734a4e661ca8745d1ee398d29bf26

**Comment by dlove67** [comment]
Thanks! I'll give it a try once the ppa updates :)

**Comment by dlove67** [comment]
Confirmed, works great now!

**Comment by SR-dude** [comment]
Since, it's your issue you can close it.
