### ISSUE TITLE
Artifacting on polygons, Killing Floor 2

### ISSUE THREAD

**Issue by SpookySkeletons** [daniel-schuermann/mesa#103]
Artifacting on polygon faces appears in many games, it can crash the system in a few titles like Overwatch but stuff like killing floor 2 gives me the most stable enviornment to see them in.

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/789738774102505453/546ACD1FB75967FD4ED691289158F32B5ED16262/

**RenderDoc capture:**
https://anonfile.com/o4lcDd29n5/KF2.tar_xz

**System information:**
 - GPU: WX7100 MXM GPU
 - ACO version: ~~3b777a1dd7eb1a41a9bc29f8f5844e17f23daffa~~ ea03ec56ed16ff66b8a512ae9c980f74eff17953

**Additional context**
--
EDIT: This seems to happen under llvm/llvmvs as well. Was this introduced with a mesa backend upgrade?

**Comment by SR-dude** [comment]
I'm unable to download the renderdoc capture. 
 Do you need an account with them?

**Comment by SpookySkeletons** [comment]
You shouldn't I'll upload elsewhere just a sec...
More info on the referenced issue: The lighting bug appears under only ACO but there's the separate polygon issue which is plaguing my system

**Comment by SpookySkeletons** [comment]
https://drive.google.com/open?id=1R0thXxBz4adRkajC1mxYl5vIsNu7XGXP

**Comment by SR-dude** [comment]
I tried your renderdoc. It looks fine on my rx 580.  It must be a APU related issue.

**Comment by daniel-schuermann** [comment]
> It must be a APU related issue.

Only that this card is not an APU ;)

**Comment by SpookySkeletons** [comment]
~~I am recompiling my system on my server inside of a chroot to speed it up.~~

~~Going to see if this solves my system problems.~~
It's a laptop dGPU/iGPU setup on an M6800 Dell.

My entire Gentoo system is just insane.
No other way to state it, login screen not accepting my password, black polys everywhere, random packages failing post symlinks. No idea what's the deal but I'll just have to start from stage3 again.

**Comment by daniel-schuermann** [comment]
Sorry to hear that! When I mess up with some driver installation, I tend to just re-install the system, but I don't know much about resolving these issues anyway...

**Comment by daniel-schuermann** [comment]
Any update?

**Comment by SpookySkeletons** [comment]
I'm going to have to call it quits on the gentoo deal. Just building mesa on ubuntu now. I'll grab a before and after of the issue in a few hours.

**Comment by SpookySkeletons** [comment]
Compressed. Will be uploaded soon, my upload speed is very poor, so again, sorry for the wait.

**Comment by SpookySkeletons** [comment]
https://drive.google.com/open?id=1QrzqA8D0WTxk2DvUFKN0a9XTKA46X6Pp

**Comment by daniel-schuermann** [comment]
This seems to be two unrelated issues. Can you elaborate which exact driver you used for both captures? The first one seems to render fine with LLVM before the rebase (backend_old_2019_08_13) while it has artifacts with both, LLVM & ACO on current master. Additionally, no matter which commit, with ACO there is lighting missing. The second capture seems to render fine, though.

**Comment by SpookySkeletons** [comment]
My gentoo install was damaged beyond repair and was presenting issues that couldn't be reproduced (the black tris).
I'm using the latest master on ubuntu to present the problem found here
https://github.com/ValveSoftware/Proton/issues/1328

**Comment by daniel-schuermann** [comment]
You mean the broken lighting? Can you test if this is resolved with 56db3b3eef98d4ccc15f8a4dee1b29c138068b74 ? The small triangles all over the place seem to be completely random happening with both backends.

**Comment by SpookySkeletons** [comment]
Just the broken lighting issue. Even my dxvk-9999 compiles on gentoo were inexplicably broken under Ubuntu itself.
Will test as soon as I can.

**Comment by daniel-schuermann** [comment]
It seems the artifacting was caused by an upstream regression. We reverted the patch and now both captures render fine for me.

**Comment by SpookySkeletons** [comment]
I'm getting lighting on the weapon now but there's no lighting on the environment weird enough.

The commit referenced did not resolve the problem either.

**Comment by daniel-schuermann** [comment]
Could you create a new capture with current master?

**Comment by SpookySkeletons** [comment]
https://drive.google.com/open?id=1XcvmPfNx8uldyJQVzGjmYZkrlhlTP4FW

Here you are, sorry for the wait!

**Comment by daniel-schuermann** [comment]
This renderdoc capture renders exactly the same with llvm and aco for me...

**Comment by SpookySkeletons** [comment]
Well, that's unexpected! It's some mesa backend issue? I was doing myself to death afraid it was my setup/ compiler/ hardware/ OS.

A bunch of issues present the very same broken rasterization related to shadow mapping in a lot of other open issues. Blocky triangles and triangle holes where there should be a block.

Should we open a separate issue for all the open corruption labels? Any leads so far?

**Comment by SpookySkeletons** [comment]
I can confirm on my Gentoo install that my local light source issue is no longer a problem but still the shadow mapping has that artifacting all over it.

Similar to: https://github.com/daniel-schuermann/mesa/issues/108

And it also affects Overwatch's shadows and the BattleNet launcher

**Comment by aufkrawall** [comment]
> and the BattleNet launcher

Could you elaborate on this? Battle.net launcher always had an issue with its window shadows or borders in Wine by having bold shadowy borders around some elements. This is not related to shader compilers though.

**Comment by SpookySkeletons** [comment]
Inside the window itself. There's large black triangle artifacts drawn diagonally across the background texture of the window I think I can trace with renderdoc, not sure if it'd do any good here. Or I can take a screenshot to show.

**Comment by daniel-schuermann** [comment]
Most helpful are captures which when you open them with RADV_PERFTEST=llvm render differently. You can easily test this before uploading by starting qrenderdoc once with and without the perftest flag.

**Comment by SpookySkeletons** [comment]
That's the weird part I get them on both llvm and aco, same as #108. My kf2 capture should demonstrate it the very same as the screenshot if you can somehow reproduce it. Large black jaggies all over the shadowmapping.

**Comment by SpookySkeletons** [comment]
Solved the issue!

The kernel can't be built with AMDGPU as a builtin piece it has to be a kernel module or else the rasterization breaks with those square and triangle jaggies on everything. I'll report this to kernel devs and see what they say, it may only happen with PRIME, I'm not sure...

But man, am I glad to be back! All other shadow effects are fixed in the latest master, everything works as it should!
