### ISSUE TITLE
The protagonist has incorrect hair color in Sunset Overdrive (847370)

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#106]
**Describe the bug**
The protagonist has incorrect hair color in Sunset Overdrive 

**Screenshots**
ACO
![20190810215001_1](https://user-images.githubusercontent.com/200750/62824895-021a4580-bbbd-11e9-89da-405091b42742.jpg)

LLVM
![20190810220234_1](https://user-images.githubusercontent.com/200750/62824894-0181af00-bbbd-11e9-9cfb-f214e02d6d67.jpg)

**RenderDoc capture:**
https://mega.nz/#F!tgoiFKYD!qhqX-yhcN8qC4ZTE5WR06Q

Last good commit: 3b777a1d

**System information:**
 - GPU: AMD Radeon VII
 - ACO version: I noted issue on 34dd1ddd commit, but last good commit is 3b777a1d

**Comment by daniel-schuermann** [comment]
Unfortunately, this game got hit by a corruption from upstream. The hair issue should be fixed with 73c5a984ab5e58e408d02536a760c1b7428e3af1, though.

**Comment by NTMan** [comment]
> Unfortunately, this game got hit by a corruption from upstream. The hair issue should be fixed with [73c5a98](https://github.com/daniel-schuermann/mesa/commit/73c5a984ab5e58e408d02536a760c1b7428e3af1), though.

I confirm that problem was gone on commit 73c5a98
