### ISSUE TITLE
Witch Hunt (661790) inaccurate shadows

### ISSUE THREAD

**Issue by AwesamLinux** [daniel-schuermann/mesa#108]
**Describe the bug**
Shadows from trees (on buildings or the ground) with ACO are inaccurate, more of a blur and not well defined. Game was tested with ultra setting.

I tried also just disabling vertex shaders with launch option "RADV_PERFTEST=llvmvs", but that made no difference.

**Screenshots**
![aco_llvm](https://user-images.githubusercontent.com/43387963/62834102-10fa0a00-bc48-11e9-8641-7dbee267e045.jpg)

To the left is ACO, note the trees shadow on the wall.

**RenderDoc capture:**
RenderDock 1.4 capture using LLVM looking at the wall on the screenshot pictured above. (if it makes any difference I can grab one with ACO too).

https://drive.google.com/open?id=1HQvDwLsDuNTn0A9zG8Z8dUn0Zn8-eg9x

**System information:**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1565347502-34dd1ddde6f-1bionic1 (Valves PPA)
- Kernel version: 5.2.8-050208-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-2

[steam-661790-aco.log](https://github.com/daniel-schuermann/mesa/files/3490039/steam-661790-aco.log)
[steam-661790-llvm.log](https://github.com/daniel-schuermann/mesa/files/3490040/steam-661790-llvm.log)
[system_info.txt](https://github.com/daniel-schuermann/mesa/files/3490041/system_info.txt)

**Comment by daniel-schuermann** [comment]
Thx for the report! Unfortunately, this capture causes a hang with both, ACO and LLVM, on our side. Would you be able to try again taking a capture (maybe with ACO this time)?

**Comment by AwesamLinux** [comment]
Captures of this game made with the experimental Mesa+ACO driver appear to be causing hangs for me too. I did some more tests (Fedora Workstation 30 and RenderDoc 1.1 this time)

Capture 1 (mesa-19.2.0-20190814.13.73c5a984.fc30.src.zip)
- Experimental ACO driver: mesa-19.2.0-20190814.13.73c5a984.fc30.src.rpm
I was only once able to load this capture in RenderDoc, but every other time it hang.

Capture 2 (mesa-19.1.3.zip)
- Distributions current default diver (LLVM): Mesa 19.1.3
No problem loading this capture, with this driver I could also load Capture 1 without a hang.

I don't know if these two captures are of any use at all, but I uploaded them here anyway:
https://drive.google.com/open?id=1Hw9U5kp0ijE0ZAW9qlUNb5m0ykdNO8AJ
https://drive.google.com/open?id=1xTGjzZBAipiB6ShhUKdFzvdrmsMsi3Pj

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1565867468-30574bba376-1disco1 (Valves PPA)
- Kernel version: 5.0.0-25-generic
- Distro version: Ubuntu 19.04 (64 bit)
- Proton version: 4.11-2

I did a capture with RenderDoc 1.2 with the setup above using ACO. I was able to load this capture in RenderDoc without crash/hang several times, uploaded this one also because I guess it could be the most usable one so far :)
 
https://drive.google.com/open?id=1bespcdrQLnLUd2rd9NKhMDnMvHsSAIOn

[steam-661790.log](https://github.com/daniel-schuermann/mesa/files/3507363/steam-661790.log)
[system_info.txt](https://github.com/daniel-schuermann/mesa/files/3507364/system_info.txt)

**Comment by AwesamLinux** [comment]
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1570636576-246f50f2c13-1bionic1 (Valves PPA)
- Kernel version:  5.4.0-050400rc2-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-7

**Retest Compatibility Report**

Since the latest driver PPA update, the shadows are rendered properly. I'm no longer seeing any problems so I'm closing this issue. Good job! :tada: 

Attaching screenshots and log just for future refenrence:
![20191010235015_1](https://user-images.githubusercontent.com/43387963/66609621-d82fd000-ebb9-11e9-96a4-94e5d5d1c3d4.jpg)
![20191010234402_1](https://user-images.githubusercontent.com/43387963/66609652-e120a180-ebb9-11e9-9cf8-cc09c2204745.jpg)
[steam-661790.log](https://github.com/daniel-schuermann/mesa/files/3714786/steam-661790.log)
[system_info.txt](https://github.com/daniel-schuermann/mesa/files/3714787/system_info.txt)

**Comment by daniel-schuermann** [comment]
Cool, I'm glad to hear that this problem got resolved somehow. Sorry that we didn't manage to find the bug earlier!
