### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by Haxk20** [daniel-schuermann/mesa#109]
For a week or so i can seem to compile mesa-aco as it fails on openCL stuff.
This does not happen on upstream mesa on latest commit.
Only mesa-aco has this issue.
This is the compile errors: [error](https://pastebin.com/ct1GDmuc)
OS is Arch Linux.

**Comment by Haxk20** [comment]
I tried backend branch. That branch is totally OK and compiles just fine.

**Comment by pendingchaos** [comment]
I guess cherry-picking 6b8269d0bbded7a42cd2de2b50d077cf12157d15 fixes it?

**Comment by Haxk20** [comment]
Indeed it does

**Comment by pendingchaos** [comment]
The master branch has just been rebased onto backend, so it should now include that commit.

**Comment by aufkrawall** [comment]
I have to set `-D gallium-opencl=disabled` to make compile of current master pass.
