### ISSUE TITLE
Incorrect vertex rendering in ARMA 3

### ISSUE THREAD

**Issue by sambazley** [daniel-schuermann/mesa#110]
**Describe the bug**
Models are randomly stretched and textures flash. This does not happen with `RADV_PERFTEST=llvmvs`.

**Screenshots**
ACO:
https://gfycat.com/inferiorfatcondor
https://i.imgur.com/JOqrYas.jpg

LLVM:
https://i.imgur.com/S7ncpYZ.jpg

**RenderDoc capture:**
https://drive.google.com/open?id=1UrYV0-zEs_g83QJcYM3KCxk3KEqib8rG

**System information:**
 - GPU: Vega 64
 - ACO version: aur/mesa-aco-git (73c5a984ab5e58e408d02536a760c1b7428e3af1)

**Additional context**
The game is running with Proton 4.11-2. It won't start unless arma3battleeye.exe is renamed to arma3launcher.exe.

**Comment by pendingchaos** [comment]
Seems to be a regression from e3bb1cc46bd6f91cec93f4de4bf35955620bd7cd

**Comment by pendingchaos** [comment]
Should be fixed with 54ece7666541f03d61dca878c16a5e5667cbb936

**Comment by sambazley** [comment]
That's fixed it. Thank you :)
