### ISSUE TITLE
GPU hangs when I launch Homefront: The Revolution (223100)

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#111]
**Describe the bug**
GPU hangs when I launch Homefront: The Revolution (223100).
I have noted it on commit 32cd9487 and it still occurs on commit 73c5a984.
With `RADV_PERFTEST=llvm` the problem didn't happens.

**umr dumps**
[dmesg](https://github.com/daniel-schuermann/mesa/files/3502918/dmesg.txt)
[./umr -O halt_waves -wa](https://github.com/daniel-schuermann/mesa/files/3502912/halt_waves.txt)
[./umr -R gfx[.]](https://github.com/daniel-schuermann/mesa/files/3502913/gfx.txt)
[./umr -O many,bits -r \*.\*.mmGRBM_STATUS\*](https://github.com/daniel-schuermann/mesa/files/3502914/mmGRBM_STATUS.txt)
[./umr -O many,bits -r \*.\*.mmCP_EOP_\*](https://github.com/daniel-schuermann/mesa/files/3502915/mmCP_EOP.txt)
[./umr -O many,bits -r \*.\*.mmCP_PFP_HEADER_DUMP](https://github.com/daniel-schuermann/mesa/files/3502916/mmCP_PFP_HEADER_DUMP.txt)
[./umr -O many,bits -r \*.\*.mmCP_ME_HEADER_DUMP](https://github.com/daniel-schuermann/mesa/files/3502917/mmCP_ME_HEADER_DUMP.txt)

**System information:**
 - GPU: AMD Radeon VII
 - ACO version: 32cd9487 and 73c5a984

**Comment by SR-dude** [comment]
I tried it and it does hang on my RX 580 with 73c5a984ab.

One other thing, the game didn't  hang until I started to gain control of my character. There are several cut scenes played and then a long non-interactive game play sequence. You can't move.
But it isn't a pre-rendered video.  I noticed minor graphical glitches similar to the closed issue with
_Quantum Break_.

`amdgpu 0000:22:00.0: GPU fault detected: 146 0x0000480c for process Homefront2_Rele pid 2858 thread Homefront2_Rele pid 2936
 amdgpu 0000:22:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000
 amdgpu 0000:22:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x0204800C
 amdgpu 0000:22:00.0: VM fault (0x0c, vmid 1, pasid 32771) at page 0, read from 'TC4' (0x54433400) (72)
`

**Comment by SR-dude** [comment]
I have some more interesting lines from dmesg.

[dmesg.zip](https://github.com/daniel-schuermann/mesa/files/3503843/dmesg.zip)

**Comment by ntropy83** [comment]
I have built mesa-aco master last Saturday the 10th of August. With that version Homefront runs pretty good. The only issues are that the framerate goes way down, if you have a lot of volumetric lightning. Then it can go down to 20 fps from 180.

**Comment by daniel-schuermann** [comment]
@NTMan Would you try to grab a renderdoc capture of the hanging scene with RADV_PERFTEST=llvm and check if it contains the hang by opening the capture without the llvm flag (just opening the capture should hang as well). I have a rough idea of what could have gone wrong. Did this happen with the rebase/update this week?

**Comment by NTMan** [comment]
> Would you try to grab a renderdoc capture of the hanging scene with RADV_PERFTEST=llvm

The hanging scene is a black screen with a mouse pointer that precedes the appearance of the main menu.
I'm not sure I have enough reaction to capture it.

**Comment by daniel-schuermann** [comment]
just grab the main menu ;)

**Comment by SR-dude** [comment]
This capture was created with Mesa 19.1.3 & llvm 8.0.1.  I have several captures. One is bound to cause a gpu hang with ACO. They do emit the VM_CONTEXT1_PROTECTION_FAULT* kernel messages given in my first post, continuously. If you want another just ask.

https://drive.google.com/open?id=1wX9PePvVLXmItN5XOXGKR6vA_-M_80BM

**Comment by NTMan** [comment]
> @NTMan Would you try to grab a renderdoc capture of the hanging scene with RADV_PERFTEST=llvm and check if it contains the hang by opening the capture without the llvm flag (just opening the capture should hang as well). I have a rough idea of what could have gone wrong.

https://mega.nz/#F!Y1R1hIjZ!5IQmUjwXljO1eTnXv4TK6w

> Did this happen with the rebase/update this week?

It’s hard to say, I have not run this game for a long time.

**Comment by SR-dude** [comment]
I finally managed to remote ssh  and run umr after a hang. This is with kernel 5.2.9, with parameter amdgpu.lockup_timeout=-1. But the output from umr didn't change. UMR reports no waves to disassemble.  For a second, it looked like my card was actually responsive. Homefronts red cursor for the main menu popped up on the screen.  I'm using a rx 580.

[homefront-umr.zip](https://github.com/daniel-schuermann/mesa/files/3512212/homefront-umr.zip)

**Comment by SR-dude** [comment]
I've got a new massive zip file. It appears that I captured some wave disassembly.
A mesa developer gave some more hints on gathering some information here,
[https://bugs.freedesktop.org/show_bug.cgi?id=105251](url) Look at comment 23.

My umr lines are found in andrey.sh. Also the output from  trace-cmd is found in
eventdump. Futhermore, the contents of the folder ddebug_dumps were generated by
the variable GALLIUM_DDEBUG. 

I read another bug report that suggest that _Saint Row 3_ might lock up.
[https://bugs.freedesktop.org/show_bug.cgi?id=110749](url)

[homefront-umr2.zip](https://github.com/daniel-schuermann/mesa/files/3512481/homefront-umr2.zip)

**Comment by daniel-schuermann** [comment]
Can you give me feedback if it does still hang and if you see visual corruption? (The renderdoc capture looks far too dark for me, but I'd like to have it confirmed)

**Comment by NTMan** [comment]
Yes, recorded trace still continue hangs on replaying on latest mesa-aco commits (just tested 6fb87e02)

**Comment by SR-dude** [comment]
There are very minor graphical corruptions. That wasn't a good trace I posted. I have others that
look better.

**Comment by daniel-schuermann** [comment]
Can you confirm if the game runs fine now with 81fac59f8c0b9d013e65419cd03f86fc986f1eb7 ?

**Comment by macktab** [comment]
Can confirm, what it is working with fresh version 19.2.0-20190819.21.81fac59f.fc32. And now it is high fps in game.

**Comment by SR-dude** [comment]
Here is a better one.
https://drive.google.com/open?id=1ZpB3_XZ9BRsu90hF30zt0shARgAzbVxZ

**Comment by daniel-schuermann** [comment]
@SR-dude This capture is 5 days old. Would you please test if the corruption is still present?

**Comment by NTMan** [comment]
> Can you confirm if the game runs fine now with [81fac59](https://github.com/daniel-schuermann/mesa/commit/81fac59f8c0b9d013e65419cd03f86fc986f1eb7) ?

With commit 81fac59f issue was gone, awesome work.

**Comment by SR-dude** [comment]
It is now fixed with the latest commit.   Nice!
