### ISSUE TITLE
Grand Theft Auto 5: Pause character image corruption, Complex Control Avatar texture corruption

### ISSUE THREAD

**Issue by jerbmega** [daniel-schuermann/mesa#113]
**Describe the bug**
These are two separate issues, but I am unsure whether or not they're connected. They certainly look similar enough to the point that they might be.

The first is that on the pause menu, the image of the current character in the top right is corrupted and looks completely garbled. Using llvmvs does not help.

The second is that with the Complex Control mod, Avatar skins as well as enemy skins do not properly render, and they also look garbled. This doesn't happen to normal pedestrians in either Complex Control or the main game, and this also does not happen with Michael, Franklin or Trevor in the main game. llvmvs also did not alleviate this issue.

**Screenshots**
Pause menu corruption (ACO):
![gta5_avatar_aco](https://user-images.githubusercontent.com/6520237/63069468-f09aab80-bee4-11e9-9204-538d7695e4bb.png)

Pause menu corruption (LLVM):
![271590_20190814223554_1](https://user-images.githubusercontent.com/6520237/63069477-f98b7d00-bee4-11e9-80a5-e0ee54c231a8.png)

Complex Control Avatar corruption (ACO, pay attention to the head and hands):
![gta5_complexcontrol_aco](https://user-images.githubusercontent.com/6520237/63069427-c812b180-bee4-11e9-96af-6f91f5f3a166.png)

Complex Control Avatar corruption (LLVM):
![271590_20190814223619_1](https://user-images.githubusercontent.com/6520237/63069457-e678ad00-bee4-11e9-97b9-cf77d00ec857.png)

**RenderDoc capture:**
These are hosted on my personal webserver, so I will be removing them if/when these are resolved.
Pause menu corruption: https://croc.pw/aco/renderdoc_avatar.rdc
Complex Control Avatar corruption: https://croc.pw/aco/renderdoc_complexcontrol.rdc

**System information:**
 - GPU: RX 580 8gb
 - ACO version: 73c5a98

**Additional context**
I'm not actually using "vanilla" ACO, instead I exported a patch for every commit that ACO master has which upstream master does not, then added them to /etc/portage/patches so it integrates seamlessly with Gentoo's package manager. As unnecessary as it sounds, I did this so that I can use ACO without creating a separate ebuild for it, and so that once 19.2.0-rc1 comes out I can add ACO to it on my Mesa Copr with ease. If this is possibly the cause of the issues then I will be happy to re-test with the normal ACO branch, although I understand ACO was rebased yesterday so I'm pretty confident that isn't the case.

**Comment by daniel-schuermann** [comment]
We weren't able to reproduce this bug. But it might be related to the hang which was reported on Vega. Would you test if it works now with 81fac59f8c0b9d013e65419cd03f86fc986f1eb7 ?
If not, I'd like to ask to just test vanilla ACO master ;)

**Comment by jerbmega** [comment]
Complex Control renders properly with that commit, and for the most part the pause menu does as well, but there's still very slight corruption on it. I'll re-test with vanilla ACO tonight after work.

-------- Original Message --------

**Comment by jerbmega** [comment]
Still happening on vanilla 9b18c4e.

![271590_20190820191925_1](https://user-images.githubusercontent.com/6520237/63391468-91bfb100-c380-11e9-9274-8c00db39a739.png)

https://croc.pw/aco/renderdoc_avatar_new.rdc

**Comment by daniel-schuermann** [comment]
I see the problem, but unfortunately the renderdoc captures aren't helping in this case as the texture is probably pre-rendered, and thus, the final image looks the same with LLVM and ACO...
So just to inform you, it might take a while to figure what's going wrong here.

**Comment by daniel-schuermann** [comment]
@jerbear64 do you still have issues with a current driver version with GTA V?

**Comment by jerbmega** [comment]
I am no longer having any issues on upstream master.

**Comment by daniel-schuermann** [comment]
thx!
