### ISSUE TITLE
Memory issue while using Cryptomator.AppImage with Mesa-ACO-git

### ISSUE THREAD

**Issue by suymur** [daniel-schuermann/mesa#114]
**Describe the situation**
While using the Cryptomator AppImage and using the "[mesa-aco-git 19.2.0](https://aur.archlinux.org/packages/mesa-aco-git/)" RAM usage spirales out of control until the systems locks up.
See the following issue coming to the conclusion Mesa was the issue at: [cryptomator/issues/953](https://github.com/cryptomator/cryptomator/issues/953)

Changing back to standard "Mesa 19.1.4-1" fixed the issue.

**RenderDoc capture:**
./.

**System information:**
- OS: Manjaro Linux x86_64
- Kernel: 5.2.8-1-MANJARO
- CPU: Intel i7-6700K (8) @ 4.200GHz
- RAM: 16GB
- GPU: 7970 OC
-- Codename: Tahiti XT2

 - ACO version: [mesa-aco-git 19.2.0_devel.114724.fbaabd839e8-1](https://aur.archlinux.org/packages/mesa-aco-git/)

**Additional context**
If you want / need any further information let me know.

**Comment by pendingchaos** [comment]
Does it happen with `RADV_PERFTEST=llvm`?

**Comment by suymur** [comment]
After I set it, everything worked normally. 

Sorry i haven't read that one should check for that before opening an issue.

**Comment by suymur** [comment]
No, i have to take that back,
after leaving it for a bit, the error is still present.

**Comment by miscco** [comment]
Its the other way around. If you define `RADV_PERFTEST=llvm` then ACO is not used at all but the LLVM backend.

If the problem persits when using that option then this is most likely not a ACO related problem

**Comment by suymur** [comment]
Ah okay, my bad then.

Reverting back to Mesa 19.1.4 fixes the issue, so I’ll go with that for now.
