### ISSUE TITLE
GPU hangs when I enter in "BRANDING & SPONSORS" menu item in DiRT 4 (421020)

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#115]
**Describe the bug**
- Launch the "DiRT 4"
- Enter in "MY TEAM" menu
- Enter in "BRANDING & SPONSORS" menu

GPU hangs was occurs here.

With `RADV_PERFTEST=llvm` the hang not occurs.

**Screenshots**
![IMG_20190816_211402](https://user-images.githubusercontent.com/200750/63189903-8158bf00-c07e-11e9-947d-8217cd90d1b7.jpg)

**RenderDoc capture:**
Unfortunately, the game being crashes when renderdoc capture enabled.
![Screenshot from 2019-08-16 21-59-36](https://user-images.githubusercontent.com/200750/63190017-b9600200-c07e-11e9-8e56-be573e54bf2c.png)

**System information:**
 - GPU: AMD Radeon VII
 - ACO version: a0a7fa75

**Additional context**
[dmesg](https://github.com/daniel-schuermann/mesa/files/3510738/dmesg.txt)
[./umr -O halt_waves -wa](https://github.com/daniel-schuermann/mesa/files/3510748/halt_waves.txt)
[./umr -R gfx[.]](https://github.com/daniel-schuermann/mesa/files/3510750/gfx.txt)
[./umr -O many,bits -r \*.\*.mmGRBM_STATUS\*](https://github.com/daniel-schuermann/mesa/files/3510758/mmGRBM_STATUS.txt)
[./umr -O many,bits -r \*.\*.mmCP_EOP_\*](https://github.com/daniel-schuermann/mesa/files/3510759/mmCP_EOP.txt)
[./umr -O many,bits -r \*.\*.mmCP_PFP_HEADER_DUMP](https://github.com/daniel-schuermann/mesa/files/3510761/mmCP_PFP_HEADER_DUMP.txt)
[./umr -O many,bits -r \*.\*.mmCP_ME_HEADER_DUMP](https://github.com/daniel-schuermann/mesa/files/3510762/mmCP_ME_HEADER_DUMP.txt)

**Comment by daniel-schuermann** [comment]
@NTMan As this might very well be the same bug as in Homefront, GTAV and NMS, would you test if this is still an issue with current master?

**Comment by NTMan** [comment]
Not reproduced on the current master.
