### ISSUE TITLE
GTA5: Grapics stack hang if going into the menu while being in game

### ISSUE THREAD

**Issue by Alexmitter** [daniel-schuermann/mesa#117]
**Describe the bug**
GTA 5 loads up and renders normal, but the moment I press ESC or the Menu button on a game controller, the game will crash the Graphics Stack. I stuck with a frozen frame on all monitors.
I can reproduce that on Xubuntu, Gnome Ubuntu with X and with Wayland. Same result in all cases.

**System information:**
 - GPU: Radeon VII
 - ACO version: 19.1.0+aco+git1565970353-650031018b4-1disco1

**Comment by SR-dude** [comment]
Any strange kernel messages with the amdgpu driver?

**Comment by Alexmitter** [comment]
Sorry, this should have come with the original report. I hope you excuse that.
https://gist.github.com/Alexmitter/7249513acc5154f2a72391d32402e8ef

Edit: Just to make sure this is clear. Rolling back to the Ubuntu Mesa solves the issue.

**Comment by pendingchaos** [comment]
Does using the latest master help? From my own testing, I think either f6829fef2421c062bdbef2ac0e3022fa3e30f48f or 29058402777e5d1fe3167f15c1cd451889f9b254 fixed the hang.

**Comment by Alexmitter** [comment]
@pendingchaos I compiled and installed the latest state in master branch, but no change.

**Comment by daniel-schuermann** [comment]
Would you test if 81fac59f8c0b9d013e65419cd03f86fc986f1eb7 fixes the issue for you?

**Comment by Alexmitter** [comment]
@daniel-schuermann I pulled the latest state in master but it did not fix the issue.
Is there any way that would make it easier to identify the issue?

**Comment by daniel-schuermann** [comment]
@Alexmitter Yes. Please test if the issue also happens with RADV_PERFTEST=llvm. If the issue is not present with LLVM, would you try to grab a renderdoc capture with LLVM from the menu which causes the hang? You can confirm that you correctly captured the hang by opening the capture with qrenderdoc with ACO.

**Comment by Alexmitter** [comment]
@daniel-schuermann I updated today to  19.1.0+aco+git1566305973-9b18c4e3df0-1disco1 and the issue seems gone. I will do some more testing and if it is stable, I will notify you that it is solved.

**Comment by Alexmitter** [comment]
I can confirm the issue is solved, I guess it can be closed. Thank you everyone for your help, I am sorry I have not been more helpful.

**Comment by daniel-schuermann** [comment]
Thx! Reporting issues is always helping :)
