### ISSUE TITLE
Flickering in GTA IV

### ISSUE THREAD

**Issue by libcg** [daniel-schuermann/mesa#118]
**Describe the bug**
I'm seeing flickering in some areas of the game. This includes lamps, skybox and some windows.

**Screenshots**
Visible on the top right:
![Screenshot from 2019-08-18 11-14-16](https://user-images.githubusercontent.com/490159/63228580-e5c46d00-c1a9-11e9-8208-c1828120d73e.png)

**RenderDoc capture:**
This is a 32-bit game, I can't get it to start with `ENABLE_VULKAN_RENDERDOC_CAPTURE=1`...

**System information:**
 - Proton 4.11-2 using built-in D9VK
 - GPU: R9 Fury
 - ACO version: 650031018b4

**Comment by daniel-schuermann** [comment]
Does the flickering go (completely) away if you use RADV_PERFTEST=llvm? Did you try starting steam with ENABLE_VULKAN_RENDERDOC_CAPTURE=1 or just the game?

**Comment by libcg** [comment]
I was able to reproduce the issue using `RADV_PERFTEST=llvm`. Carry on!

**Comment by daniel-schuermann** [comment]
Thx for reporting anyway. Might be a D9VK bug then.
