### ISSUE TITLE
X4 Foundations: abort because of temporaries never defined or defined after use

### ISSUE THREAD

**Issue by edmondo** [daniel-schuermann/mesa#120]
**Describe the bug**
X4 aborts with the shader dump and following message:
```
These temporaries are never defined or are defined after use:
%87
%88
```

This is a regression in master I couldn't bisect. It's easy to reproduce with the renderdoc frame capture.
Complete stdout and stderr of renderdoc:
https://gist.github.com/edmondo/9c1121ed1fdc6b78a0ce580fc0fb2d82

**RenderDoc capture:**
https://drive.google.com/file/d/1NVTu0LA_LKmAajzwaRssiXCLb0bFjAdZ/view?usp=sharing
(817 MB)

**System information:**
 - GPU: AMD RX 470
 - ACO version: 81fac59f8c0b9d013e65419cd03f86fc986f1eb7

**Comment by pendingchaos** [comment]
Unfortunately I probably can't open the RenderDoc capture because I don't have any compatible hardware plugged in right now. I have what appears to be the same problem with a different shader though.

Does 62b2e2c3467eab1358a34485fc6c1070b83af78c fix your crash?

**Comment by edmondo** [comment]
Yes, it does fix the crash. Thanks.

**Comment by edmondo** [comment]
@pendingchaos I just want to mention it here since I found a massive performance regression in standard mesa (not ACO) for X4, probably caused by a change in nir code generation (and maybe as a follow up this crash in ACO?).

I bisected the drop from 90 FPS to 1 FPS (one!) to this commit:
https://gitlab.freedesktop.org/mesa/mesa/commit/74470baebbdacc8fd31c9912eb8c00c0cd102903

I will file a bugzilla issue to mesa.

**Comment by pendingchaos** [comment]
I guess this fixes the performance issue: https://gist.github.com/pendingchaos/09f535ccb3ff5005a0bbac1fd9ed510e ?

I'll probably create a MR for that change soon.

**Comment by edmondo** [comment]
Nice! :+1: 
Yes, the performance issue is fixed with your patch.

**Comment by pendingchaos** [comment]
Does https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1844 also fix the performance issue? (if using `git am` is quicker: https://gist.githubusercontent.com/pendingchaos/06eb518ab0ff62b670adc00cbff7e021/raw/7ab8290bda61a2b9b2d1266ca3ee153cd508f071/opt_large_constants.patch )

**Comment by edmondo** [comment]
Yes, Connor's patch series fixes the performace regression in default mesa.

I didn't test it over ACO. Do you need to implement something similar for ACO as well or is it just NIR?

**Comment by pendingchaos** [comment]
Thanks for testing

We need to implement something similar for ACO

**Comment by edmondo** [comment]
Very nice, master from today with `load_constant` is running very well. Thanks!
