### ISSUE TITLE
Persona 5 (RPCS3) - Shader compile crash

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#121]
**Describe the bug**
Emulator crashes during shader compilation stage. 

    ./src/amd/compiler/aco_instruction_selection.cpp:314: aco::Temp aco::{anonymous}::emit_extract_vector(aco::isel_context*, aco::Temp, uint32_t, aco::RegClass): Assertion `idx == 0' failed. 

Commenting out the [assertion](https://github.com/daniel-schuermann/mesa/blob/81fac59f8c0b9d013e65419cd03f86fc986f1eb7/src/amd/compiler/aco_instruction_selection.cpp#L314) works around the bug without any obvious issues. 

**System information:**
 - GPU: Vega 56
 - ACO version: 81fac59f8c0b9d013e65419cd03f86fc986f1eb7

**Comment by daniel-schuermann** [comment]
I cannot reproduce this bug. Would you be able to either hand me a savegame, a renderdoc capture (taken with llvm and reproducing the error when opening with radv), or the pipeline (e.g. collected with vkpipeline-db using llvm)

**Comment by aqxa1** [comment]
I suspect the bug doesn't occur until late in the game, so that's why you can't reproduce it. Here is the [set of pipelines](https://drive.google.com/open?id=1FT_6C3a1YWJ8HdZqGP_uXB6RZKIiqy1w) produced with LLVM.

I ran the pipelines on ACO and it crashed on several pipelines:
     

2139.pipeline_test                                                                                        

2145.pipeline_test                                                                                    

2152.pipeline_test                                                                                        

2140.pipeline_test                                                                                    

2138.pipeline_test                                                                                        

2150.pipeline_test                                                                                    

Along with several more. Hopefully, it can be reproduced on your end.

**Comment by daniel-schuermann** [comment]
Does bfeeb9ff56f79dd2fd084b13e934e740d18f9247 fix this issue for you?

**Comment by aqxa1** [comment]
https://github.com/daniel-schuermann/mesa/commit/bfeeb9ff56f79dd2fd084b13e934e740d18f9247 fixes the issue, thanks.
