### ISSUE TITLE
Fails to compile (Again)

### ISSUE THREAD

**Issue by Haxk20** [daniel-schuermann/mesa#122]
Im starting to go crazy from reporting a failing build.
But well here we go again.
[pastebin dump](https://pastebin.com/hD8GYUA6)
Tried to build stock mesa and that one builds just fine.

**Comment by pendingchaos** [comment]
LLVM started requiring C++14. We'll probably rebase on upstream (which has a fix for this) soon. Until we do, you will have to add "-Dcpp_std=c++14" when running `meson configure` or `meson setup`

**Comment by daniel-schuermann** [comment]
@Haxk20 we rebased ACO so that it schould include the C++14 patch now. Did this solve your issue?

**Comment by Haxk20** [comment]
My btrfs part got corrupted from me doing experiments on it so wasnt here. But i just built mesa-aco so indeed yes it did.
