### ISSUE TITLE
OpenSUSE Support.

### ISSUE THREAD

**Issue by ukbeast89** [daniel-schuermann/mesa#124]
I am trying to to convert https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-aco repo to work in OpenSUSE, https://build.opensuse.org/package/show/home:ukbeast89:branches:X11:XOrg/Mesa

I need help doing this.
Thanks.

**Comment by ukbeast89** [comment]
OK, I've packaged it, and it works.
https://download.opensuse.org/repositories/home:/ukbeast89:/branches:/X11:/XOrg/openSUSE_Tumbleweed/

to undo, remove repo and do:
`sudo zypper dup`

**Comment by daniel-schuermann** [comment]
very cool :)
Sorry that I didn't reply earlier. Besides weekend, I also don't know how to create packages. I'd suppose asking some maintainer at OpenSUSE for help or whichever distro you want to build packages for. But looks like you already got it solved. :)
