### ISSUE TITLE
cemu zbotw zoom causes unstable system

### ISSUE THREAD

**Issue by BlazeKl** [daniel-schuermann/mesa#125]
**Describe the situation**
using cemu's vulkan backend with ACO and using the zoom feature of zelda breath of the wild causes the system to be unstable and have 1 frame every 4 seconds, it's possible to close the emulator and restore the system by spam-clicking the close button

**RenderDoc capture:**

[capture x2](https://drive.google.com/open?id=12_jy_p65guywq0ha0VbaYgcfiE1v_E11)

**System information:**
 - GPU: Radeon RX 470 4GB
 - ACO version: [db73bde](https://github.com/daniel-schuermann/mesa/commit/db73bde35cc01d5e3403b8474881232de5914b19)

**Additional context**
did 2 captures just in case. with LLVM it works correctly. using RADV_PERFTEST=llvmvs didn't help

**Comment by pendingchaos** [comment]
is it working now?

**Comment by BlazeKl** [comment]
I forgot to change some env variables when testing and thought it was fixed, srry

**Comment by BlazeKl** [comment]
it seems to be fixed on latest mesa-git and cemu vulkan branch, closing
