### ISSUE TITLE
No Man's Sky - Experimental 30/8

### ISSUE THREAD

**Issue by baldyjeric0** [daniel-schuermann/mesa#128]
Gameplay FPS seem ok, but entering any of the menus causes a major fps hit; dropping from 60fps to 12/15 fps.  Leaving the menu, gameplay jumps straight back into 60 fps and drops again when entering menus.  
This does not affect the initial 'Game Mode' menu.

**System information:**
 - GPU: Radeon RX570 4Gig
 - ACO version: Latest Ubuntu apt

Change the RADV env made no difference to this issue.

**Comment by pendingchaos** [comment]
I think this was reported in a different NMS issue: https://github.com/daniel-schuermann/mesa/issues/112#issuecomment-523114259

It was probably an upstream regression from 74470bae, which also caused issues with X4 foundations. The solution that will be taken would probably be to revert that commit in the upstream stable releases and implement a better fix for 19.3

**Comment by baldyjeric0** [comment]
I make you right on that; apologies I missed that issue.  Will close this one, many thanks.
