### ISSUE TITLE
Updating ACO ppa's to LLVM9.0 soon?

### ISSUE THREAD

**Issue by oscarbg** [daniel-schuermann/mesa#129]
Hi,
seems LLVM 9 should be released this week..
plans to update https://launchpad.net/~valve-experimental/+archive/ubuntu/mesa builds to LLVM9 shortly after 9.0 is released?
I want it for three reasons:
*New exts supported: atomic_int64
*on RADV at least fixes some bugs on Vega
*this is needed for Navi

**Comment by GloriousEggroll** [comment]
@oscarbg I think the proper way to handle this would be to contact the PPA's maintainer:

https://launchpad.net/%7Evivek-collabora

**Comment by baryluk** [comment]
It works with LLVM 9 and LLVM10 from top of svn/git. Ask the maintainer of the repo to build it if you want this way.

**Comment by oscarbg** [comment]
thanks.. also now ACO it's merged on mesa so PPAs like Oibaf include it also with LLVM 9.0..
