### ISSUE TITLE
amd tahiti xt

### ISSUE THREAD

**Issue by sylware** [daniel-schuermann/mesa#131]

**Comment by sylware** [comment]
I am the owner of amd tahiti xt parts. Since aco does not support gcn1 isa, I _may_ try to add its support to aco or an alternative compiler, since aco is setting up mesa code for alternative compilers. In order to help me, could give code pointers on mesa amd shader ABI? Namely the hardware context setup by mesa for shader execution? (push constant buffer, "vm" virtual memory layout, etc)

**Comment by pendingchaos** [comment]
There isn't really a single ABI, but one for radeonsi (the OpenGL driver) and RADV (the vulkan driver). ACO currently only works with radv.

The code relevant to RADV/ACO interaction and setup for shaders is mostly in radv_cmd_buffer.c/radv_descriptor_set.c, where push constants and descriptor sets are uploaded in functions like `radv_flush_constants()` and commands to run the shaders are created.

The part of the LLVM backend where code is created that uses all this setup is in radv_nir_to_llvm.c
ACO has the aco_instruction_selection.cpp and aco_instruction_selection_setup.cpp files which do this.

radv_shader.c is where ACO is actually used directly and information about the shader is read from the `radv_shader_binary_legacy` struct.

None of this is actually different in GCN1 from the currently supported GCN1.3 and GCN1.4. Most of the changes are slightly different instruction encodings, hardware bug/hazard workarounds and missing features.

**Comment by sylware** [comment]
Thanks for all.

I was looking for a document describing the hardware state a shader does expect
in order to run. hw registers, lds content, but mostly what data with its
layout in vram: those "push constants", "descriptor sets", etc.

I guess, I have to use the code pointers you nicely provided to figure out what
are those data strutures and their layout.

doc = code :(

That said, when aco is going upstream? IMHO, the code setup for alternative
compilers is kind of very important.

**Comment by daniel-schuermann** [comment]
@sylware Although meanwhile outdated, airlied did some small fiddling with GFX7 (Hawaii and friends) here: https://github.com/airlied/mesa/commits/aco-gfx7-wip
(SI and CI are very similar.)
You don't need setup code, hw register or the like. Just looking at which instructions are different or don't exist, and adding a second path for that should do the job for most things.
if you look at aco_opcodes.py, you see that some opcodes don't exist for GFX6/7. In aco_assembler.cpp, some encodings have to be changed.

**Comment by sylware** [comment]
Thanks for your response.

I don't know yet how I will handle GFX6 isa. That said, is your code going
upstream? Are you still going to work on it?  Because, having some code in mesa
setting up alternative shader compilers is really important in my opinion.

**Comment by pendingchaos** [comment]
We have a MR to upstream most of it (disabled by default) here: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2009 and we are still going to work on it after everything is upstreamed

**Comment by sylware** [comment]
What about a C port of aco? (removing c++ compiler/runtime dependency as much
as possible is always a good thing)

**Comment by pendingchaos** [comment]
We have no plans on rewriting ACO in C

**Comment by daniel-schuermann** [comment]
There is no runtime involved, just standard lib, and definitely no desire for a rewrite.
There is also no such thing as a common compiler interface in mesa. Some people are working on generalizing some stuff between radeonSI and radv in order to make things easier, but all of that is unrelated to a potential extension for Tahiti. Adding GFX6 ISA doesn't require a new compiler to be added but only a couple of things to be handled differently by ACO.

**Comment by sylware** [comment]
Then I don't know what I will do. I may do myself a port of your c++ code to C.
Cannot start right now, don't know how much real life will let me port it.

Out of curiosity, how did you manage to find the support ($$$/time) to work on
this?

**Comment by daniel-schuermann** [comment]
> Then I don't know what I will do. I may do myself a port of your c++ code to C. Cannot start right now, don't know how much real life will let me port it.

Why would anyone want to do that?! In my opinion, you won't get anything from that port. The two major C-Compilers (Clang and GCC), are both capable to compile C++ as well. The performance difference is probably neglectable and the code size and readability would be much worse.

> Out of curiosity, how did you manage to find the support ($$$/time) to work on this?

We are contracted by Valve for that work.

**Comment by sylware** [comment]
Don't take it personally, I am not here to criticize c++, it is all over the
internet, and has been for decades, and it is not the front focused topic.

I will stick to simple C and try to do something with 0 resource, not fair, but
who said the world was.

**Comment by daniel-schuermann** [comment]
> Don't take it personally, I am not here to criticize c++, it is all over the internet, and has been for decades, and it is not the front focused topic. 

No worries, I didn't choose C++ for it's beauty and don't take anything personal about programming languages. For beauty, I'd probably have chosen Rust. Compilers are by nature very dynamically (they are by definition complete functions in the mathematical sense) which would make functional programming languages the best choice in terms of simplicity.
> I will stick to simple C and try to do something with 0 resource, not fair, but who said the world was.

I think, you're drastically underestimating what it takes. I won't stop you, though, but I highly recommend to not bother. You can probably do something more useful to the world in that time :)

**Comment by sylware** [comment]
As I said, don't take it personally, but if I have a favor to do to the world,
unfortunately with 0 resource, it's trying to remove c++ and use simple C.

Sad you were "asked" by valve technical steering committee to use c++ for this.
The pb is with them I guess.

Nothing/nobody is perfect, the world is full of deceivers, me first.

**Comment by daniel-schuermann** [comment]
> Sad you were "asked" by valve technical steering committee to use c++ for this. The pb is with them I guess.

No idea where you got that from, but it's wrong. We are free to choose whatever tools we want to use.
