### ISSUE TITLE
Crystar: Some scenes show a black screen

### ISSUE THREAD

**Issue by CygnusTerminal** [daniel-schuermann/mesa#133]
**Describe the bug**
In-game, there is a feature that reproduces an in-game cutscene (https://youtu.be/9xCkjiIdj4k?t=4462), which is not working. The game would show a black screen, but the sound still reproduce, and once it ends, the game keeps functioning as intended.

**System information:**
 - GPU: Radeon RX 480
 - ACO version: mesa-aco-git 19.3.0_devel.115981.f2bed9b344c-2

**Additional context**

**Comment by pendingchaos** [comment]
Are you able to get a renderdoc capture?

**Comment by rossophantasma** [comment]
> Are you able to get a renderdoc capture?

Let me check, i'll keep you updated

**Comment by CygnusTerminal** [comment]
> Are you able to get a renderdoc capture?

Update: I could not, maybe i am doing something wrong. Could you point me out to a guide on proper renderdoc usage? The ones i've read didn't help me much. Thanks in advance!

**Comment by pendingchaos** [comment]
The issue template explains how to get one: https://github.com/daniel-schuermann/mesa/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by CygnusTerminal** [comment]
> The issue template explains how to get one: https://github.com/daniel-schuermann/mesa/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thanks a lot! Here you go, i had to upload it to google drive because of the size: [https://drive.google.com/file/d/1WoKMDEHXwauqJaEadbraynlVRBgEso2l/view] (Note: frame 2440 is a normal frame, the bug starts from frame 2840). Also, i upgraded to the latest Mesa ACO git (Mesa 19.3.0-devel (git-5e92f5b88d))

**Comment by daniel-schuermann** [comment]
@rossophantasma: Unfortunately, the renderdoc captures with the black screen don't contain anything useful (and render black with LLVM as well). Did you try starting the game with RADV_PERFTEST=llvm to see if this problem is specific to ACO?

**Comment by rossophantasma** [comment]
Hello again. I'll try tomorrow, because my motherboard died and i had to order a new motherboard, cpu and RAM. I'll update as soon as possible.

**Comment by CygnusTerminal** [comment]
> @rossophantasma: Unfortunately, the renderdoc captures with the black screen don't contain anything useful (and render black with LLVM as well). Did you try starting the game with RADV_PERFTEST=llvm to see if this problem is specific to ACO?

Hello again, i tried with RADV_PERFTEST=llvm and still shows a black screen. Sorry for the wrong report, i'll be sending it to the Proton github. Thanks a lot for your help anyways!
