### ISSUE TITLE
Very frequent full gpu crashes since mesa-aco 19.3.0

### ISSUE THREAD

**Issue by FurbyOnSteroids** [daniel-schuermann/mesa#134]
**Describe the bug**
As soon as the "loading into the level" ends (when starting a new game or continuing an old save), the screen freezes for a bit just to crash the whole gpu which requires a full system restart. This happens 100% of the time in the tested games below. If used with "RADV_PERFTEST=llvm", the games run just fine.

**System information:**
 - OS: Manjaro 18.1
 - Kernel: 5.2.14-1-MANJARO (no fsync patch)
 - GPU: Radeon RX580
 - ACO version: mesa-aco-git 19.3.0_devel.115981.f2bed9b344c-3

**Additional context**
Tested with No Man's Sky and Rage 2 (Both Vulkan games. Coincidence?)

**Comment by pendingchaos** [comment]
(It's late at night and the weekend in the morning, so I'm not sure how soon I will properly look at this.)

Both being Vulkan games isn't a coincidence, ACO is currently only supported with Mesa's Vulkan driver for AMD cards: RADV.

EDIT: do you know what was the last version that worked?

**Comment by FurbyOnSteroids** [comment]
Oh yea don't worry. I can just play it with llvm so no big deal. I was mentioning Vulkan because games that run via dxvk have no issues. Though I don't know how and if that plays a role so I thought I mention it.

The last version that worked just fine was 19.2 most likely, though I'm not 100% sure as I haven't played a whole lot the last few weeks

**Comment by daniel-schuermann** [comment]
@FurbyonSteroid As we are always interested in bug reports and regressions, would you help us and retest if the problem persists? Thanks in advance!

**Comment by shmerl** [comment]
Sorry for asking here, but I couldn't really deduce it from other places. How far along is Navi support in ACO? I'd be interested in testing it, since I just switched to a Navi card.

**Comment by Venemo** [comment]
@shmerl Thanks for your interest, please take a look at #136

**Comment by FurbyOnSteroids** [comment]
Yea sure. I'll keep testing. No problem.

**Comment by FurbyOnSteroids** [comment]
Alright. Tested with the new mesa-aco version 

Kernel: 5.3.0-0
Mesa-ACO version: 19.3.0_devel.20190919.b738bf06917-3
Proton: 4.11-5

No Man's Sky still just crashes on level-load. No change there.

Rage 2 on the other hand launches now, but looks like this:
![ACO Image](https://imgur.com/rGtu5Ro.png)
ACO RenderDoc Capture: https://mega.nz/#!xOZnjaga!ZMXBrcztuG-KkOYUe4SbaX6MxxM4iXYeDWw3z0tEhMI

While if I run it with RADV_PERFTEST=llvm, it looks like this:
![LLVM Image](https://imgur.com/yGZ4cZ5.png)
LLVM RenderDoc Capture: https://mega.nz/#!tGIXFSAS!5G-mVY-LvIYO73TDQZUbnlzetJqNxzj0CXXLWYwx4zk

I'm not sure, maybe it's a system issue that would be fixed if I reinstalled the OS. Doesn't look like a whole lot of people have this issue.

**Comment by daniel-schuermann** [comment]
I can reproduce the Rage2 issue, thx!

**Comment by FurbyOnSteroids** [comment]
ACO Version: 19.3.0_devel.20190927.d0ed7ce952c
Proton: 4.11-6
Kernel: 5.3.1-1

The Rage 2 issue seems to be resolved, graphics look normal again and it doesn't crash anymore. Ty for that! 
No man's sky still crashes, though for some reason sometimes, very rarely, it doesn't seem to crash. Maybe some planets work while most don't? I'm not sure. 

So that's why I thought I could share the system log file. Maybe it helps to figure out what's happening. Again, llvm works just fine so I still think it's a mesa issue.
[system_log.txt](https://github.com/daniel-schuermann/mesa/files/3664894/system_log.txt)

**Comment by evolarium** [comment]
I was also getting GPU hangs with my RX 470 on Mesa ACO in No Man's Sky.  However, with the current master (6c3bad5), No Man's Sky is working fine for me again.  Might be worth trying again now to see if it is resolved for you.

**Comment by FurbyOnSteroids** [comment]
Alright... After testing it with the newest mesa build I can pretty much confirm (or I was just super lucky) that No Man's Sky does not crash anymore. I loaded into 6 different worlds and none crashed. Looks like it's fixed. Awesome!

**Comment by daniel-schuermann** [comment]
@FurbyonSteroid Glad to hear that everything seems fixed. Are there still games affected or can this issue be closed?

**Comment by FurbyOnSteroids** [comment]
Oh yea, right. Haven't found a game where it happens, so I'll close it for now. If it reappears on some game and it works fine via llvm, I'll just re-open it
