### ISSUE TITLE
Commits and Vacations

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#135]
I see a massive code drop on the master branch.  Given that I had to do a soft reset of my clone, suggests that it is a rebase of mesa's master tip. There hasn't been too much activity in well over a month. Vacation time?  Anything new? I'll test it out.

You can close this as scratch.

**Comment by daniel-schuermann** [comment]
Heh, you name it :P
There is also some upstream preparation in the background going on, so don't expect fancy features in the next couple of weeks ;)
