### ISSUE TITLE
No Man's Sky LOD texture issues

### ISSUE THREAD

**Issue by Mastergatto** [daniel-schuermann/mesa#137]
**Describe the bug**
As described in the title, this game with ACO has heavy (LOD ?) texture issues, the models look very washed as you can see below. Often the game will load those textures slowly but nonetheless it will complete the task, but in certain cases like those textures on screens that will be never loaded completely.

**Screenshots**
ACO:
![20190917233320_1](https://user-images.githubusercontent.com/1028191/65081475-00098a80-d9a4-11e9-9265-74445ab76cf4.jpg)
LLVM:
![20190917233013_1](https://user-images.githubusercontent.com/1028191/65081467-fc760380-d9a3-11e9-9165-8c6fc2520cb7.jpg)

**RenderDoc capture:**
https://mega.nz/#!3w5ByQIL!S7nNbMxsBM4ptshf06I-ZpStYcay08p8djC8WlSDNg8

**System information:**
 - GPU: Radeon RX Vega 56
 - ACO version: 374999ecfdf

**Comment by daniel-schuermann** [comment]
Please provide some more information:
- How do you reproduce the issue?
- Does the issue appear every time you load into the game or only on the first start (e.g. after a reboot?)
- Did you test with LLVM after you tested with ACO? If so, did you try to do this the other way around?

That said, I can hardly imagine how this issue can be related to ACO in any way.

**Comment by pendingchaos** [comment]
> That said, I can hardly imagine how this issue can be related to ACO in any way.

I'm guessing the shader is using the incorrect LOD or something

**Comment by Mastergatto** [comment]
- At least in my case, it can be reproduced reliably by simply starting the game and loading save file directly into my base where I have saved last time. It should noted that I have everything on Ultra in the graphics settings.
- Only on first time, but some texture that have failed to load completely will remain in that state even the next time. I suppose this issue could reappear with new textures that weren't loaded in first instance, e.g. it could appear when you enter in a new area.
- I have switched to LLVM and back multiple times, and everytime this issue happens only with ACO, never with LLVM.

**Comment by pendingchaos** [comment]
Seems the renderdoc capture gives the blurry textures on both LLVM and ACO
This happens with some issues, making the renderdoc much less useful

**Comment by Mastergatto** [comment]
Should I create another RenderDoc capture but this time with llvm?

**Comment by pendingchaos** [comment]
I don't expect one with LLVM to be any more useful

**Comment by daniel-schuermann** [comment]
Is this still an issue? I saw some mentioning of LOD fixes in the patch notes.

**Comment by Mastergatto** [comment]
Unfortunately yes...even after some versions of the game and ACO, it's still present. It seems that with ACO the loading of textures is slower, but that can also happen with LLVM (although this is rare) if there are too much things going on the screen and it tanks the frame rate.

**Comment by daniel-schuermann** [comment]
closed because it doesn't seem to be a (serious) ACO issue.
