### ISSUE TITLE
World of Warships game freezes 

### ISSUE THREAD

**Issue by anonymous133** [daniel-schuermann/mesa#138]
Please follow comment chain here:
https://github.com/ValveSoftware/Proton/issues/333#issuecomment-533517807

I first thought it was a Proton related issue but deactivated ACO, which seems to have solved the issue.

If you need further info, please let me know.

I'm using mesa-aco-git 19.3.0_devel.115981.f2bed9b344c-2

**Comment by anonymous133** [comment]
I reinstalled the game and it seems to have been an issue with the world of warships preferences file. When I copied my old settings file over into the new installation it would freeze up the game. So guys if you run into this issue, delete your config file and set it up new.

**Comment by pendingchaos** [comment]
Do you still have the config file? It might have been a bug with ACO that only appears with a specific graphics setting.

**Comment by anonymous133** [comment]
Here it is. Thank you for your support and yes I think I don't have the exact same graphics settings with my new config, so you might be onto something.

[preferences.xml.zip](https://github.com/daniel-schuermann/mesa/files/3641932/preferences.xml.zip)

**Comment by anonymous133** [comment]
Hi @pendingchaos 
Freeze occurs again reliably upon starting the game and loading into port. Here is my preference file and the steam log:

[preferences.xml.tar.gz](https://github.com/daniel-schuermann/mesa/files/3646943/preferences.xml.tar.gz)
[steam-552990.log](https://github.com/daniel-schuermann/mesa/files/3646939/steam-552990.log)

**Comment by Venemo** [comment]
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.
