### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#141]
ACO will no longer compile. The error is below.
>[2/992] Compiling C++ object 'src/amd/compiler/3c53451@@aco@sta/meson-generated_.._aco_opcodes.cpp.o'.
FAILED: src/amd/compiler/3c53451@@aco@sta/meson-generated_.._aco_opcodes.cpp.o 
g++
 ...
 -c src/amd/compiler/aco_opcodes.cpp
In file included from ../src/amd/compiler/aco_ir.h:37,
                 from src/amd/compiler/aco_opcodes.cpp:25:
../src/amd/compiler/aco_util.h:74:29: error: ‘constexpr const value_type* aco::span<T>::begin() const’ cannot be overloaded with ‘constexpr aco::span<T>::value_type* aco::span<T>::begin() const’
   74 |    constexpr const_iterator begin() const noexcept {
      |                             ^~~~~
../src/amd/compiler/aco_util.h:67:23: note: previous declaration ‘constexpr aco::span<T>::value_type* aco::span<T>::begin() const’
   67 |    constexpr iterator begin() noexcept {
      |

**Comment by pendingchaos** [comment]
ACO has recently started requiring C++14, since it's now the default for Mesa and required by LLVM 10.

Try recreating your build directory or running `meson configure <build directory> -Dcpp_std=c++14`

**Comment by SR-dude** [comment]
That worked. I personally don't have any plans to upgrade llvm. I'm still using llvm 8.0.1.
