### ISSUE TITLE
Agony Unrated Graphical Glitch

### ISSUE THREAD

**Issue by troylights** [daniel-schuermann/mesa#143]
**Describe the bug**
Pixelated areas and distortions in main menu and game which appear to affect background areas.  Changing shadow settings in the graphics MAY eliminate the effect in the main menu, but otherwise no setting changes from low to ultra make any difference in the game.

Game ran fine with previous MESA-ACO (PPA for Ubuntu 18.04) until I did a system update yesterday.  Unfortunately, there were several updates which happened at the same time, making the cause harder to determine.  The game itself received an update, but there was no indication by the developers that any changes had been made to the rendering engine.  Proton was updated from 4.11-5 to 4.11-6.  If I remember correctly, the last time I played the game successfully, I was using 4.11-4.  However, I forced version 4.2-9, and there was no improvement.  Using RADV_PERFTEST=llvmvs or RADV_PERFTEST=llvm did not fix the bug.  I am unable to revert to the previous MESA-ACO, and I suspect this to be a MESA bug.  However, since I'm using the PPA by Valve, this seemed like the place to post the bug report.

**Screenshots**
PROTON_USE_WINED3D renders the main menu similarly to DXVK (prior to recent MESA-ACO update) in this screenshot:  https://steamuserimages-a.akamaihd.net/ugc/770602596707321791/79F2FDC43B033FB231DE59FDE5DEB6F8B9B1AB38/

Example of current graphical glitch:  https://steamuserimages-a.akamaihd.net/ugc/770602596707315896/05C67A5A36124E40AA51F24AF7A39B36DEAA9013/

**RenderDoc capture:**
If you really need this, I'll post it later.

**System information:**
Ryzen 3 1300x
Sapphire Nitro+ RX 580 8 GB
16 GB DDR4 3200
Ubuntu 18.04.3 (GDM3/Gnome/Ubuntu)
Valve PPA kernel 5.0.0-20-mfutex
Valve PPA MESA-ACO 19.1.0+aco+git1568736924-374999ecfdf-1bionic4

**Additional context**
I've also created an archived backup using Steam, uninstalled the game, and reinstalled the game to another directory.  About the only thing I haven't done is to PPA purge Valve's MESA-ACO to test using Padoka stable.  I have played a couple of other UE4 games such as Hellblade and Supraland without rendering issues, so I am hesitant to possibly break things for just one game.  While this game seems playable with WINED3D, the framerate and render quality are not on par with playing it using DXVK, as I had been able to previously.

**Comment by troylights** [comment]
I was checking the Valve MESA-ACO PPA web page and noticed that it had received an update since I posted this bug report.  

... sudo apt update, apt list --upgradable, sudo apt upgrade, and reboot ...

Now running Valve PPA MESA-ACO 19.1.0+aco+git1568912505-b738bf06917-1bionic2.  The game renders correctly out-of-the-box, no need for PROTON_USE_WINED3D=1, just "gamemoderun %command%" in my launch options.

I'd close the thread and call it fixed, but I'll leave it open for comment until tomorrow, if anyone has anything to add.

**Comment by daniel-schuermann** [comment]
It was possibly a mesa-regression independent from ACO because
> Using RADV_PERFTEST=llvmvs or RADV_PERFTEST=llvm did not fix the bug.

Thanks for reporting anyway.

**Comment by troylights** [comment]
You're welcome, Daniel.  I'll call it a closed case then.
