### ISSUE TITLE
Assassin's Creed Origins lock-ups

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#145]
Assassin's Creed Origins stargazing missions lock up. In game, there are several missions where you are to rotate the stars to match up with some stones laid down on earth. When the constellations appear the system locks up. A video of one such mission is posted on [youtube](https://www.youtube.com/watch?v=5G-nX3COt1w), fast foward to timestamp 4:50. 

The behavior is reproducible with llvm. But, I'm posting this here first. This looks one of those times you'll need to forensically need to examine the machine with ssh.

**Comment by SR-dude** [comment]
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] driver: amdgpu 
           v: kernel 
           Display: server: X.Org 1.20.5 driver: amdgpu unloaded: fbdev,modesetting resolution: 1600x900~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.33.0 5.3.0+ LLVM 8.0.1) 
           v: 4.5 Mesa 19.3.0-devel (git-a8ac7881ff)

**Comment by SR-dude** [comment]
If I'm lucky it doesn't lock up the computer and I can just simply restart the X server again.
I see  the two lines in my logs. In dmesg one line is spammed: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
At the same time this line is repeated in my X server log: amdgpu: The CS has been cancelled because the context is lost.

**Comment by SR-dude** [comment]
[This](https://drive.google.com/open?id=1FfsFshIPtC3b5EzxE2oOpD7DHFn4Yphv) is a renderdoc captured just when the constellations appear.

**Comment by SR-dude** [comment]
I have some saves if anyone is interested. To use them place them in:
`C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\{youruserid}\4923`
inside your wine prefix. I'm not sure where they would go if you are using SteamPlay.
Also, the hints at the steam forums say to place them in a different folder other than 4923.
You might have to turn off cloud saves to actually load them.
[Origins-saves.zip](https://github.com/daniel-schuermann/mesa/files/3667622/Origins-saves.zip)

Once loaded, move north. You immediately notice over your right shoulder some standing stones. They'll look like stonehenge. Stand in the middle of the stones and press 'E'.

+ 
EDIT. I just learned that my saves my not be transferable between users, because my GUID is embedded in them. If so, try using [this tool](https://github.com/linzhouyu/ACST) .

**Comment by Kierek** [comment]
I encounter the same issue with Radeon VII

Device: AMD Radeon VII (VEGA20, DRM 3.33.0, 5.3.8-arch1-1, LLVM 9.0.0) (0x66af)

**Comment by pendingchaos** [comment]
Closing this issue since it happens with LLVM too and is duplicated at https://gitlab.freedesktop.org/mesa/mesa/issues/2127
