### ISSUE TITLE
Problem removing mesa-aco-git

### ISSUE THREAD

**Issue by anonymous133** [daniel-schuermann/mesa#149]
Hi, 

I would like to uninstall mesa-aco-git which I installed via pikaur. Could you please help me with this since I'm relatively new to linux. Thank you.

sudo pikaur -R mesa-aco-git
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: gst-plugins-base-libs: removing mesa-aco-git breaks dependency 'mesa'
:: gtk3: removing mesa-aco-git breaks dependency 'mesa'
:: lib32-mesa: removing mesa-aco-git breaks dependency 'mesa'
:: libglvnd: removing mesa-aco-git breaks dependency 'mesa'
:: libglvnd: removing mesa-aco-git breaks dependency 'opengl-driver'
:: qt5-base: removing mesa-aco-git breaks dependency 'mesa'
:: xf86-video-ati: removing mesa-aco-git breaks dependency 'mesa'

**Comment by SolitudeSF** [comment]
you should install `mesa` instead, then mesa-aco-git will be replaced.

**Comment by anonymous133** [comment]
Thank you so much @SolitudeSF !
