### ISSUE TITLE
Corruption in some mirror reflections in Heroes of the Storm

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#155]
Look at the distortion (of the geometry?) in the wheel reflection, it also rapidly changes in motion all the time:
![Screenshot_20191017_103421](https://user-images.githubusercontent.com/13510490/66992891-e9ea0980-f0ca-11e9-9571-4a3ebb351385.png)
Doesn't happen with LLVM.

RenderDoc capture:
https://drive.google.com/open?id=1v2TekIPPWM0xsLT_Nn4nxtq8MOb3Tml-

RX 570
recent mesa-git (main master, not your fork)

**Comment by daniel-schuermann** [comment]
Should be fixed with https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2366
Thx for reporting

**Comment by aufkrawall** [comment]
Yep, confirmed. Thanks, you guys are really quick.
