### ISSUE TITLE
Skies Of Arcadia Legends - incorrect rendering

### ISSUE THREAD

**Issue by Double-0-seven7** [daniel-schuermann/mesa#156]
**Describe the bug**
Playing the game Skies Of Arcadia Legends on ACO using the Dolphin emulator will produce semi-corrupted graphics.

**Screenshots**
ACO:
![GEAE8P_2019-10-17_13-07-33](https://user-images.githubusercontent.com/48792756/66999992-a64dca80-f0df-11e9-8046-c190749d5fde.png)
LLVM:
![GEAE8P_2019-10-17_13-08-35](https://user-images.githubusercontent.com/48792756/67000056-c7aeb680-f0df-11e9-9575-4fcf3da8caf0.png)

**RenderDoc capture:**
Capture from ACO:
[dolphin-emu_2019.10.17_12.28_frame993.zip](https://github.com/daniel-schuermann/mesa/files/3738653/dolphin-emu_2019.10.17_12.28_frame993.zip)

**System information:**
 - GPU: Radeon 530
 - ACO version: Mesa 19.3 git updated from Oibaf PPA with ACO enabled.

If's its needed i will test with the driver from this git (if its not updated on mesa 19.2 git).
The issue looks worse when in actual gameplay but the renderdoc file was too big to upload here.

**Comment by daniel-schuermann** [comment]
This might take a bit, as none of the devs have an Radeon 530.

**Comment by MojoJojoDojo** [comment]
Ya it's a laptop GPU.
I wonder how ACO even works on it but I only found issues on this game
so far , I thought to myself it will be useful to report here about it.

**Comment by MojoJojoDojo** [comment]
Ya it's a laptop GPU. 
I wonder how it even works with ACO but I thought it will be useful to report here anyway.

**Comment by daniel-schuermann** [comment]
We made a stupid mistake on the workaround for the Iceland/Tonga HW-bug which got fixed with a47e232ccd1df7a3f5dd1f92722772e8b81c90ed. Would you test if the issue is still present?

**Comment by ghost** [comment]
Nah it's still there but I think that the situation got improved(?)
![צילום מסך מ־2019-11-14 20-14-46](https://user-images.githubusercontent.com/33392696/68884714-68fb4d80-071c-11ea-804b-884df354caab.png)
Don't know if the Oibaf PPA got the commit tho.

**Comment by Double-0-seven7** [comment]
Yep this got fixed in the latest Oibaf driver so i am closing this.
