### ISSUE TITLE
SteamVR home is dimmer under ACO

### ISSUE THREAD

**Issue by yshui** [daniel-schuermann/mesa#157]
**Describe the bug**

The default environment of SteamVR Home is much dimmer compared to rendered with llvm. If I exit SteamVR Home, then the brightness looks normal except the controller models, which is also much dimmer than usual.

VR games seems to be unaffected (I tested Beat Saber).

**Screenshots**

(The blue noise-like glitch is present is both screenshot)

**aco**

![a](https://user-images.githubusercontent.com/366851/67159698-42760c80-f340-11e9-90b4-e511cb82f1d5.png)

**llvm**

![b](https://user-images.githubusercontent.com/366851/67159701-486bed80-f340-11e9-9b83-7bd5e6f4daa5.png)

**RenderDoc capture:**

I couldn't figure out how to do renderdoc capture of SteamVR. SteamVR Home doesn't want to start when `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` is set.

**System information:**
 - GPU: 5700XT
 - ACO version: 4424784357627f843c8c8aa066b3762b1709404e (tip of aco-navi)

**Comment by Venemo** [comment]
I've just tried, and couldn't reproduce this problem with the latest aco-navi branch.

**Comment by yshui** [comment]
I can confirm the dimming is gone with `RADV_PERFTEST=aco`, but it's still there when I use `RADV_PERFTEST=cswave32,pswave32,gewave32,aco`

(Sorry, I forgot to mention my RADV_PERFTEST settings in the original report)

**Comment by pendingchaos** [comment]
ACO doesn't yet support cswave32, pswave32 and gewave32. It's probably some situation not handled in the incomplete wave32 implementation. I'm guessing sgpr spilling is broken, I think everything else would probably just be sub-optimal

Does this patch https://gist.github.com/pendingchaos/c1e389a037e2a5161ab303e0ae5b4bd9 fix it (can be applied with `git am <file>`)?

**Comment by Venemo** [comment]
For wave32 to work, we need to also adapt ACO's exec mask handling, which currently always uses the 64-bit instructions. I plan to work on that after things look good with wave64.

**Comment by yshui** [comment]
@pendingchaos It does not seem to fix it.

**Comment by Venemo** [comment]
@yshui Please use ACO in wave64 mode (the default) for now.

**Comment by yshui** [comment]
@Venemo OK. Thanks for your help!

**Comment by pendingchaos** [comment]
We recently properly implemented wave32. Does it look correct now with `RADV_PERFTEST=cswave32,pswave32,gewave32,aco`?

**Comment by yshui** [comment]
everything seems to work :+1:
