### ISSUE TITLE
Shadows glitches in the Witcher 3

### ISSUE THREAD

**Issue by shmerl** [daniel-schuermann/mesa#158]
When testing recent updates in [aco-navi that finally started working better for The Witcher 3](https://github.com/daniel-schuermann/mesa/issues/136) due to various hazards mitigations, I noticed some graphical problems with shadows:

**llvm:**

![shadows_llvm](https://user-images.githubusercontent.com/310927/67154560-5b44da80-f2cc-11e9-8907-fce0e27cfa6a.jpg)

**aco:**

![shadows_aco](https://user-images.githubusercontent.com/310927/67154565-60098e80-f2cc-11e9-80cf-048793532e7b.jpg)

Save at that place: 
[tw3_save_shadows_bug.zip](https://github.com/daniel-schuermann/mesa/files/3747451/tw3_save_shadows_bug.zip)

Note shadows disappearing in the distance when using aco.

GPU: Sapphire Pulse RX 5700 XT
Mesa 19.3.0-devel ([git-4424784357](https://gitlab.freedesktop.org/Venemo/mesa/commit/4424784357627f843c8c8aa066b3762b1709404e)) (LLVM 10.0.0) (aco-navi branch).

Not sure if it's Navi specific, so if anyone can please confirm that it doesn't or does happen with older cards, it would be useful.

**Comment by aufkrawall** [comment]
Seems to look correct on Polaris:
![Screenshot_20191022_113228](https://user-images.githubusercontent.com/13510490/67273972-d28e9000-f4bf-11e9-8531-c2280b772835.png)

**Comment by Venemo** [comment]
I tested this on aco-navi just now and could not reproduce the problem with the attached save game.

**Comment by aufkrawall** [comment]
Noticed something weird: Somehow the lighting looks different with amdvlk-pro, like if amdvlk-open and radv-aco would have no indirect sun lighting:
![Screenshot_20191022_181926](https://user-images.githubusercontent.com/13510490/67307685-28cbf500-f4f9-11e9-89ee-28f3309f677d.png)
![Screenshot_20191022_182134](https://user-images.githubusercontent.com/13510490/67307687-28cbf500-f4f9-11e9-8490-833db6d8c1a3.png)

Since only amdvlk-pro is the "odd" one: Another case of hidden fixing in proprietary compilers?
Could of course also just be a bug of amdvlk-pro.

**Comment by Venemo** [comment]
@aufkrawall This issue is about shadows on aco-navi. Can you please open a different issue about this lighting problem?

**Comment by aufkrawall** [comment]
Sorry @Venemo for putting myself in between. My last comment about this: I checked with Windows native D3D11, and it looks like ACO/amdvlk-open. So it's apparently just a bug of amdvlk-pro.

**Comment by Venemo** [comment]
@aufkrawall Can you tell us which screenshot is "right" and "wrong"? Ie. which one did you make with which driver, and how does radv look?

**Comment by aufkrawall** [comment]
@Venemo I'll retest tomorrow in a proper, detailed ticket.

**Comment by shmerl** [comment]
> I tested this on aco-navi just now and could not reproduce the problem with the attached save game.

Try to move forward in the direction of the character where that save is pointing first using aco, and then form the same save using llvm. You'll see anomalies in the distance in case of aco. Or shadows looked OK to you?

Let me try rebuilding latest master, to double check.

**Comment by shmerl** [comment]
Just rebuilt latest mesa-aco-navi, and that glitch is gone! So I'll close it for now.

**Comment by aufkrawall** [comment]
@Venemo Seems like I tested too many things yesterday.

Windows Polaris D3D11:
![witcher3_2019_10_23_10_17_23_462](https://user-images.githubusercontent.com/13510490/67373158-6d9a6f00-f57f-11e9-9eeb-c93eb9b41c4f.png)

RADV-ACO:
![Screenshot_20191023_101051](https://user-images.githubusercontent.com/13510490/67373172-7428e680-f57f-11e9-99eb-e22775f1087f.png)

Looking identical and I guess that's all we want to know.

Well, except that the Windows driver for whatever reason fails in forcing 16x anisotropic filtering, whereas DXVK gets it done.
