### ISSUE TITLE
Trine 4 - corruption of certain effects

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#159]
LLVM:
![Screenshot_20191022_094143](https://user-images.githubusercontent.com/13510490/67266676-0d3cfc00-f4b1-11e9-8d15-39f1fb01397a.png)

ACO:
![Screenshot_20191022_094244](https://user-images.githubusercontent.com/13510490/67266674-0b733880-f4b1-11e9-92d3-eb02535c6b8a.png)

RenderDoc capture:
https://drive.google.com/open?id=1QbPxL2vU7XEOYgfUjj3vZHhMlOjf5Bkz

latest mesa-git mainline master
RX 570

**Comment by daniel-schuermann** [comment]
@aufkrawall Unfortunately, I cannot reproduce the issue with the renderdoc capture.

**Comment by aufkrawall** [comment]
@daniel-schuermann I see what you mean, the weird "lensflares" aren't showing here either in RD.
However, the partially missing shadows/SSAO in the trees in the background is visible (it's not random, but also part of the corruption).

Edit: The SSAO in the grass in the front is not right either.

**Comment by daniel-schuermann** [comment]
Can you give me a picture from the renderdoc opened with aco pointing out what exactly looks different? I'm not seeing it :/

**Comment by aufkrawall** [comment]
In the grass in the front, the SSAO (at least it's my best guess that it's the SSAO) has weird patterns which are not there on the LLVM screenshot:
![Screenshot_20191022_194139](https://user-images.githubusercontent.com/13510490/67314024-45b9f580-f504-11e9-85af-c6393aeb6dcb.png)
Those patterns also look like partially "detached" in motion when playing the actual game.

Also, you can notice that especially the trees on the right side of the background look too bright with ACO. Probably there is something wrong with the SSAO as well.

**Comment by daniel-schuermann** [comment]
But when opening the capture with LLVM, it looks exactly the same which makes it extremely hard to find.

**Comment by aufkrawall** [comment]
That's a bummer. :(
I suppose it wouldn't make sense to create more captures, the issue basically is always there and always looks the same.

**Comment by aufkrawall** [comment]
So the issue is that the corruption is "hardcoded" into the capture with ACO?
When I let radv-llvm render the game and capture it, there is no corruption in the capture (despite of using ACO in qrenderdoc).

**Comment by aufkrawall** [comment]
Good news: I can't reproduce this anymore with mesa 20.1.4 and RX 480.
Though amdvlk-pro is still 10% faster.
