### ISSUE TITLE
Shadow of the Tomb Raider flickering clouds

### ISSUE THREAD

**Issue by gort818** [daniel-schuermann/mesa#161]
**Describe the bug**
Graphical Corruption in clouds,  there seems to be flickering in clouds and smoke which doesn't happen with LLVM. Hard to see without recording

**Screenshots**
LLVM
![tr-llvm](https://user-images.githubusercontent.com/9098121/68520468-d571da80-024c-11ea-9c76-3f82ec2a9612.png)

ACO
![tr-aco1](https://user-images.githubusercontent.com/9098121/68520477-e3bff680-024c-11ea-8a96-254ab612baa0.png)

**RenderDoc capture:**
Will try to get soon.

**System information:**
 - GPU: [VEGA 56]
 - ACO version: [3b06b512c76]

**Comment by gort818** [comment]
Here is a better screenshot
![tr-aco-2](https://user-images.githubusercontent.com/9098121/68537472-336bf400-0319-11ea-9892-29b31a6da985.png)

**Comment by daniel-schuermann** [comment]
Thanks for the report!
Would you be able to capture the latter scene?

**Comment by doitsujin** [comment]
This is the exact same problem I was complaining about recently; at least on my Polaris it was fixed by the latest rebase and also works on mesa-master. @gort818 is your build up to date?

**Comment by gort818** [comment]
@doitsujin I built it on the 4th of November. I will try the latest master right now.

**Comment by gort818** [comment]
The latest rebase works great.
