### ISSUE TITLE
Doom 2016 System hang when using ACO

### ISSUE THREAD

**Issue by romanstingler** [daniel-schuermann/mesa#162]
Just tried ACO on Doom 2016 with newly compiled mesa 20.0 and I started the game at the first rune (vacuum) and the level plays fine until a fireball or multiple bright muzle flashes are in my view.
As soon as there is something very bright in front of me the game hangs and I can´t exit the game nor change the application window.
If I play the same with llvm it runs just fine.

If there is some debugging I can make just let me know. 
 
Processor Information:
    CPU:  Intel Xeon 8260
    Speed:  3900 Mhz
    96 logical processors
    48 physical processors
   
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.3.11-arch1-1
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12005000
    X Window Manager:  GNOME Shell using Wayland
    Steam Runtime Version:  steam-runtime_0.20191024.0

Video Card:
RX 5700 XT
    Driver:  X.Org AMD NAVI10 (DRM 3.33.0, 5.3.11-arch1-1, LLVM 9.0.0)
    Driver Version:  4.5 (Compatibility Profile) Mesa 20.0.0-devel (git-dd77bdb34b)
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x731f
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary VRAM: 8192 MB
Memory:
    RAM:  96020 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  937367 Mb
    Largest Free Hard Disk Block:  580833 Mb
    VR Headset: None detected

**Comment by romanstingler** [comment]
Closed 

I don´t know why but recompiling it 
(git-commit ad40715f35) fixed the problem

**Comment by romanstingler** [comment]
I recompiled the mesa with the latest commits 20.0.0_devel.117920.ad40715f359
and it doesn´t happen anymore.
Now I get this behavior just randomly when switching from ultra to low and again to ultra settings.

**Comment by Venemo** [comment]
@romanstingler Sorry for the late reply. Can you please try upgrading to kernel 5.4 and LLVM 9.0.1 and see if the issue happens with the very latest mesa master?

**Comment by Venemo** [comment]
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.
