### ISSUE TITLE
Graphical Issue Star Wars Jedi: Fallen Order

### ISSUE THREAD

**Issue by gort818** [daniel-schuermann/mesa#163]
Game runs great with aco! much less stutter than llvm, but there
seems to be a graphical issue with certain characters' hair in the game, this issue was not present with llvm

#with aco
![Screenshot_20191125_190507](https://user-images.githubusercontent.com/9098121/69596398-4b996f80-0fb7-11ea-962a-f521eedf77eb.png)

with llvm
![star-wars-jedi-fallen-order-cal](https://user-images.githubusercontent.com/9098121/69596593-f316a200-0fb7-11ea-97fc-4f47d90c7b66.jpg)

**RenderDoc capture:**
Could not get a capture, and it takes me forever to get the game to start.. sometimes it takes me twenty minutes but that is beside the point.
**System information:**
 - GPU: [vega 56]
 - ACO version: [6df53a980c0]

**Comment by gort818** [comment]
So I have to launch the game with origin and if I launch it with ENABLE_VULKAN_RENDERDOC_CAPTURE=1 origin crashes :(

If there is anything else I can do let me know.

**Comment by pendingchaos** [comment]
Seems someone created a duplicate issue on the Gitlab: https://gitlab.freedesktop.org/mesa/mesa/issues/2156 (the GitHub repo is still the preferred place to report ACO bugs for now)

The reporter somehow got some renderdoc captures and I think they are useful. I'll probably look into it more in the morning

**Comment by gort818** [comment]
Ok awesome thanks!

**Comment by pendingchaos** [comment]
I think this MR should fix the issue: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2917

**Comment by pendingchaos** [comment]
Should be fixed with https://github.com/daniel-schuermann/mesa/commit/8a8381dd604c5f0a3b677230d683ed27bcad461c (https://gitlab.freedesktop.org/mesa/mesa/commit/ff70ccad16a2efb3be1fbc4ca03453d38721a267 in upstream)
