### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by gort818** [daniel-schuermann/mesa#164]
Trying to build the latest master I am met with this error.

`../mesa-aco/src/compiler/nir/nir_opt_load_store_vectorize.c: In function ‘create_entry’:
../mesa-aco/src/compiler/nir/nir_opt_load_store_vectorize.c:551:50: error: ‘struct <anonymous>’ has no member named ‘access’
  551 |       entry->access = entry->key->var->data.image.access;
      |                                                  ^
[238/2308] Compiling C object 'src/compiler/nir/068b2c8@@nir@sta/.._spirv_vtn_variables.c.o'.
`

**Comment by daniel-schuermann** [comment]
Oops, and I wondered why we get bug reports from outdated commits. I pushed a rebased version which should build fine again.

**Comment by gort818** [comment]
Ok thanks builds now.
