### ISSUE TITLE
"Unsupported opcode" when using ACO on RX 5700 XT

### ISSUE THREAD

**Issue by marhkb** [daniel-schuermann/mesa#165]
**Describe the bug**
Vulkan applications crash with ACO compiler enabled. "RADV_PERFTEST=llvm" works fine. Last tested version  "20.0.0_devel.20191107.2e64afa5e39" was working fine.

**Screenshots**
```
$ vkcubepp                                                                                                                                                                                                  
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: disabling NGG because ACO is used.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: disabling NGG because ACO is used.
Unsupported opcode: exp %14:v[0], %15:v[1], %16:v[2], %17:v[3] en:r*** done vm mrt0[1]    30450 abort (core dumped)  vkcubepp
```

**System information:**
 - GPU: Sapphire Technology Limited Navi 10 [Radeon RX 5700 / 5700 XT] [1da2:e409]
 - ACO version: 20.0.0_devel.20191126.9db4cf56a7d
 - Distribution: Arch Linux
 - LLVM version:  9.0.0-4
 - Kernel: 5.4.0-rc7-amd-staging-drm-next-git-01355-g2c96a366b9a0

**Comment by pendingchaos** [comment]
Should be fixed with https://github.com/daniel-schuermann/mesa/commit/6df53a980c07e9536eddae5aa42a613863b3ab84
