### ISSUE TITLE
Path of Exile (238960) - Global Illumination causes the outline of default Portal effects to be missing.

### ISSUE THREAD

**Issue by ZereoX** [daniel-schuermann/mesa#170]
**Describe the bug**
In Path of Exile ([238960](https://store.steampowered.com/app/238960/Path_of_Exile/)), enabling global illumination causes the white highlight / outline present on the default portal effect to be missing on ACO, but is present on LLVM.

**Screenshots**

| ACO | LLVM |
| --- | --- |
| ![ACO - 20 0~git1912290730 b0203b~oibaf~e](https://user-images.githubusercontent.com/761853/71561492-fc76ac80-2a44-11ea-8edd-f35c7712e331.png) | ![LLVM - 20 0~git1912290730 b0203b~oibaf~e](https://user-images.githubusercontent.com/761853/71561494-ff719d00-2a44-11ea-833a-4c0f7e4f4760.png) |

**RenderDoc capture:**
[Google Drive Link](https://drive.google.com/file/d/1oGl_iqH0rlwAuzU1izBVfMQXFWietgU7/view?usp=sharing) 
_I was unable to open the capture without RenderDoc hanging my system while loading it. Please let me know if there is anything else I can try._

**System information:**
 - GPU: Radeon RX 5700 XT (Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 (rev c1))
 - ACO version: 20.0\~git1912290730.b0203b\~oibaf~e ([PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers))

**Additional context**

- Issue occurs on all 3 [Shadows + GI Quality] presets (Low, High, Ultra).
- Issue can be reproduced by enabling "Shadows + Global Illumination" under the [Lighting] graphical options and using a "Portal Scroll" once outside of any town.

| ![Settings](https://user-images.githubusercontent.com/761853/71562779-3189fb80-2a53-11ea-90a8-8e8ce70d1abd.png) |
| --- |

**Comment by pendingchaos** [comment]
A commit which seems to fix the issue has been pushed: https://gitlab.freedesktop.org/mesa/mesa/commit/809c8feb92d33c43ace3ef25584a2adca24b1be0

It should be included in this repository next time we rebase

**Comment by ZereoX** [comment]
Hey @pendingchaos,

I confirmed the issue was resolved yesterday at work on an RX 580 (20.0\~git2001140730.a9bd06\~oibaf~b), but I'm currently experiencing a launch failure with latest mesa git on my home RX 5700 XT and therefore I can't properly confirm the fix.

I'm using Proton 4.11-12 w/ Mesa 20.0\~git2001151930.af6c2f\~oibaf~e. Title does launches with "RADV_PERFTEST" set to "llvm" in my user_settings.py. I also checked Monster Hunter World and Witcher 3 both launches correctly with it set to aco, so its seems to just be that game.

Wine appears to be crashing in libc.so when ACO is enabled:
> Unhandled exception: assertion failed in 64-bit code (0x00007f87bd07d3eb).
005f:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 rip:00007f87bd07d3eb rsp:000000000cd08430 rbp:000000000cd08810 eflags:00000246 (   - --  I  Z- -P- )
 rax:0000000000000000 rbx:000000000cd13700 rcx:00007f87bd07d3eb rdx:0000000000000000
 rsi:000000000cd08430 rdi:0000000000000002  r8:0000000000000000  r9:000000000cd08430 r10:0000000000000008
 r11:0000000000000246 r12:000000000cd086d0 r13:0000000000000040 r14:00007f8778001000 r15:0000000000000002
Stack dump:
0x000000000cd08430:  0000000000000000 00007f87bd849a9e
0x000000000cd08440:  000000000d553885 0000000000000000
0x000000000cd08450:  0000000000000085 ffff0000ffffffff
0x000000000cd08460:  0000000000000002 0000000000000002
0x000000000cd08470:  0000000000000086 000000007ce28ab0
0x000000000cd08480:  000000000cd08510 000000007cd26e10
0x000000000cd08490:  000000007ce28ab0 0000ffff00001fa0
0x000000000cd084a0:  0000000000000000 0000000000000000
0x000000000cd084b0:  fffffffe7fffffff ffffffffffffffff
0x000000000cd084c0:  ffffffffffffffff ffffffffffffffff
0x000000000cd084d0:  ffffffffffffffff ffffffffffffffff
0x000000000cd084e0:  ffffffffffffffff ffffffffffffffff
Backtrace:
=>0 0x00007f87bd07d3eb execlp+0xffffffffffffffff() in libc.so.6 (0x000000000cd08810)
0x00007f87bd07d3eb execlp+0xffffffffffffffff in libc.so.6: movq	0x0000000000000108(%rsp),%rax

I've attached a video of the launch failure: https://www.youtube.com/watch?v=wKAQa6TSMnU&feature=youtu.be

**Comment by undu** [comment]
The glitch doesn't happen anymore with the latest mesa-aco-git build from valveaur (20.0.0_devel.20200115.6e1411c9e84-7). This is using a Fiji card.

**Comment by ZereoX** [comment]
Hey @pendingchaos 

I ran a git bisect and it would appear the following commit breaks Path of Exile on Navi (at least for me):

> 20d869079de085369eb269489b9b84d3ba8cc3b1 is the first bad commit
commit 20d869079de085369eb269489b9b84d3ba8cc3b1
Author: Rhys Perry <pendingchaos02@gmail.com>
Date:   Tue Dec 10 19:03:42 2019 +0000

    aco: allow input modifiers on v_cndmask_b32
    
    Totals from affected shaders:
    SGPRS: 594099 -> 594019 (-0.01 %)
    VGPRS: 441016 -> 441124 (0.02 %)
    Spilled SGPRs: 101 -> 101 (0.00 %)
    Spilled VGPRs: 18 -> 18 (0.00 %)
    Code Size: 30266652 -> 30125256 (-0.47 %) bytes
    Max Waves: 67044 -> 67057 (0.02 %)
    Instructions: 5753097 -> 5726607 (-0.46 %)
    
    Signed-off-by: Rhys Perry <pendingchaos02@gmail.com>
    Part-of: <https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2883>
    :040000 040000 8e06518544d34d598113fcc8d38883fc61414a5b 
    c1bbc4e18812d163209ac04e0d40367e93d60484 M	src

I reverted to f9405ceb8a73a1dda1ea00619d86427bd62b020c and was able to successfully launch PoE and confirm the Portal effects are appearing correctly: 

| ACO - f9405ce |
| --- |
|![Mesa f9405ce - ACO](https://user-images.githubusercontent.com/761853/72685763-4a6a5780-3abb-11ea-9dda-aa8d05b8a874.png)|


Would you like me to close this ticket out and create a new one for the Launch Failure or should I simply leave this open?

**Comment by pendingchaos** [comment]
Does https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3442 fix the crash?

**Comment by ZereoX** [comment]
Yup, that seems to have done the trick. I'll confirm and close out once it has been merged.

Thank you.

**Comment by ZereoX** [comment]
I've just confirm the issue is resolved on mesa-git  (dbdf3b3ef97e51c31a71b3a27fb84cf89293f57c).

Closing fixed.

Thank you.
