### ISSUE TITLE
Detroit Become Human issues with ACO

### ISSUE THREAD

**Issue by Oschowa** [daniel-schuermann/mesa#171]
Detroit Become Human - both demo and full game - crashes on start-up with ACO enabled, it runs fine with RADV/LLVM, AMDVLK and AMDVLK-pro (although there is some corruption with LLVM on RADV and AMDVLK).
On a debug build, it hits an assertion in ACO code, i'll attach the output and a SPIRV dump.
Unfortunately, trying to record a renderdoc capture leads to an Denuvo 24h ban, so i couldn't record one.
The Demo is free on the Epic Games Store, and should work with lutris.

**System information:**
 - GPU: RX580
 - ACO version: daniel-shuermann master 3409c06

[spirv-dump.txt](https://github.com/daniel-schuermann/mesa/files/4009673/spirv-dump.txt)

[debug.txt](https://github.com/daniel-schuermann/mesa/files/4009672/debug.txt)

![Screenshot from 2019-12-30 11-59-30](https://user-images.githubusercontent.com/8129300/71580374-abc48980-2b00-11ea-955d-476d5b371589.png)

**Comment by tannisroot** [comment]
To get the game running easily, I suggest using Lutris: https://lutris.net/games/detroit-become-human/ (the wine build Lutris uses for this game already contains patches to make it launch and not run at 1 frame per minute).
Note that it's one of those special games with DRM that will ban you for 24h if you dare to change your system configuration (like Mesa version or Wine version).

**Comment by Oschowa** [comment]
I recorded a [gfxreconstruct](https://github.com/LunarG/gfxreconstruct) capture, which reproduces the crash/assertion with ACO when replayed:
https://drive.google.com/open?id=1ojcfd0DcdJt4QF61aXR4vkpn_a3Uj1rl

**Comment by valters-tomsons** [comment]
`wine: Unhandled page fault on read access to 000000000000000C at address 00007FF3946B272A (thread 00db) `

Same with RX 590.

**Comment by Oschowa** [comment]
@pendingchaos I tested https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3257 on top of mesa master, and with this the crash is gone, but the game allocates tons of memory until it is eventually killed. This does not happen with RADV_PERFTEST=llvm

Here is a longer gfxreconsturct capture, which reproduces the memory allocation issue for me:
https://drive.google.com/open?id=1vAaQ7ISAo07CW9YZftQtUqxPug6PIFvk

**Comment by Oschowa** [comment]
A debug build of radv with the above MR applied hits an assertion before running out of memory:
```
mesa/src/amd/compiler/aco_spill.cpp:611: aco::RegisterDemand aco::{anonymous}::init_live_in_vars(aco::{anonymous}::spill_ctx&, aco::Block*, unsigned int): Assertion `!partial_spills.empty()' failed.
```

**Comment by daniel-schuermann** [comment]
@Oschowa is this issue still present?

**Comment by Oschowa** [comment]
The original issue has been fixed, however I'm now getting gpu hangs on master when playing the Demo:
```
[ 1720.199397] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, but soft recovered
[ 1725.319216] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out!
```
This didn't used to happen when I was testing the WIP MR's to fix the crashing issue earlier, but now I haven't found a commit that works. I tested a build of Mesa right after !3257 was merged fwiw.
I also tried to apply !3388 to master, but no changes.

**Comment by pendingchaos** [comment]
Changing this issue to be about a hang/corruptions, since that seems to be what happens for me now (at the very beginning of the demo). Polaris seems to hang while Navi has corruptions. I don't know yet if the two are related

**Comment by pendingchaos** [comment]
Hang should be fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4004

The corruptions still exist though and the hang turned out to be specific to pre-GFX10, so the two are probably not related

**Comment by pendingchaos** [comment]
I think all ACO-specific issues with this game are fixed: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3063
