### ISSUE TITLE
Overwatch - System hang when using ACO

### ISSUE THREAD

**Issue by WannaBeOCer** [daniel-schuermann/mesa#173]
The game randomly causes a system hang when using ACO installed via the ppa:valve-experimental/mesa-bionic. Mesa-dev with LLVM, AMDVLK and amdgpu-pro all work fine with my Radeon VII. 

System:
CPU: Core i9 9900K
GPU: Radeon VII
Ubuntu 18.04
Kernel 5.5rc1-rc5(same issue with 5.0/5.4)

Let me know what's needed to help diagnose the issue.

**Comment by daniel-schuermann** [comment]
Thx for the report! Does it work with mesa upstream or 19.3 with aco? Maybe you can try to grab a renderdoc capture using LLVM in a situation where aco hangs?

**Comment by WannaBeOCer** [comment]
Sorry for the delay, I tested 19.3.2 with ACO this weekend without an issue. It's very random when it happens but it occurs within 3 quick play games. I'm going to try mesa upstream with ACO also and follow up.

**Comment by pendingchaos** [comment]
Why did you close this? Is it fixed now?
