### ISSUE TITLE
Heroes of the Storm - building corruption, supposedly GS

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#176]
Looks like this since recent big ACO update of this repo, so there's some good chance it's due to GS. When the buildings spawn, their geometry also doesn't look correct in the process.

Black areas at buildings and partially misplaced objects (black squares at the core and windows of keeps misplaced):
![Screenshot_20200114_232830](https://user-images.githubusercontent.com/13510490/72388357-fc093180-3725-11ea-871a-0ae7dd78309e.png)

renderdoc capture (doesn't open with llvm, unfortunately):
https://drive.google.com/open?id=1HwWoQshm1RK_DMo2c5iN5YrSLSun_SlX

Any connection to this?
https://github.com/daniel-schuermann/mesa/issues/53
At least it'd be neat if I hadn't have to see it anymore. ;)

RX 570 8GB
mesa-aco a11f0a7666021e20013ef8abb36812bcf2e3e36a
linux 5.5-rc6

**Comment by pendingchaos** [comment]
It's probably not related to #53 

Seems to be a regression from 342bb4ff82548cdc5f494f5dbbed1674ad98d12b

**Comment by pendingchaos** [comment]
Should be fixed with 6e1411c9e8448b22ec38adec8d3267ea4b002109

**Comment by aufkrawall** [comment]
Confirmed, thanks!
