### ISSUE TITLE
Yuzu emulator missing VK_KHR_16bit storage and VK_KHR_8bit_storage

### ISSUE THREAD

**Issue by toccata10** [daniel-schuermann/mesa#177]
yuzu, the nintendo switch emulator is about to get a vulkan renderer.
After compiling this branch: https://github.com/yuzu-emu/yuzu/pull/3337
when I try to launch a game with the vulkan renderer, it quits: the log contains:
```
[  15.277072] Render.Vulkan <Error> video_core/renderer_vulkan/vk_device.cpp:IsSuitable:293: Missing required extension: VK_KHR_16bit_storage
[  15.277075] Render.Vulkan <Error> video_core/renderer_vulkan/vk_device.cpp:IsSuitable:293: Missing required extension: VK_KHR_8bit_storage
[  15.277658] Render.Vulkan <Error> video_core/renderer_vulkan/vk_device.cpp:IsSuitable:357: AMD RADV/ACO FIJI (LLVM 9.0.1) is not suitable
[  15.277663] Core <Critical> core/core.cpp:Load:185: Failed to initialize system (Error 5)!
```
It works fine on llvm.

**Comment by pendingchaos** [comment]
Yes, these extensions are on our TODO list

**Comment by pendingchaos** [comment]
We've implemented both extensions for GFX8+ (I think Fiji is GFX8)

We plan to implement them too for GFX6 and GFX7 in the future

**Comment by pendingchaos** [comment]
Closing this since the extensions are have been implemented for GFX6 and GFX7 in Mesa git

This Github repository is based on Mesa 20.1, so it only supports them on GFX8 and later. Upstream git is needed for these extensions on GFX6 and GFX7 cards
