### ISSUE TITLE
implement bug fixes of the new mesa stable 19.3.3

### ISSUE THREAD

**Issue by felipefacundes** [daniel-schuermann/mesa#180]
implement bug fixes of the new mesa stable 19.3.3:

Bug fixes

    aco: Dead Rising 4 crashes in lower_to_hw_instr() on GFX6-GFX7
    libvulkan_radeon.so crash with `free(): double free detected in tcache 2`
    Commit be08e6a causes crash in com.android.launcher3 (Launcher)
    Mesa no longer compiles with GCC 10
    [bisected] [radeonsi] GPU hangs/resets while playing interlaced content on Kodi with VAAPI
    [radeonsi] MSAA image not copied properly after image store through texture view
    T-Rex and Manhattan onscreen performance issue on Android
    VkSamplerCreateInfo compareEnable not respected
    VkSamplerCreateInfo compareEnable not respected
    Freedreno drm softpin driver implementation leaks memory
    [POLARIS10] VRAM leak involving glTexImage2D with non-NULL data argument

**Comment by daniel-schuermann** [comment]
These bug fixes should be part of the repository, now. Thx!
