### ISSUE TITLE
Window rendering bugs (tabs bar) in Chromium

### ISSUE THREAD

**Issue by Pandiora** [daniel-schuermann/mesa#181]
**Describe the bug**
Window rendering bugs (tabs bar) in Chromium.

**Screenshots**
I'm not sure how to reproduce this issue.

**RenderDoc capture:**
This is not a game-specific issue.

**System information:**
 - AMD 3500U - Vega 8
 - Manjaro Cinnamon
 - aur/lib32-mesa-aco-git 20.0.0_devel.20200107.7b444ba5ef1-9
 - aur/mesa-aco-git 19.3.0_devel.20191017.fe930ad92ab-7
 - extra/chromium 79.0.3945.130-2

**Explanation:**
Just for tracking I decided to open this issue. I lately replaced my mesa driver with this one and noticed the chromium tab bar started to appear to have rendering bugs. Hard to describe, but tabs appear at wrong positions, overlaying each other, wrong fragments of tooltips are shown and so on. The problem disappears if I open another application and this way I'm not able to capture the issue itself without using an external device. (which I should next time)

If I find out how to reproduce this issue I will add it here, but to me it seems this issue takes quite some time to reappear and also seems to be random and can happen no matter which site I'm surfing on.

**Comment by pendingchaos** [comment]
Does it happen with `RADV_PERFTEST=llvm`?

Seems there's also some issues with the LLVM backend: https://gitlab.freedesktop.org/mesa/mesa/issues/2449 . Maybe that's related

RenderDoc could still be useful, I would expect it to work on both games and applications. However I think applications like Chromium often cache rendering results which makes it potentially less useful

**Comment by Pandiora** [comment]
Thank you, good finding. The screenshot and the heavy artifacts are totally different to mine, but I were finally able to take a "screenshot":

![image](https://i.imgur.com/gPjPutm.jpg?1)

At the top left corner the button for adding a new tab can be seen and some of the extension icons too. All of these elements should be normally on the right side of the window, so it seems to me this glitch somehow mirrors elements of the window.

Depending your parameter `RADV_PERFTEST=llvm` I've no idea how to use it system-wide? Besides that it will take quite some time to reproduce this behaviour or to be sure it won't get triggered with this parameter.

Since this problem only occurs for chromium so far it could be unrelated to this driver and I will do some more testing.

**Comment by pendingchaos** [comment]
I think `RADV_PERFTEST=llvm` can be set system-wide with `/etc/environment`. You don't have to set it system-wide though, launching chromium with `RADV_PERFTEST=llvm chromium-browser` should work

It could be related to this driver, lots of issues are only known to happen in a few applications/games

**Comment by BNieuwenhuizen** [comment]
Chromium does not use vulkan unless you specifically enable some experimental setting for Vulkan support. So likely this is a radeonsi bug entirely unrelated to ACO.

**Comment by Pandiora** [comment]
It seems to me some update might've fixed this issue for me or I can't reproduce it currently. I also changed the drivers multiple times in between since I had problems with a game and opengl. Closing this for now or until I encounter this problem again. However, thanks for your help!
