### ISSUE TITLE
Problems with Athlon 3000G (or Vega 3)

### ISSUE THREAD

**Issue by master-caster** [daniel-schuermann/mesa#182]
**Describe the bug**
I have upgraded from fedora 31 to 32. That seems to mean that ACO is now enabled
by default. But ACO is causing some errors/glitches using OpenGL. I'm on wayland
and compared to my other system i need to wait for xorg 1.20.7 to fix some vulkan 
issues with xwayland. So vulkan is not an option for now.

Some shader effects cause curious color effects. I'm pretty sure there is a name for
it but I don't know it. (sry for that) 
Have a look at the screenshot.

I tried using `RADV_PERFTEST=llvm` but it doesn't seem to work.
On the otherhand using `RADV_PERFTEST=aco` on Fedora 31 it creates
the same issues.

The screenshot is from Resident evil 4 but the native running F1 2015 shows
the same effect.

**Screenshots**
![Bildschirmfoto von 2020-03-12 19-43-15](https://user-images.githubusercontent.com/2255421/76626310-3716be00-6539-11ea-93ec-bb1a8108316e.png)

**System information:**
inxi -b
System:    Host: mantis Kernel: 5.6.0-0.rc4.git0.1.fc32.x86_64 x86_64 bits: 64 Desktop: Gnome 3.36.0 
           Distro: Fedora release 32 (Thirty Two) 
Machine:   Type: Desktop System: Gigabyte product: B450M S2H v: N/A serial: <root required> 
           Mobo: Gigabyte model: B450M S2H v: x.x serial: <root required> UEFI: American Megatrends v: F50 date: 11/27/2019 
CPU:       Dual Core: AMD Athlon 3000G with Radeon Vega Graphics type: MT MCP speed: 1495 MHz min/max: 1600/3500 MHz 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Picasso driver: amdgpu v: kernel 
           Display: wayland server: Fedora Project X.org 1.20.6 driver: amdgpu resolution: 1536x864~60Hz 
           OpenGL: renderer: AMD RAVEN2 (DRM 3.36.0 5.6.0-0.rc4.git0.1.fc32.x86_64 LLVM 10.0.0) v: 4.6 Mesa 20.0.1 
Network:   Device-1: Realtek RTL8812AE 802.11ac PCIe Wireless Network Adapter driver: rtl8821ae 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           Device-3: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad 
Drives:    Local Storage: total: 238.47 GiB used: 150.59 GiB (63.1%) 
Info:      Processes: 266 Uptime: 2m Memory: 13.67 GiB used: 2.10 GiB (15.4%) Shell: bash inxi: 3.0.37 
rpm -qa | grep -i mesa
mesa-libglapi-20.0.1-1.fc32.i686
mesa-libGL-20.0.1-1.fc32.x86_64
mesa-vulkan-drivers-20.0.1-1.fc32.i686
mesa-libGL-20.0.1-1.fc32.i686
mesa-dri-drivers-20.0.1-1.fc32.i686
mesa-libglapi-20.0.1-1.fc32.x86_64
mesa-libxatracker-20.0.1-1.fc32.x86_64
mesa-libgbm-20.0.1-1.fc32.x86_64
mesa-dri-drivers-20.0.1-1.fc32.x86_64
mesa-filesystem-20.0.1-1.fc32.x86_64
mesa-vulkan-drivers-20.0.1-1.fc32.x86_64
mesa-libEGL-20.0.1-1.fc32.x86_64
mesa-libOSMesa-20.0.1-1.fc32.x86_64
mesa-filesystem-20.0.1-1.fc32.i686
mesa-libGLU-9.0.1-2.fc32.x86_64
mesa-libOpenCL-20.0.1-1.fc32.x86_64

**Comment by Oschowa** [comment]
ACO is neither enabled by default in upstream Mesa nor hooked up for OpenGL at all, so your issue is most likely not ACO related.

**Comment by master-caster** [comment]
Any idea where to open an issue for that?
On fedora 31 (I don't know the right package versions) it looks like the creator 
wanted it to look like.
Enabling ACO created this issue
Feel free to close it if doesn't belong here.

**Comment by Oschowa** [comment]
If the game is actually using OpenGL, there is no way ACO has any effect on it.
Are you running RE4 with Proton? Proton recently enabled DXVK by default for dx9 games (which RE4 is) and would thus be using vulkan for that.
Issues not specific to ACO you should report here: https://gitlab.freedesktop.org/mesa/mesa/issues

**Comment by master-caster** [comment]
Yes. I'm using steam proton 5.xxx but I disabled "dx9k" or what it was called in earlier releases
due to the fact that my xwayland won't support vulkan for some reason. So I use
`PROTON_USE_WINED3D` to enforce OpenGL.

So vulkan via xwayland seem to work on my ubuntu 20.04 that uses xorg 1.20.7 so I think
there are some fixes left to get vulkan work with xwayland.

But of course I'm using a different hardware setup on both systems!

**Comment by Oschowa** [comment]
I'm not aware of any xwayland issue preventing vulkan to work and it does work for me on 1.20.7.
Anyways, if your sure you're using OpenGL (maybe set DXVK_HUD=1 as launch option in steam for RE4 and see if the HUD shows up) you should close this issue and create a new one on the mesa bugtracker.

**Comment by master-caster** [comment]
will DXVK_HUD=1 work with OpenGL?
And thx for your reply i'll give it a try

**Comment by Oschowa** [comment]
No, DXVK_HUD=1 should have no effect with OpenGL

**Comment by master-caster** [comment]
Okay i gave it a shot and try it with
`DXVK_HUD=1 %command%` 
no different visible.

So i don't know what should be visible using this environment variable
but it looks like it is using opengl.
So as of your recommendation i close this for not being ACO related
