### ISSUE TITLE
Has ACO being main streamed into MESA yet? 

### ISSUE THREAD

**Issue by pure-water** [daniel-schuermann/mesa#185]
I noticed the commit message is talking about enable ACO by default. Just wondering what is the plan to push to main stream mesa library?

**Comment by pendingchaos** [comment]
Yes, it's included since 19.3: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2009

It will be enabled by default in 20.2 (RADV_PERFTEST=llvm is replaced with RADV_DEBUG=llvm): https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5445
