### ISSUE TITLE
ACO shader makes textures color flickering with Assassin's Creed Origins

### ISSUE THREAD

**Issue by Philippe734** [daniel-schuermann/mesa#186]
The use of ACO shader compiler with Assassin’s Creed Origins makes issue with some textures. On ground or ceiling, there is a color flickering, hard to see. **Here attached two screencasts**, with ACO enabled and disabled. Watch the ground and the ceiling of the temple. That issue exist with mesa 20.0 and mesa-git 20.3. To run the game without ACO, I use the following prefix command to disable ACO and use LLVM `RADV_DEBUG=llvm`

**System information:**
Ubuntu 20.04
Mesa driver 20.0 and 20.3
Radeon RX 5600 XT
```
inxi -Gxz
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: Gigabyte 
           driver: amdgpu v: kernel bus ID: 03:00.0 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: AMD Radeon RX 5600 XT (NAVI10 DRM 3.38.0 5.8.13-050813-generic LLVM 10.0.1) 
           v: 4.6 Mesa 20.3.0-devel (git-ef918f0 2020-10-04 focal-oibaf-ppa) direct render: Yes 
```
Screencast with ACO enabled:
https://www.dropbox.com/s/f019wnyig1ppn1e/ACO-enabled-assassinscreedorigins.mkv?dl=0
Screencast with ACO disabled (with LLVM):
https://www.dropbox.com/s/nrcwly94jb7n5pa/ACO-disabled-assassinscreedorigins.mkv?dl=0

**Comment by Venemo** [comment]
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.
