### ISSUE TITLE
Dawn of War 3 assert in spilling code

### ISSUE THREAD

**Issue by tarceri** [daniel-schuermann/mesa#23]
aco_spill.cpp void process_block() assert(distance != 0);

**Comment by daniel-schuermann** [comment]
current build? Because I fixed one bug causing this assert in adcc026e8b1d04804c37e254052bdaf1890192c4

**Comment by tarceri** [comment]
Yeah I pulled and rebased your latest branch on Mesa this morning before reporting these.

**Comment by pendingchaos** [comment]
02cb647fa1785f0aaf0c451ca13aad0bfa82b239 prevents a Dawn of War 3 shader from triggering this assert, so this should be fixed.
