### ISSUE TITLE
CTS Coverage

### ISSUE THREAD

**Issue by daniel-schuermann** [daniel-schuermann/mesa#30]
Tested with Polaris on current CTS master

dEQP-VK.info.*
  Passed:        4/4 (100.0%)

dEQP-VK.api.*
  Passed:        30291/88391 (34.3%)
  Failed:        5/88391 (0.0%)
  Not supported: 58096/88391 (65.7%)
Fails (RADV):
dEQP-VK.api.info.image_format_properties.2d.optimal.g8_b8_r8_3plane_420_unorm
dEQP-VK.api.info.image_format_properties.2d.optimal.g8_b8r8_2plane_420_unorm
dEQP-VK.api.info.android.no_unknown_extensions
dEQP-VK.api.info.android.no_layers
dEQP-VK.api.invariance.random (../src/amd/vulkan/radv_image.c:1038: radv_image_create: Assertion `info.width % desc->width_divisor == 0' failed.)

dEQP-VK.memory.*
  Passed:        2602/2828 (92.0%)
  Not supported: 226/2828 (8.0%)

dEQP-VK.pipeline.*
  Passed:        46437/86979 (53.4%)
  Not supported: 40542/86979 (46.6%)

dEQP-VK.binding_model.*
  Passed:        47214/47552 (99.3%)
  Not supported: 338/47552 (0.7%)

dEQP-VK.spirv_assembly.*
  Passed:        5324/25772 (20.7%)
  Not supported: 20444/25772 (79.3%)
  Warnings:      4/25772 (0.0%) (from LLVM)

dEQP-VK.glsl.*
  Passed:        16066/17929 (89.6%)
  Failed:        26/17929 (0.1%)
  Not supported: 1837/17929 (10.2%)
Fails:
dEQP-VK.glsl.linkage.*
  Failed:        1/69 (1.4%)
dEQP-VK.glsl.440.*
  Failed:        25/68 (36.8%)

dEQP-VK.renderpass.*
  Passed:        11134/13139 (84.7%)
  Not supported: 2005/13139 (15.3%)

dEQP-VK.renderpass2.*
  Passed:        7318/13541 (54.0%)
  Not supported: 6223/13541 (46.0%)

dEQP-VK.ubo.*
  Passed:        6215/8965 (69.3%)
  Not supported: 2750/8965 (30.7%)

dEQP-VK.dynamic_state.*
  Passed:        15/15 (100.0%)

dEQP-VK.ssbo.*
  Passed:        4764/7904 (60.3%)
  Not supported: 3140/7904 (39.7%)

dEQP-VK.query_pool.*
  Passed:        644/644 (100.0%)

dEQP-VK.draw.*
  Passed:        540/543 (99.4%)
  Not supported: 3/543 (0.6%)

dEQP-VK.compute.*
  Passed:        69/869 (7.9%)
  Not supported: 800/869 (92.1%)

dEQP-VK.image.*
  Passed:        10653/20810 (51.2%)
  Not supported: 10157/20810 (48.8%)

dEQP-VK.wsi.*
  Passed:        135/485 (27.8%)
  Failed:        1/485 (0.2%)
  Not supported: 349/485 (72.0%)
Fails (RADV):
dEQP-VK.wsi.display.get_display_plane_capabilities2

dEQP-VK.synchronization.*
  Passed:        11509/23409 (49.2%)
  Not supported: 11900/23409 (50.8%)

dEQP-VK.sparse_resources.*
  Passed:        154/1636 (9.4%)
  Not supported: 1482/1636 (90.6%)

dEQP-VK.tessellation.*
  Passed:        432/432 (100.0%)

dEQP-VK.rasterization.*
  Passed:        113/177 (63.8%)
  Not supported: 64/177 (36.2%)

dEQP-VK.clipping.*
  Passed:        307/307 (100.0%)

dEQP-VK.fragment_operations.*
  Passed:        35/35 (100.0%)

dEQP-VK.texture.*
  Passed:        4482/9430 (47.5%)
  Not supported: 4948/9430 (52.5%)

dEQP-VK.geometry.*
  Passed:        141/146 (96.6%)
  Not supported: 5/146 (3.4%)

dEQP-VK.robustness.*
  Passed:        762/762 (100.0%)

dEQP-VK.multiview.*
  Passed:        284/324 (87.7%)
  Not supported: 40/324 (12.3%)

dEQP-VK.subgroups.*
  Passed:        3529/6053 (58.3%)
  Not supported: 2524/6053 (41.7%)

dEQP-VK.ycbcr.*
  Passed:        13/21895 (0.1%)
  Not supported: 21882/21895 (99.9%)

dEQP-VK.protected_memory.*
  Not supported: 4357/4357 (100.0%)

dEQP-VK.device_group.*
  Passed:        6/12 (50.0%)
  Not supported: 6/12 (50.0%)

dEQP-VK.memory_model.*
  Passed:        318/12222 (2.6%)
  Not supported: 11904/12222 (97.4%)

dEQP-VK.conditional_rendering.*
  Passed:        134/184 (72.8%)
  Not supported: 50/184 (27.2%)

dEQP-VK.amber-example.clear
  Passed:        1/1 (100.0%)

dEQP-VK.graphicsfuzz.*
  Passed:        10/10 (100.0%)

**Comment by pendingchaos** [comment]
Nearly all supported tests are passing.
