### ISSUE TITLE
Built the repo, but no console warning is shown

### ISSUE THREAD

**Issue by shmerl** [daniel-schuermann/mesa#34]
Just built the repo, run a few things with it, including vkcube, but it's not showing the warning, so I'm not sure if compiler is active.

**Comment by shmerl** [comment]
Ah, I probably skipped setting Meson option to enable it, since I'm using regular Mesa building script. Checking.

**Comment by pendingchaos** [comment]
It's enabled by default and there is no Meson option to enable it. What GPU are you using? Not all are supported.

**Comment by shmerl** [comment]
Vega 56. Let me check my build and re-try it again. May be something was wrong there.

I wonder if some build dependency is missing may be, and it gets disabled, or the build will simply fail in such case?

**Comment by shmerl** [comment]
OK, I see that `libaco.a` got build, and 
`WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely` cooked into resulting `libvulkan_radeon.so`, so build should be good.

Ah, I see it now. I messed up with ICD json, it points to the wrong file for me. Re-trying now.

**Comment by shmerl** [comment]
Yep, I get the warning now. So all is good.
