### ISSUE TITLE
Nex Machina crashes on startup

### ISSUE THREAD

**Issue by undu** [daniel-schuermann/mesa#37]
After the videos get played, the loading screen gets displays but crashes very soon after that.
I can get to the start menu and in-game with `PROTON_NO_ESYNC=1 RADV_PERFTEST=llvm`

I'm using the AUR packages.

Proton: 4.2-9
Kernel: 5.1.15-arch1-1-ARCH
CPU: AMD Ryzen 7 1700
GPU: AMD ATI Radeon R9 NANO Series

**Comment by daniel-schuermann** [comment]
Thank you! Would you be able to create a debug build and paste the output from /.steam/error.log ?

**Comment by undu** [comment]
I'm not familiar with meson and couldn't find the option in `meson_options.txt`. How do I go about to enable a debug build?

In the meantime the current AUR build outputs this on the terminal: [crashdump.log](https://github.com/daniel-schuermann/mesa/files/3357956/crashdump.log)

**Comment by daniel-schuermann** [comment]
Thanks! This is very helpful.
I already know where the bug has to be. To find it quickly, would you give me the same crashdump, but this time with RADV_DEBUG=nocache,preoptir ? (Note, the file probably gets huge)

**Comment by daniel-schuermann** [comment]
sorry, I mean with RADV_DEBUG=nocache,shaders,preoptir (seems, it doesn't output anything without shaders added)

**Comment by undu** [comment]
This one is a bit bigger :)

[out.log.gz](https://github.com/daniel-schuermann/mesa/files/3360265/out.log.gz)

**Comment by daniel-schuermann** [comment]
Ok, found the issue. I'll get back to you when I have a patch. Thx!

**Comment by daniel-schuermann** [comment]
Would you be able to apply [this patch](https://pastebin.com/Ud4QZcSm) on master and test if the problem persists? If you need instructions, feel free to ask.

**Comment by daniel-schuermann** [comment]
We decided to push the fix already. You should automatically get a driver update as soon as the package gets updated. Thx!

**Comment by undu** [comment]
I can confirm it fixes the crash, thanks!
