### ISSUE TITLE
RPCS3 emulator - Persona 5 crashes during pipe object compilation stage

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#40]
When running Persona 5 with the PS3 emulator, RPCS3, the game crashes with the Vulkan renderer during pipe object compilation with this message:
`Number of Operands does not match number of predecessors:  v1: %485 = p_phi Number of Operands does not match number of predecessors:  v1: %351, %481%532 = p_phi                                                                                             
Number of Operands does not match number of predecessors:  %415,  v1: %484 = %529
Number of Operands does not match number of predecessors:  v1: %531p_phi %350, %480
Number of Operands does not match number of predecessors:  v1: %483 = p_phi %349, %479
Number of Operands does not match number of predecessors:  v1:  = p_phi %414, %482 = p_phi %129%528
Number of Operands does not match number of predecessors:  v1: %530 = p_phi %413, %478, %527
rpcs3: ../src/amd/compiler/aco_validate.cpp:216: void aco::validate(aco::Program*, FILE*): Assertion 'is_valid' failed. 
rpcs3: ../src/amd/compiler/aco_validate.cpp:216: void aco::validate(aco::Program*, FILE*): Assertion 'is_valid' failed.
`
The problem does not occur with RADV_PERFTEST=llvm.

System:
Gentoo AMD64
Mesa ACO git
RPCS3 git
Vega 56

**Comment by daniel-schuermann** [comment]
Thank you very much! Would you be able to provide the complete output containing the intermediate representation of the shader? Unfortunately, I cannot test games myself using an emulator, for legal reasons.

**Comment by aqxa1** [comment]
It's not really clear exactly which shader is failing (and logs look to not be saved when it crashes like this), but I'll see what I can do.

**Comment by aqxa1** [comment]
Hello again. I've attached a set of pipelines and raw shaders built using ACO from a cold cache, which subsequently crashes as before.

I'm not sure these are the format you are looking for, as there a number of other caches included with RPCS3, although I suspect most are CPU and sound related

The following is the last filename by date, which may be the offending pipeline, but I uploaded the rest as they are small in size:
Pipeline filename: D2D4290EC8ED4977+F3DAF8643A2780E5+8DB8BEFC16EF8B20+400F.bin
Raw filename: D2D4290EC8ED4977.vp

If these aren't right, I'll get in touch with the RPCS3 developers to clarify what is needed.

[persona5_pipelines_raw.zip](https://github.com/daniel-schuermann/mesa/files/3361405/persona5_pipelines_raw.zip)

**Comment by daniel-schuermann** [comment]
Is the moment when the game crashes reproducible and always at the same position? Then, it might be easiest to grab a renderdoc capture with llvm enabled just at the moment after this would happen with aco. Do you have any instructions how to replay the provided pipeline?

**Comment by aqxa1** [comment]
>Is the moment when the game crashes reproducible and always at the same position?

The way it works is that the emulator itself compiles and loads the pipelines at launch of the game. So while it's reproducible, it would be difficult to trace it with renderdoc (although I could try it).

>Do you have any instructions how to replay the provided pipeline?

No idea if that is even supported. RPCS3 has something called RSX capture, but I suspect the same problem, that the emulator would crash before I could create a capture.

It might be possible for pipeline compilation to be delayed until it's needed in game (there may be an option for that) which might make it easier to trace.

EDIT: I tried to get a renderdoc trace, but it crashes before it can save. And it seems like the pipeline that fails is pretty much immediate, even when disabling the caches that I could disable.

**Comment by HerrHulaHoop** [comment]
@aqxa1 is this specific to Persona 5 or does it crash with any pipe object compilation? RPCS3 comes with a couple ELF files that usually generate one or two shaders. If you experience the same crash with those files, then reproducing the same should become much simpler.

The ELF files are located at `~/.config/rpcs3/dev_hdd0/game/TEST12345/USRDIR/`
You can boot them by selecting `File -> Boot SELF/ELF` and navigating to the files. AFAIK gs_gcm_basic_triangle, gs_gcm_cube and gs_gcm_tetris generate shaders.

**Comment by aqxa1** [comment]
It does look to be Persona 5 specific. Other commercial games work (MGS: Peace Walker), and all of the tests were fine.

**Comment by daniel-schuermann** [comment]
Fixed with commit 0ba58be607f5b47cd51ab7fb38d83aa3d86ee9c7 .
Thx!
