### ISSUE TITLE
Batman Arkham Knight freezes

### ISSUE THREAD

**Issue by TheAquabat** [daniel-schuermann/mesa#41]
Batman Arkham Knight freezes, frames drop to 0 fps on the benchmark test, with normal radv frames do not dip below 20 fps more or less. There is two parts of the benchmark where it really freezes hard.

**Comment by tarceri** [comment]
Just thought I should note there were some fairly large regressions in my vkpipeline-db testing with Batman Arkham City which is likely related.

 ```
PERCENTAGE DELTAS    Shaders     SGPRs     VGPRs SpillSGPR SpillVGPR  PrivVGPR   Scratch  CodeSize  MaxWaves     Waits
 batman-arkham-city      2581    9.34 %   22.43 % -100.00 %     .         .         .       -1.85 %  -15.50 %     .    
```

**Comment by TheAquabat** [comment]
I see, if I run the benchmark with RADV_PERFTEST=llvm variable it should use the same git commit but with llvm shader compiler?? just to discard this.
I was testing against 19.1.1.

**Comment by TheAquabat** [comment]
with RADV_PERFTEST=llvm it doesn't happen in fact the minimum fps I get is 42.

**Comment by tarceri** [comment]
Thanks for the report. However I think you are mistaken here, I can definitely reproduce the stalls at the start and end of the benchmark on llvm.

I can also avoid the minimum fps drop at the start of the benchmark if I start running the benchmark then press esc 2 times to exit and then rerun the benchmark. Maybe that's what you did? It could also be that the stall has a random nature to it that caused you not to see it on you llvm run. All I can say for sure is I was able to reproduce with llvm.

**Comment by daniel-schuermann** [comment]
chancho-zombie, could this elaboration help you? Or is this game still having strong performance problems with ACO? (i.e. the ingame framerate is notably worse with ACO than when using LLVM).
Thx!

**Comment by daniel-schuermann** [comment]
We made a note to investigate the performance of this game. Thx.
