### ISSUE TITLE
Dark Souls 3 character load freeze

### ISSUE THREAD

**Issue by SpookySkeletons** [daniel-schuermann/mesa#42]
Dark Souls 3 seems to freeze a moment before the loading screen disappears.
Can't load in as any particular character but the background audio loop of the wind still plays.

**Comment by daniel-schuermann** [comment]
Thank you for reporting this issue. Would you be able to start the game with RADV_PERFTEST=llvm and take a renderdoc capture of the scene (a moment after the freeze with ACO)?

**Comment by SpookySkeletons** [comment]
I can confirm that RADV_PERFTEST=llvm works just fine with my ACO PPA.
Do you have a guide on hand to use renderdoc with a Steamplay game?

**Comment by daniel-schuermann** [comment]
works with most games:
you start steam from the console via
ENABLE_VULKAN_RENDERDOC_CAPTURE=1 RADV_PERFTEST=llvm steam
(not sure if you have to have renderdoc opened while doing so)
Then you can take a capture ingame which gets saved to /tmp/renderdoc/

**Comment by SpookySkeletons** [comment]
Got it uploading now.
Wasn't super exact about the timing but it won't hurt if it's a few frames after?

**Comment by SpookySkeletons** [comment]
And done! Hope this can help!
https://anonfile.com/cfk9Z0xfn2/DarkSouls3.tar_gz

**Comment by regulator-g** [comment]
Hi guys yeah same issue: dark souls 3 starts and runs, select char, loading screen w/ animation then the animation stops and music keeps playing, you can still alt+tab and quit the game

I had steam running from terminal saw this written not sure if its helpful:
ERROR: ld.so: object '/home/gaben/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by hmph123** [comment]
Yep, same issue.

**Comment by daniel-schuermann** [comment]
Fixed with eebe7f88564043f62c8228bb700a6fb2b08c8f93 (master) and 465d1fe3b0f0ab60bd7b5fef879dac560eea6777 (backend). Thx!
