### ISSUE TITLE
Using touchscreen lead to crash Gnome of Wayland session

### ISSUE THREAD

**Issue by luyatshimbalanga** [daniel-schuermann/mesa#45]
Test done with a HP Envy x360 Ryzen 2500u on Fedora 30 Workstation using latest ACO. Touching a screen on Gnome on Wayland session causes a crash forcing an user to reboot the system while wsing a stylus on some touchscreen laptop has no visible impact.
Problem may affect other distribution running on touchscreen laptop.

**Comment by daniel-schuermann** [comment]
Thanks! Can you confirm, this doesn't happen with RADV_PERFTEST=llvm or with upstream mesa?
Also, I'd be glad about any error logs / crashdumps about this issue.

**Comment by luyatshimbalanga** [comment]
Here is the log
[journalctl-report.txt](https://github.com/daniel-schuermann/mesa/files/3359440/journalctl-report.txt)

Upstream mesa is not affected per se. I don't know how to use RADV_PERFTEST=llvm on Gnome Wayland session or login.

**Comment by daniel-schuermann** [comment]
Looking at the log, it seems that the crash is happening in radeonSI, thus unrelated to ACO. If current upstream works for you, then I assume that this might have been fixed meanwhile upstream. We will probably rebase in the next couple of days which should fix the issue for us as well.

**Comment by luyatshimbalanga** [comment]
Thanks. I'll let you know if the fix worked.

**Comment by luyatshimbalanga** [comment]
You are right. The bug occurred with the mix of llvm-git and mesa-git impacting mutter when running on Wayland session.
