### ISSUE TITLE
Devil May Cry 5 freezes when trying to compile some random shader

### ISSUE THREAD

**Issue by Valmar33** [daniel-schuermann/mesa#46]
I removed my old `DevilMayCry5.dxvk-cache` prior to the run, along with my old Mesa shader cache.

I'm running close to the latest master of DXVK.

Here is the crash output for the shader/s. Hope it helps:

[ACO-freeze.log.txt](https://github.com/daniel-schuermann/mesa/files/3358705/ACO-freeze.log.txt)

When it freezes, the music is still playing, interestingly. I can even close the window, but the music still plays, and the process is stalled until killed.

**Comment by pendingchaos** [comment]
I think this might be the same issues as https://github.com/daniel-schuermann/mesa/issues/44
Are you able to test the patch pasted there: https://pastebin.com/dge2ZVwm ?

**Comment by Valmar33** [comment]
That seems to fix it, thanks. :)
