### ISSUE TITLE
ACO compiler with OpenGL

### ISSUE THREAD

**Issue by SpookySkeletons** [daniel-schuermann/mesa#50]
Not seeing this brought up anywhere else but would OpenGL benefit from ACO's use?
Any way to patch it in to test currently or down the line?

**Comment by daniel-schuermann** [comment]
Thanks for asking!
Unfortunately, there is no quick way to integrate OpenGL (RadeonSI, that's the Mesa AMD OpenGL driver) with ACO. However, we will definitely consider it once ACO is more stable and feature-rich.

**Comment by SpookySkeletons** [comment]
Very nice! Thank you.
