### ISSUE TITLE
Path of Exile Proton: load screen hangs

### ISSUE THREAD

**Issue by TimoFreiberg** [daniel-schuermann/mesa#51]
EDIT: For anyone with the same issue: After setting the environment variable `RADV_DEBUG=nocache` I get the same `division by zero` exception as in #49.

This seems like a different issue than #49 so I'm creating a separate one.

Proton 4.2.9
RX580

After ~3 seconds, the load screen animation (the turning gears) stops and the load screen stays frozen for at least ~5 minutes (i killed it then)
This happens both with and without `gamemoderun` and with or without `DXVK_STATE_CACHE=0`

After disabling ACO with `RADV_PERFTEST=llvm`, it loads and runs like before (playable but annoyingly unsmooth)

Here's the stdout, nothing jumped out at me: https://gist.github.com/TimoFreiberg/4646799bf711548b1afef446e38b8c21

Do you think a RenderDoc capture will help? Do you want one of the load screen or of the loaded game directly after the load screen?

**Comment by TimoFreiberg** [comment]
After trying it again, I could load into a few zones successfully. The load screen for some zones (Hideout and Labyrinth) hung again though.

**Comment by daniel-schuermann** [comment]
Could you test with RADV_DEBUG=nocache ? I'm not completely sure if this is actually a problem with the compiler... Which build are you using?

**Comment by TimoFreiberg** [comment]
I was using `19.2.0_devel.113497.8e93352dc14`.
I since reinstalled the old mesa version because my PC crashed a few times which I attributed to it being mesa-git (hasn't crashed since so...) - but I can reinstall it in a few minutes and check!

**Comment by TimoFreiberg** [comment]
Alright, with `RADV_DEBUG=nocache` I get the same `divide by zero` exception as in #49 :)
Closing this one
