### ISSUE TITLE
visual corruption in Heroes of the Storm - supposedly game bug, but fixed in proprietary compilers

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#53]
Hello,
there is this kind of corruption:
![hots](https://user-images.githubusercontent.com/13510490/60688506-e46b0980-9eb5-11e9-98e0-9eebd439b515.png)

The issue occurs with:
dxvk radv-aco
dxvk radv-llvm
dxvk amdvlk-llvm
wined3d11 radeonsi-llvm

The issue does not occur with:
AMD, Nvidia and Intel native D3D11
dxvk amdvlk-proprietary
dxvk nvidia

Quoting Rhys Perry from here:
https://bugs.freedesktop.org/show_bug.cgi?id=109394

 > I think this is a game bug: it's using implicit derivatives when sampling textures in non-uniform control flow. In the GLSL and SPIR-V spec, the results are undefined. I think it's the same with HLSL.
Since the control flow is non-uniform and (IIRC) LLVM seems to move the operations creating the texture coordinates into it, I think it's causing discontinuities and messing up the LOD calculation.
 >

Would it be possible to fix it in ACO?

**Comment by baryluk** [comment]
It is probably best to report the issue to Blizzard first.

**Comment by aufkrawall** [comment]
Somebody may do so, but nothing will happen. They don't even fix undefined cubemap behavior that badly affects AMD and Intel D3D11 on native Windows.

**Comment by baryluk** [comment]
> Somebody may do so, but nothing will happen. They don't even fix undefined cubemap behavior that badly affects AMD and Intel D3D11 on native Windows.

I understand that. But it is worth a try nevertheless. Even if likely hood of fixing it 2%.

**Comment by aufkrawall** [comment]
Since the game receives only content updates and no engine fixes: Any chance to address this in between of the other goodness?
The game is not playable with amdvlk-pro driver due to missing shader cache, while Nvidia users don't have the artifacts, but have a shader cache at the same time.

**Comment by Venemo** [comment]
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.

**Comment by aufkrawall** [comment]
This is fixed in RADV/ACO, though can't say since when.
Funny thing is that since AMD have switched to LLPC also for their Windows Vulkan driver with RDNA3 (and PRO driver on Linux uses it too with RDNA3), it shows the issue as well. Unlike RDNA2 driver, that is still using the proprietary compiler (apart from amdvlk-open).

**Comment by pendingchaos** [comment]
> This is fixed in RADV/ACO, though can't say since when.

Probably https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22636
