### ISSUE TITLE
Outlast 2 won't start

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#54]
Has anyone tested Outlast 2 lately? Something broke, somewhere sometime.
But, I'm not sure that ACO is the problem. I'll keep trying.

**Comment by daniel-schuermann** [comment]
Hi, thx for reporting. I'd appreciate if you could add some more information like which graphics card you are using, if it's working with LLVM enabled and maybe paste the error.log from /.steam/error.log so that we can investigate.

**Comment by SR-dude** [comment]
I've been working with different version of Mesa, this years wine releases and this has nothing to do with ACO. It last worked on 07/14/18. I'll have to find a way to retrace my steps.
I'll try some old version of wine. I'm not a SteamPlay user. So, I  run the windows version of steam
in a wine prefix.  I'll close this and go else where.

**Comment by SR-dude** [comment]
I tried wine master without the staging patches and it worked.

**Comment by SR-dude** [comment]
It runs fine with ACO. Success!
