### ISSUE TITLE
Path of Exile water texture corruption  

### ISSUE THREAD

**Issue by jackarsnel** [daniel-schuermann/mesa#55]
Non moving water is black on the floor and not rendering correctly, see below pictures for reference and gist for hardware info. 

https://steamuserimages-a.akamaihd.net/ugc/786358006022392530/C1AFB2079B5B860E67C84DF77D18209B6D36BBC9/

https://steamuserimages-a.akamaihd.net/ugc/786358006022413958/1EA7EE2D14A25D6991DEF273B68DC754CF4394BD/

https://gist.github.com/jackarsnel/dc28daa6e91f3c7649b6a5409fee4458

**Comment by cheald** [comment]
I'm seeing this as well. Running ACO on a RX590 via Proton-4.2-9.

**Comment by ripper81** [comment]
Yes the same over here, i am also using an RX590.

**Comment by pendingchaos** [comment]
The water should be rendering correctly after 79c130f2e3de92cab0279773a4da2a4232b59f0a, bf454aab5324c9ea5ba06e914b2bb50762a3248a and 2f3b6ae50bf48416b0ffa6f8f0e06b382ea7de7a.

**Comment by ernstp** [comment]
Yes, nice!
