### ISSUE TITLE
Dying Light colors don't look right

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#56]
Dying Light colors look almost washed out. Almost B & W.

**Comment by aqxa1** [comment]
I can reproduce this.

ACO: 
![ACO](https://i.imgur.com/tU25i49.jpg)

LLVM:
![LLVM](https://i.imgur.com/SxKWJrH.jpg)

[Renderdoc](https://drive.google.com/open?id=1PH1AkwrWgvewHQ1Ec0EUUIaf5xU4c9Fy) with both ACO and LLVM

System:
Vega 56
Dying light with DXVK git

**Comment by SpookySkeletons** [comment]
As an aside the game benefits so massively from ACO it's actually dropped my jaw.

But I have the same issue on my Polaris WX7100 mobile GPU, some sort of post process had the color sucked out of it so everything is a dull grey color with poor lighting on every surface.

**Comment by daniel-schuermann** [comment]
Thx, we found the issue and the fix probably won't affect performance. I'll get back when we figured how to solve it.

**Comment by SR-dude** [comment]
To be  frank, the second screenshot doesn't look great either, It looks ok with  Mesa 19.1.1.

**Comment by daniel-schuermann** [comment]
yes, LLVM also got affected by a change we made to the frontend.

**Comment by SR-dude** [comment]
FYI, I'm using LLVM 8.0.0.  8.0.1 is suppose to be released by 20th of this month.

**Comment by pendingchaos** [comment]
Should be fixed with 833c5a809037492f01f5ee9da3abf858396489d4 (master) and 53c1a6379f69e9e0980bc2c677c1798106b60b9e (backend).

**Comment by SR-dude** [comment]
It looks good!
