### ISSUE TITLE
War Thunder mesa ACO vulkan API : clouds textures corrupted

### ISSUE THREAD

**Issue by radube2** [daniel-schuermann/mesa#59]
Hi,
this is not a DXVK gameplay but I think it still relates to ACO issues

Testing War Thunder on vulkan API (beta version of game)
When using ACO clouds get artefacts (squares or lines depending on video settings)
When applying RADV_PERFTEST=llvm the clouds are fine

I'm using Antergos
kernel 5.1.15
Mesa 19.2.0-devel LLVM 8.0.0
GPU : RX 470 4GB

Attached are two screenshots: one using ACO where clouds are corrupted and one applying RADV_PERFTEST=llvm where clouds are fine
![Screenshot from 2019-07-06 03-02-21](https://user-images.githubusercontent.com/19916015/60749020-b4e2fc80-9f9c-11e9-9333-ecd5dc92be1b.png)
![Screenshot from 2019-07-06 03-04-04](https://user-images.githubusercontent.com/19916015/60749035-ed82d600-9f9c-11e9-8fac-3333d976d887.png)

**Comment by dennis1248** [comment]
I checked and this issue is not present for me on my Vega 64, so it might only affect certain GPUs. I am launching the game with LD_PRELOAD="", I am mentioning this in case it could be affecting my test results (even though I highly doubt they do).

**Comment by radube2** [comment]
Yes, there might be some differences between 4th gen GCN and 5th gen GCN. Remains to see if other people with Polaris cards have same issue.
Also if it's not cloudy these artifacts will not appear (obviously, but just saying).

**Comment by pendingchaos** [comment]
I can reproduce this issue and it seems to have been fixed with 50ea4e6b9cebb7de3def53b0aa11b32b4c47e5b4.
