### ISSUE TITLE
Dolphin emulator - black screen with ACO and green graphics output with LLVM

### ISSUE THREAD

**Issue by ghost** [daniel-schuermann/mesa#60]
I am running the Dolphin emulator and I am using the experimental driver I got from this PPA:
https://launchpad.net/~valve-experimental/+archive/ubuntu/mesa
My GPU Is Radeon 530 , the OS Is Ubuntu 19.04.
WIth ACO enabled I get a black screen with the titles I got.
With LLVM enabled I simply get green graphics output all over.
Should i use Renderdoc or other software so you can see what's wrong?
I tried RPCS3 and it works fine with 1 title that i got.
Thanks.

**Comment by daniel-schuermann** [comment]
Thx for the report. Which version is correct? green or black? :P (scnr)
Is this a particular game not working or doesn't work anything with dolphin?
Does it work with upstream mesa or with with your default distro vulkan driver?
If you're able to, a renderdoc capture taken with ACO would be helpful.

**Comment by stenzek** [comment]
Hi, Dolphin dev here. the green screen behavior does sound strange, I wasn't aware we had any issues with upstream Mesa/radv. A single solid colour does sound like a texture format conversion issue (we use both fragment and compute shaders for this), but difficult to say for sure without more info.

**Comment by ghost** [comment]
neither black or green are correct lol.
It's not a single game , none works correctly so far (FMVs are fine though).
It works fine with upstream mesa , i never tried the default distro vulkan driver because I always used padoka.
I captured with renderdoc for both LLVM and ACO:

[LLVM.tar.gz](https://github.com/daniel-schuermann/mesa/files/3364573/LLVM.tar.gz)

This is ACO : https://www.mediafire.com/file/pin6lwytaubl65t/ACO.7z/file
I will try and see if upstream mesa is working fine to be sure.

**Comment by pendingchaos** [comment]
I can reproduce the issue with some FIFOs and the issue appears to be fixed with 833c5a809037492f01f5ee9da3abf858396489d4. This fixed an issue introduced in a change we made to code shared between LLVM and ACO, so it shouldn't be present in upstream Mesa.

**Comment by stenzek** [comment]
Ah, that does sound plausible, there's a good chance that most games will make use of dual-source blending at some point. And even if they don't specifically use the feature which requires both outputs, we still write both from the fragment shader.

**Comment by ghost** [comment]
Upstream mesa is fine.

**Comment by pendingchaos** [comment]
Seems the renderdoc captures rendered the frame and but ended up presenting a previous frame(?), so I had to go into qrenderdoc to find out if 833c5a809037492f01f5ee9da3abf858396489d4 fixed them.

For the captures I can replay on my hardware, it seems it does. So I'll be closing this issue.

**Comment by ghost** [comment]
So is the driver version that the ppa uses not the latest one?
Should i wait for an update?
If it is my hardware why I can still use ACO? weird

**Comment by pendingchaos** [comment]
Yes, it's not the latest. The issue should be fixed in an update.
