### ISSUE TITLE
Crash Bandicoot N. Sane - Rendering differs from LLVM8

### ISSUE THREAD

**Issue by libcg** [daniel-schuermann/mesa#62]
Performs better at 1440p by about 9% but the final image differs a bit, see below. Lighting is static in that scene, with some objects moving, such as the foliage. Using mesa 0ba58be607f and LLVM 8.0.0, R9 Fury.

ACO:
![Screenshot from 2019-07-06 17-36-42](https://user-images.githubusercontent.com/490159/60762471-a4bb3380-a015-11e9-8519-1590d1859134.png)

LLVM8:
![Screenshot from 2019-07-06 17-35-33](https://user-images.githubusercontent.com/490159/60762472-aab11480-a015-11e9-9535-b2b5951494be.png)

**Comment by libcg** [comment]
Here's a reference screenshot from a [video](https://www.youtube.com/watch?v=l4OZRwQ1t-Q):
![Screenshot from 2019-07-06 18-10-45](https://user-images.githubusercontent.com/490159/60762615-7b9ca200-a019-11e9-89f8-bc265c7de498.png)

There are differences between this screenshot and the ones I initially posted, it might be a different revision of the game. Nonetheless the shadows look incorrect with ACO, it's most visible on the box on the left of the screen.

**Comment by daniel-schuermann** [comment]
Thx for reporting this issue. Would you be able to provide a renderdoc capture of the frame?

**Comment by libcg** [comment]
I made an interesting discovery... The game never looks identical on consecutive runs. This happens with ACO and LLVM. Maybe there is no driver bug after all.

ACO:
![Screenshot from 2019-07-08 19-56-26](https://user-images.githubusercontent.com/490159/60856387-dc63e000-a1bb-11e9-83d7-0b9434012b10.png)
![Screenshot from 2019-07-08 19-58-11](https://user-images.githubusercontent.com/490159/60856388-de2da380-a1bb-11e9-88e2-7242b8c7af54.png)
![Screenshot from 2019-07-08 19-59-42](https://user-images.githubusercontent.com/490159/60856391-df5ed080-a1bb-11e9-994b-d62bfe6e8c8a.png)

LLVM:
![Screenshot from 2019-07-08 20-01-19](https://user-images.githubusercontent.com/490159/60856393-e4bc1b00-a1bb-11e9-92f0-604b4f35aed2.png)
![Screenshot from 2019-07-08 20-02-00](https://user-images.githubusercontent.com/490159/60856395-e5ed4800-a1bb-11e9-9401-9f4c8148ddf0.png)
![Screenshot from 2019-07-08 20-03-58](https://user-images.githubusercontent.com/490159/60856398-e71e7500-a1bb-11e9-9a06-e94fa15d9883.png)

**Comment by libcg** [comment]
Here's the renderdoc: https://send.firefox.com/download/ca076f06ea62c2ef/#u3zFjMiNbv-dJ1eMd-ctuQ

**Comment by daniel-schuermann** [comment]
Thx! You can by the way open qrenderdoc with ACO and compare the image with RADV_PERFTEST=llvm. Then, you see if the image looks identical.

**Comment by pendingchaos** [comment]
In all screenshots, the bloom around the white line is different with ACO.
![60856391-df5ed080-a1bb-11e9-994b-d62bfe6e8c8a](https://user-images.githubusercontent.com/5159806/60877732-4c16b100-a236-11e9-8e43-653516f27864.png)

**Comment by pendingchaos** [comment]
Can you reupload the Renderdoc? Apparently the link has expired.

**Comment by libcg** [comment]
@pendingchaos here you go: https://send.firefox.com/download/b3a7173391e9b1a5/#wPoIq0PV3dAj4PBPrzK19w

**Comment by libcg** [comment]
From renderdoc, there's definitely a difference between ACO and LLVM with the exact same capture.

ACO:
![aco](https://user-images.githubusercontent.com/490159/60902491-9000ba80-a224-11e9-9e40-00144e2c484b.png)

LLVM:
![llvm](https://user-images.githubusercontent.com/490159/60902545-a444b780-a224-11e9-8383-cc4ce95e8159.png)

**Comment by pendingchaos** [comment]
Should be fixed with 9928a2253860613cca9e8bfbf56d65e8c537c009 (master) and 6f5e73ca6ff60c611ae2ab4a750a7367e6a120fd (backend).

**Comment by libcg** [comment]
Woah! That was fast. Thanks!

**Comment by libcg** [comment]
I can confirm that the rendering is now identical between the two compilers.
