### ISSUE TITLE
Kingdom Come: Deliverance - blocky glitch

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#63]
ACO:
![ACO](https://i.imgur.com/U8q7v1X.jpg)

RADV_PERFTEST=llvm:
![LLVM](https://i.imgur.com/ThZoZfb.jpg)

[Renderdoc](https://drive.google.com/open?id=1fsdvzhTYCY4NA-q-SEeXE3Q5J1YkU89Z)

System:
Vega 56
Mesa ACO git
Proton 4.2 with DXVK git

**Comment by daniel-schuermann** [comment]
Thx, I can reproduce the issue. (LLVM doesn't have any lighting which seems also wrong to me, but might just be the rtld bug.)

**Comment by daniel-schuermann** [comment]
Fixed with 50ea4e6b9cebb7de3def53b0aa11b32b4c47e5b4 in master and with ea5bdb1cda9f3252b1ecf8b0887e8400bb360bae in backend.
