### ISSUE TITLE
[backend] Path of Exile aco_register_allocation assert

### ISSUE THREAD

**Issue by ernstp** [daniel-schuermann/mesa#66]
mesa-aco from 
commit a34cf7009071c835415a7c199dbdfb0585594dd0 (HEAD -> backend, aco/backend)
    amd/compiler: add missing scc clobbers

LLVM-8, FIJI, Ubuntu 19.04.

../src/amd/compiler/aco_register_allocation.cpp:426: std::pair<aco::PhysReg, bool> aco::{anonymous}::get_reg_impl(aco::{anonymous}::ra_ctx&, std::array<unsigned int, 512>&, std::vector<std::pair<aco::Operand, aco::Definition> >&, uint32_t, uint32_t, uint32_t, uint32_t, aco::RegClass, aco::aco_ptr<aco::Instruction>&): Assertion `reg_file[instr->getOperand(j).physReg().reg] == 0' failed.

https://drive.google.com/file/d/1FN2vyBZ8djSc3br8otKT0qpDPYM81m6_/view?usp=sharing

**Comment by daniel-schuermann** [comment]
Should be fixed with aae07fa2083e210c94c817f29b77bc6af6a2738b in master and e57976fedea2ad5d20dd572de6983b21f70fb31a in backend.
