### ISSUE TITLE
Star Citizen gpu hang

### ISSUE THREAD

**Issue by gort818** [daniel-schuermann/mesa#70]
using latest master aco  9928a22

Game loads up fine already seeing better fps but as soon as I move to a larger area in the game it freezes and the gpu hangs.

Tested with llvm and the game ran fine.

Hardware and driver info
https://gist.github.com/gort818/4d556e3c598d0852de5abe50d2245e0e
Dmesg
https://gist.github.com/gort818/9f99b6545994a3e12d2cba61304646b9
![Screenshot_20190709_182738](https://user-images.githubusercontent.com/9098121/60933984-72117500-a279-11e9-843c-b6fa09104d43.png)

**Comment by daniel-schuermann** [comment]
Hey, thx for the report. Would you be able to re-run the game with a debug build? If this doesn't provide useful information, maybe you could try to take a renderdoc capture of the moment just after it normally hangs?

**Comment by daniel-schuermann** [comment]
Another question: are you sure it is an actual hang? Someone else reported freezes of ~20s occasionally for this game.

**Comment by pendingchaos** [comment]
I think it's an actual hang, dmesg pasted shows a GPU reset

**Comment by NTMan** [comment]
Yes, I am sure because I see in kernel log GPU reset.
It's, of course, abnormal, and the system couldn't resume work after it.
Here you can switch in console (Alt - F3) and kill DE process.
For better investigation I would make the following steps:
1) Retest with `RADV_PERFTEST=llvm` environment variable.
2) Switch off GPU reset by adding `amdgpu.lockup_timeout=-1` to kernel command line.
3) Collect log with umr utility https://gitlab.freedesktop.org/tomstdenis/umr
```
# ./umr -O halt_waves -wa
# ./umr -R gfx[.]
# ./umr -O many,bits -r *.*.mmGRBM_STATUS*
# ./umr -O many,bits -r *.*.mmCP_EOP_*
# ./umr -O many,bits -r *.*.mmCP_PFP_HEADER_DUMP
# ./umr -O many,bits -r *.*.mmCP_ME_HEADER_DUMP
# dmesg
```
Save output all above commands in the files and share via cloud file service.

P.S. If you turn off GPU reset system would hang and only one way to collect info is using ssh connection and terminal on another computer.

**Comment by gort818** [comment]
@daniel-schuermann Yes I would be happy to test a debug build, and yes definitely a hang.
@NTMan already tested with llvm works great, ill test with umr later today. Thanks.

**Comment by gort818** [comment]
@daniel-schuermann Ok I tried with the debug build the game now crashes on launch, here is the output. 
https://gist.github.com/gort818/55c24358177004b05af71690462c90eb

**Comment by gort818** [comment]
I tried commit d271fd74413d4600ec18ace0c4be5ab10e379e26 and there are no gpu hangs I will look for the bad commit and report back. 

but using this commit the game crashes when firing gatling ballistic guns here is the crash log 
https://gist.github.com/gort818/4057a720316029bd589a1041105dd052

also player models faces are distorted 
![Screenshot_20190710_183039](https://user-images.githubusercontent.com/9098121/61015774-e6afe680-a341-11e9-96a5-6944ccb6ec42.png)
with llvm 
![Screenshot_20190710_184829](https://user-images.githubusercontent.com/9098121/61016123-68ecda80-a343-11e9-8dcc-5d2cda9cabdb.png)

**Comment by gort818** [comment]
Ok I just finished bisecting It seems that this commit 077490f  introduced the gpu hang for Star Citizen.

> 

> 077490f11216f0d2c4550364ce2149ee31c17d33 is the first bad commit
> 
> commit 077490f11216f0d2c4550364ce2149ee31c17d33
> Author: Daniel Schürmann <daniel@schuermann.dev>
> Date:   Mon Jul 8 18:15:27 2019 +0200
> 
>     amd/compiler: remove killed phi sgpr-operands from live vars between p_logical_end and block end.
>     
>     As SSA elimination inserts parallelcopies at p_logical_end, SGPR operands might be dead already and can be re-used for RA
> 
>  src/amd/compiler/aco_live_var_analysis.cpp   | 12 ++++++++--
>  src/amd/compiler/aco_register_allocation.cpp | 34 ++++++++++++++++++++++++++++
>  src/amd/compiler/aco_validate.cpp            | 34 ++++++++++++++++++++++++++++
>  3 files changed, 78 insertions(+), 2 deletions(-)
>

**Comment by gort818** [comment]
With the latest working commit for me b8daf015462 the gpu does not hang but the game crashes , works fine with llvm. Here is the crash log with a debug build of mesa.

https://gist.github.com/gort818/3e0c92d8a5c7ca302d7a641cb8ddb5fe

**Comment by gort818** [comment]
And here is a renderdoc using b8daf01 with llvm I captured right after it crashes with aco

 https://www.dropbox.com/s/kfxhaxp8s8egvxn/wine64-preloader_2019.07.10_21.40_frame5100.rdc?dl=0

**Comment by daniel-schuermann** [comment]
Thx for the very helpful information. I fixed the assertion which came up (it was a false positive) and implemented the missing instructions. Can you check if the game still hangs? If it does, I assume the capture didn't get the hang, unfortunately, as it renders just fine for me with the patches applied.
(Note that captures taken with LLVM need shader{Int64/Float64} enabled, if you want to test them with ACO. You can do this in /src/amd/vulkan/radv_device.c

**Comment by ntropy83** [comment]
actual built of Mesa/ACO from the Steam Ubuntu PPA doesnt launch Star Citizen. It crashes when trieing to open the game window:

`e: ../src/amd/compiler/aco_ssa_elimination.cpp:205: void aco::{anonymous}::try_remove_simple_block(aco::{anonymous}::ssa_elimination_ctx&, aco::Block*): Zusicherung »j == branch->target[0]« nicht erfüllt.`

**Comment by gort818** [comment]
Just tried the latest commit built with debug, game loads but still the gpu still hangs

> amdgpu: radv_amdgpu_cs_query_fence_status failed.

**Comment by gort818** [comment]
I ran with radv debug and got 

> ../mesa-aco/src/amd/vulkan/radv_cmd_buffer.c:5348: write_event: Assertion `cmd_buffer->cs->cdw <= cdw_max' failed.

**Comment by gort818** [comment]
I tried to get a renderdoc with llvm every time i capture the game crashes and the renderdoc file says it is corrupted.

**Comment by gort818** [comment]
The game loads with the latest debug build but still getting a gpu hang with aco.

> amdgpu: radv_amdgpu_cs_query_fence_status failed.

I managed to get another renderdoc with llvm where gpu hangs with aco, I had i set my resolution to 1080p from 1440p otherwise the game would crash with renderdoc. Hope this is helpful!

https://www.dropbox.com/s/4yylw61x4jhzqj6/wine64-preloader_2019.07.11_19.39_frame7139.rdc?dl=0

**Comment by ntropy83** [comment]
The backend_old_2019_07_08 branch btw runs amazing, almost 90% decrease in stutter compared to llvm and the game becomes playable. It only has the faces issues, like in the pictures above.

**Comment by gort818** [comment]
@enthalpie with that branch can you test if using ballistic gatling guns make your game crash

**Comment by SR-dude** [comment]
Is there a demo for this game?

**Comment by beniwtv** [comment]
They do free-fly events once in a while, where you can play it for free during a few days. But no permanent demo.

**Comment by ntropy83** [comment]
> @enthalpie with that branch can you test if using ballistic gatling guns make your game crash

They do ! No GPU hang tho, just a game freeze.

Other than that the compiler is working wonders. I get 45 fps in Area 18 and 60 - 70 outside w/o streaming (software encoding) and recording on a 2700X. Completly stutterless. Upon entering the hangar in the video the shader got compiled new for the new ship I spawned, but that took like a nanosecond. Pretty amazing :). 
https://www.youtube.com/watch?v=AYXquX6ZKns

**Comment by daniel-schuermann** [comment]
Thx for sharing. Would you retest with current master branch? It contains a bunch of fixes compared to backend_old_2019_07_08. What do you mean by freeze? Does the game continue normally? And how long does it freeze?

**Comment by gort818** [comment]
@daniel-schuermann Master branch causes a gpu hang still 
dmesg output
> [  209.688366] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
[  214.818453] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=60013, emitted seq=60015

game output

> ../mesa-aco/src/amd/vulkan/radv_descriptor_set.c:487: VK_ERROR_OUT_OF_POOL_MEMORY
amdgpu: radv_amdgpu_cs_query_fence_status failed.

and on backend_old_2019_07_08 branch
>  with that branch can you test if using ballistic gatling guns make your game crash
They do ! No GPU hang tho, just a game freeze.

The game freezes but does not continue it eventually crashes to desktop

**Comment by gort818** [comment]
Don't know if this helps but I replayed a renderdoc I captured and saw this error.

> Error   - Assertion failed: 'capabilities.minImageCount <= 2 && (2 <= capabilities.maxImageCount || capabilities.maxImageCount == 0)'

**Comment by gort818** [comment]
I reverted this commit 1f6010dd013342fce62a9f4fd55186cf83e4570a and tested it out, no more gpu hangs but distorted faces.

**Comment by daniel-schuermann** [comment]
> Don't know if this helps but I replayed a renderdoc I captured and saw this error.

This one is unrelated.





> I reverted this commit [1f6010d](https://github.com/daniel-schuermann/mesa/commit/1f6010dd013342fce62a9f4fd55186cf83e4570a) and tested it out, no more gpu hangs but distorted faces.

Would you be able to hand me a capture of the distorted faces? Maybe it's related. The commit shouldn't have any visual effect.

**Comment by gort818** [comment]
Of course here you go! Warning it is a big one 2.4 GB
https://www.dropbox.com/s/gim5zixi32oefnt/wine64-preloader_2019.07.14_02.04_frame26974.rdc?dl=0

**Comment by ntropy83** [comment]
Same here, master branch causing a full gpu hang after a minute of playtime.

The game freeze of the backend branch you can see at the end of my video above. Upon firing the ballistic cannons it freezes. Laser weaponry on the other hand is working.

**Comment by daniel-schuermann** [comment]
Unfortunately, the capture doesn't help investigating the problem further. Would you be able to run the game with a debug build and enable some additional validation by starting the game with ACO_VALIDATE_RA=1 ? (Beware, this will probably make the game unplayable because of stuttering)

**Comment by gort818** [comment]
unfortunate I tried about 20 times and the game kept crashing or getting oom errors. All the renderoc captures ended up corrupted.

Any other suggestions?

**Comment by gort818** [comment]
@enthalpie maybe you can give it a shot?
also I just built the latest master look at the fps difference between aco and llvm great job guys! Still causes gpu hang but what a difference!

with llvm 47.60 fps
![Screenshot_20190715_201129](https://user-images.githubusercontent.com/9098121/61263378-7b995200-a73d-11e9-914a-8db0d7663094.png)

with aco 72.20 fps
![Screenshot_20190715_200638](https://user-images.githubusercontent.com/9098121/61263392-85bb5080-a73d-11e9-873b-6120e0cb3491.png)

with amdgpu-pro vulkan drivers 63.99 fps
![Screenshot_20190715_202239](https://user-images.githubusercontent.com/9098121/61263583-5fe27b80-a73e-11e9-90e0-014f09a8dcd3.png)

**Comment by daniel-schuermann** [comment]
The numbers are great, but the GPU hang still needs some investigation :(
I created an extra branch for this issue, so that we can try something.
The branch https://github.com/daniel-schuermann/mesa/tree/backend_issue_70
has shaderFloat64 enabled (although not completely implemented).
The idea is to try once again to capture the hang itself. For that reason, I'd like to ask you if you could again use RADV_PERFTEST=llvm and capture the moment where ACO hangs as precisely as possible. You can test if you got it by opening the capture with ACO, the GPU should just hang like ingame. Thx in advance!

**Comment by gort818** [comment]
Ok awesome thanks! The only problem is the gpu always hangs at different times, sometimes it hangs while loading and other times in hangs after a few minutes of playing.. But I will give it a try!

**Comment by pendingchaos** [comment]
One thing you could do is run the game with something like
```bash
export RADV_TRACE_FILE=$HOME/trace.txt
export RADV_DEBUG=allbos,syncshaders,vmfaults
./game &> $HOME/stdout_stderr.txt
```
and post stdout_stderr.txt once the game hangs. This will probably make the game run very slowly though.

RADV_TRACE_FILE needs to be specified, but I don't think it will contain anything interesting. So you can delete it once you're done.

**Comment by ntropy83** [comment]
[kernel.log](https://github.com/daniel-schuermann/mesa/files/3399341/kernel.log)

I have a kernel log snippet. The VK_ERROR_OUT_OF_POOL_MEMORY keeps iterating from the game menu on. Then after leaving your ingame apartment, the game crashes with two GPU resets. If I then just reboot, the PC will hang and I have to hard reset. If I kill the whole wine instance via ssh the GPU recovers.

I have build a debug mesa build and it launches and crashes always at the same time. How can I capture the console output when starting from lutris? I watched the lutris log but there are mainly wine related issues shown

**Comment by daniel-schuermann** [comment]
from https://wiki.gentoo.org/wiki/Lutris#Debugging
lutris -d 2>&1 lutris.txt might work.
Then again, if it's reproducible, you can try to capture that moment with renderdoc and replay the capture with the debug build (use the backend_issue_64 branch as debug build for that). if the capture crashes as well, would be perfect, otherwise the lutris dump might help as well. Thx!

capturing that moment with LLVM, otherwise it would crash before you get a chance.

**Comment by gort818** [comment]
Ok tried with the backend_issue branch using radv debug and it crashes on launch. Without the radv debug environmental variable games loads but same gpu hang.

> WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU 
> Enabled debug options: allbos, vmfaults, syncshaders, 
> Enabled perftest options: llvm, 
> ../mesa-aco/src/amd/vulkan/radv_cmd_buffer.c:5406: write_event: Assertion `cmd_buffer->cs->cdw <= cdw_max' failed.

**Comment by gort818** [comment]
If I run radv debug with the backend branch using RADV_PERFTEST=llvm games crashes

> Enabled debug options: allbos, vmfaults, syncshaders, 
> Enabled perftest options: ../mesa-aco/src/amd/vulkan/radv_device.c:512: radv_get_perftest_option_name: Assertion `id < ARRAY_SIZE(radv_perftest_options) - 1' failed.

**Comment by gort818** [comment]
I manged to get a few captures with llvm and I cant get any of them to cause a gpu hang using aco :(

**Comment by gort818** [comment]
Ok I disabled that assert statement so I could launch the game, and got this hang report.
https://gist.github.com/gort818/71d7ff82e4e1d006d021d7dfdc642e21

**Comment by shmerl** [comment]
What is a good way of making a renderdoc capture when hang happens? I.e. is there some way to continuously do it, rather than a single one with F12? Or using `RADV_TRACE_FILE` is the only way to handle that?

**Comment by daniel-schuermann** [comment]
Not as far as i know. So, hitting the moment is basically the best we can get. Unfortunately, the shader from the trace is already contained in the previous capture but doesn't seem to reproduce the hang..
Currently, we just try to figure the hang with a sharp look on the assembly but that might or might not work out.
Does reverting  1f6010d still produce any visual differences (maybe other than the faces). I know that the shader is affected by that commit but I cannot explain what could go wrong yet.

**Comment by gort818** [comment]
Ok so there are two versions of the game at this moment the live version which is at 3.5.1 and there is a test version called PTU 3.6 (it stays in the testing phase for a few weeks before moving to the live version.). I just got access to the test version Yesterday.

With the test version, ACO master(  gives me a SpvCapabilityFloat64 error) and backend 70 branch do not cause gpu hangs it does cause a wine c++ runtime error every so often but I doubt that has anything to do with ACO

**Comment by shmerl** [comment]
With SC constantly updating, stuff will change a lot :) But it's probably still good to figure out why the hang happens, to prevent similar potential cases in the future.

**Comment by SR-dude** [comment]
There is possibly another way we can go about this. The engine
is open source, Amazon Lumberyard.
[https://en.wikipedia.org/wiki/Amazon_Lumberyard](url)
The github page is [https://github.com/aws/lumberyard](url)
The download link is
[https://aws.amazon.com/lumberyard/download-lumberyard/](url)

**Comment by shmerl** [comment]
SC is using their own fork of the engine, to the point that it has very little with Lumberyard now, as far as I know, besides may be only Amazon backend services integration.

**Comment by SR-dude** [comment]
I'm installing some demos from this link. They  are
all windows binaries. I'll keep you posted.
https://aws.amazon.com/lumberyard/downloads/

**Comment by daniel-schuermann** [comment]
> With the test version, ACO master( gives me a SpvCapabilityFloat64 error) 

Oh, interesting. Error (== crash) or warning? In case of an error, they'd now check the support before just using the features. But strange that the game has a strong dependency on FP64 without fallback option.

> and backend 70 branch do not cause gpu hangs it does cause a wine c++ runtime error every so often but I doubt that has anything to do with ACO

Not sure about that. Is that with a debug build? Do you think you can somehow access the error.log of wine to see what goes wrong?

**Comment by gort818** [comment]
Oops sorry just a SPRIV warning. Yes that is with a debug build I will try and get a log for you.

**Comment by gort818** [comment]
Ok good news for the moment Star Citizen just released alpha 3.6 , using the debug build of the branch backend issue 70 there are no more gpu hangs , no distorted faces, game doesn't crash when firing ballistic gatlings , and no crashes witihin an hour of playing.

I will need to test with master branch and non debug build and let you know my findings.

Thanks again for all your work!

**Comment by daniel-schuermann** [comment]
That is some good news, although I still have no idea why that hang happened. Maybe, it was just some uninitialized variable or something undefined behavior which LLVM resolves, and ACO doesn't...
Anyway, would you also check with the normal 'backend' branch? I pushed the remaining shaderFloat64 instructions and enabled this feature (which also means backend_issue_70 is obsolete now). Thx!

**Comment by gort818** [comment]
I just tested with the master branch no hangs!
with ACO
![Screenshot_20190720_122810](https://user-images.githubusercontent.com/9098121/61583304-29fd1880-aaeb-11e9-849d-3efb45507c2d.png)

with LLVM
![Screenshot_20190720_122540](https://user-images.githubusercontent.com/9098121/61583310-3aad8e80-aaeb-11e9-8802-8352e3a32329.png)

with amdgpu pro vulkan
![Screenshot_20190720_122226](https://user-images.githubusercontent.com/9098121/61583311-426d3300-aaeb-11e9-98f8-270fc85c1df5.png)

now to test backend branch

**Comment by daniel-schuermann** [comment]
hmm, is there a lighting issue or is this just player position or change on the scene? because something similar is visible on the previous screenshots you posted..

**Comment by gort818** [comment]
It is just the player position, ok I tried the backend branch there does not seem to be any difference between that branch and master.

with ACO
![Screenshot_20190720_130652](https://user-images.githubusercontent.com/9098121/61583666-fa044400-aaef-11e9-893d-2ef49cede88d.png)

with LLVM
![Screenshot_20190720_131002](https://user-images.githubusercontent.com/9098121/61583669-05576f80-aaf0-11e9-933e-8a09f39d0ad3.png)

**Comment by gort818** [comment]
So i think I can close this issue, as there are no more hangs and the hang that would occur in alpha 3.5.1 is not available to test anymore, unless @enthalpie has any issues

**Comment by shmerl** [comment]
I tested the new update. It often hangs during quantum drive flight, though it's not a GPU reset kind of hang.

**Comment by ntropy83** [comment]
Hi sry I have been busy the last days. The branch backend_issue_70 is running amazing for me. On a R9 3900X the shader stutter is almost gone, the game is absolutely playable now :). FPS are still borked, but its the same for windows users as people told me. Game only lets the GPU run at 50%.

Have a look here, empty shader cache:
https://www.youtube.com/watch?v=zw7FQNMsbxw
P.S.: in the vid after leaving ARC-1 rest stop there is a little fight with a pirate. :)

Havent tested the master branch yet, but I guess its working (since we kept hitting the same problems in the past) so the issue can be closed :)

**Comment by shmerl** [comment]
Just tested with llvm, and it's not hanging during quantum drive flight, so it's something with aco. Testing master branch.

**Comment by gort818** [comment]
@shmerl Does the game crash or just hang monetarily ?

**Comment by shmerl** [comment]
The graphics stop updating, but the sound still plays. I can still minimize the window and then force exit it from the system notifications area icon.

**Comment by ntropy83** [comment]
I think you got the max memory cap error. SC will crash, when the Ubuntu default value got overrun. On Ubuntu you have to issue in CLI once:

sudo sysctl -w vm.max_map_count=655300

The value will remain after reboots then. Could be a different command on debian, I am sadly not versed with the distro, but you may be will know.

This crash is mesa unrelated and just happens for all Linux users, if not adressed. Took me a week to find that out, before I wasnt able to ever leave Hurston .

The command was added in the Lutris installer reference (but I admit I never read manuals as well :)).

**Comment by gort818** [comment]
I doubt this has anything to do with ACO but Star Citizen seems crash for me frequently maybe a wine bug? https://gist.github.com/gort818/ee738564b99ff18dd7913bd217a9685d

**Comment by shmerl** [comment]
Did you try increasing `vm.max_map_count` kernel variable, like @enthalpie suggested above? It fixed these crashes for me! Though I increase it only temporarily, when playing the game.

**Comment by gort818** [comment]
yeah I increased that a while ago.. I get random crashes and not during quantum

**Comment by shmerl** [comment]
What Wine are you using? I run it with Wine 4.12.1 + esync patches, faudio 19.07.

**Comment by gort818** [comment]
I tried 4.12, 4.11, tkg 4.6, GE4.11 proton. All seem to crash only started on the new patch 3.6.. Haven't noticed a crash with llvm yet. Ill do some more testing.

**Comment by shmerl** [comment]
May be it's a dxvk issue? I built it not long ago (master branch).

**Comment by gort818** [comment]
It looks like a webrtc  pulse issue... I deleted my pulse config lets hope that works.

Anyway no more gpu hangs I think it is safe to say we can close this. :) Thank you all your work everyone.
