### ISSUE TITLE
Elder Scrolls Online

### ISSUE THREAD

**Issue by bMapuche** [daniel-schuermann/mesa#72]
Performance didn't change much (The same, sometimes a little better), but I noticed rendering issues.

[2019-07-10-203743-1920x1080-scrot.png](https://postimg.cc/t1kTVcYg)

Kernel: 5.1.16-arch-1-ARCH
CPU: Core i5 4470
GPU: AMD Radeon R9 280

**Comment by gort818** [comment]
You should probably post a screenshot using llvm to see the comparison.

**Comment by pendingchaos** [comment]
I don't think ACO supports that GPU. Are you sure ACO is being used and this isn't an bug with normal Mesa?

Does using your Linux distribution's Mesa or RADV_PERFTEST=llvm change anything?

**Comment by bMapuche** [comment]
I used to play the game with regular Mesa, and had no rendering issues before. It is something with the ACO that is causing these issues.

**Comment by daniel-schuermann** [comment]
This GPU is currently not yet supported by ACO, which means that the normal LLVM backend is being used with this driver. As we didn't rebase the master branch yet, you are probably affected by a recent regression regarding the rtld change in LLVM. This will be fixed with the next rebase. Nevertheless, I'd recommend to use a standard mesa driver with this GPU until we can provide proper support.
Thx for reporting anyway.

**Comment by bMapuche** [comment]
> This GPU is currently not yet supported by ACO, which means that the normal LLVM backend is being used with this driver. As we didn't rebase the master branch yet, you are probably affected by a recent regression regarding the rtld change in LLVM. This will be fixed with the next rebase. Nevertheless, I'd recommend to use a standard mesa driver with this GPU until we can provide proper support.
> Thx for reporting anyway.

Oh okay, thanks for clarifying. I just switched to regular mesa and the rendering issues went away.
[![2019-07-10-223731-1920x1080-scrot.png](https://i.postimg.cc/MGKmDb38/2019-07-10-223731-1920x1080-scrot.png)](https://postimg.cc/QFw7N5r6)

**Comment by lapinsami** [comment]
https://i.imgur.com/gHs00fv.png
https://i.imgur.com/c7KdJwW.png
https://i.imgur.com/VVvEpNK.png
https://i.imgur.com/gpGH0b5.png

Vega 56
Ryzen 7 1700
Manjaro Linux, Kernel 5.1.16-1-MANJARO
