### ISSUE TITLE
Elder Scrolls Online glitches

### ISSUE THREAD

**Issue by lapinsami** [daniel-schuermann/mesa#73]
# Software information
Elder Scrolls Online
All settings tested, same glitches every time
No glitches with RADV_PERFTEST=llvm Edit: check my comment below

# Screenshots
https://i.imgur.com/gHs00fv.png
https://i.imgur.com/c7KdJwW.png
https://i.imgur.com/VVvEpNK.png
https://i.imgur.com/gpGH0b5.png

# System information
Vega 56
Ryzen 7 1700
Manjaro Linux, Kernel 5.1.16-1-MANJARO
mesa-aco-git from AUR (19.2.0_devel.113503.0ba58be607f-1)

# RenderDoc capture
https://send.firefox.com/download/061d61f43688017e/#T3trKZzWN7wbDI4Pgi8PQg
Expires after 100 downloads or 7 days, password acordc56

**Comment by libcg** [comment]
Can you test with the latest commit?

**Comment by lapinsami** [comment]
https://i.imgur.com/RqzvVHD.png
https://i.imgur.com/RBTmhvS.png

I tested RADV_PERFTEST=llvm again and noticed some smaller scale glitches similar to the ones above. These do no appear when using normal mesa packages. ACO makes them bigger and more numerous though.

**Comment by lapinsami** [comment]
> Can you test with the latest commit?

Tested, makes no difference

**Comment by daniel-schuermann** [comment]
Hi, thx for the report!
Are you sure about them appearing differently with LLVM? If I open your renderdoc with LLVM, and also with upstream mesa, and it looks identical to me.

**Comment by lapinsami** [comment]
Tested some more areas in the game. Every area I tested is like this.

https://i.imgur.com/YfvLsi9.png ACO
https://i.imgur.com/DMIK9PK.png LLVM

https://i.imgur.com/AsadLOS.png ACO
https://i.imgur.com/rRJ9qFd.png LLVM

Upstream mesa has no glitches at all, I've played the game for hundreds of hours on Linux.

**Comment by daniel-schuermann** [comment]
Ok, convinced :)
Unfortunately, the renderdoc capture seems to contain pre-rendered textures which result in the same output no matter which driver is used. I'll investigate this, but might take a bit.

**Comment by daniel-schuermann** [comment]
So, turns out:
The issue is indeed present in upstream/mesa, but it is not a driver issue but originating in DXVK (meanwhile resolved). With the next Proton update, the fix will be made available. Meanwhile a workaround would be to use a newer DXVK version or an older driver version.
