### ISSUE TITLE
Grandia II Anniversary Edition aborts with "Cannot initialize Direct3D device"

### ISSUE THREAD

**Issue by Valmar33** [daniel-schuermann/mesa#75]
# Software information

Grandia II Anniversary Edition on Steam.

Game settings changes don't make a difference.

# Screenshots

After error dialog with message, the window opens for a brief moment, then immediately closes.

# System information

- GPU: RX 580
- ACO version: "add Github issue template", 7157929d52cc9155315bba243749e9a6f575c2e7, 11/7/19 1:21 AM, Rhys Perry<pendingchaos02@gmail.com>

# Logs

[grandia2_log.txt](https://github.com/daniel-schuermann/mesa/files/3388725/grandia2_log.txt)

[grandia2_d3d11_log.txt](https://github.com/daniel-schuermann/mesa/files/3388726/grandia2_d3d11_log.txt)

[grandia2_dxgi_log.txt](https://github.com/daniel-schuermann/mesa/files/3388727/grandia2_dxgi_log.txt)

Please tell me more about how I can gather more information about this bug.

**Comment by doitsujin** [comment]
This is not a bug, it's a problem with your setup. The DXVK log shows that it cannot find a Vulkan driver, so depending on how you are tying to use your Mesa build, you're either missing a 32-bit build or you just did something wrong.

**Comment by Valmar33** [comment]
Ah. I see. I had presumed that the game was 64-bit.

Turns out it was 32-bit... thanks doitsujin! :)
