### ISSUE TITLE
Max Payne 3 (204100) incorrect colors + GPU hang

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#76]
# Software information

[Max Payne 3](https://store.steampowered.com/app/204100/)
# Screenshots
LLVM:
![Screenshot from 2019-07-13 16-18-03](https://user-images.githubusercontent.com/200750/61172221-ca5ab680-a59a-11e9-922e-af583d0ee309.png)

ACO:
![Screenshot from 2019-07-13 16-23-38](https://user-images.githubusercontent.com/200750/61172231-d777a580-a59a-11e9-8774-17d46b20a734.png)

Yes, you see that ACO looks much better than LLVM on screenshots, but not the same picture I saw on the monitor.
On the monitor when I see the dark-green beard and dark-red hair, green blood.

Here I made a photo from the phone for explaining how I see it:
![IMG_20190713_174029](https://user-images.githubusercontent.com/200750/61172299-c9765480-a59b-11e9-9f4b-767fa9c13b6c.jpg)

![IMG_20190713_174054](https://user-images.githubusercontent.com/200750/61172323-06424b80-a59c-11e9-9a9a-af9b68e3632a.jpg)

![IMG_20190713_204047](https://user-images.githubusercontent.com/200750/61173625-3ba46480-a5af-11e9-9055-a37ec4df2f68.jpg)

And the second issue is GPU hang which reproduced on both LLVM and ACO.

So I think this should be reported to original mesa right?
Demonstration: https://youtu.be/5-peqm82_qI

Here is my save game for easy reproduction: 
[Max Payne 3.zip](https://github.com/daniel-schuermann/mesa/files/3388848/Max.Payne.3.zip) should be placed in `.steam/steam/steamapps/compatdata/204100/pfx/drive_c/users/steamuser/My Documents/Rockstar Games` directory

# System information

- GPU: AMD Radeon VII
- ACO version: Git f1e0a45d

# RenderDoc capture

https://mega.nz/#F!E5IxSSaT!5EnrlWDvAob2sQBiRPOfqA

**Comment by daniel-schuermann** [comment]
Thx for the report. Running the capture with LLVM on a debug build, gives an assertion:
`src/amd/common/ac_llvm_build.c:2580: ac_build_image_opcode: Assertion 'a->opcode == ac_image_sample || a->opcode == ac_image_gather4 || (!a->compare && !a->offset)' failed.`

I'll try to figure if it's a driver bug.

**Comment by pendingchaos** [comment]
The assertion @daniel-schuermann reported has been fixed with https://gitlab.freedesktop.org/mesa/mesa/commit/a9f58af4549b522f64950152c0180228471b8520

This also seems to fix the glowing hair issue you reported: https://user-images.githubusercontent.com/200750/61172221-ca5ab680-a59a-11e9-922e-af583d0ee309.png

**Comment by NTMan** [comment]
@pendingchaos Can you also look why GPU hang occurred?
Here separate bug report: https://bugs.freedesktop.org/show_bug.cgi?id=111124

**Comment by daniel-schuermann** [comment]
@NTMan Would you please confirm if the purple hair issue is gone?
W.r.t. the hang, as this issue is reproducible on both ACO and LLVM, the bug is correctly reported at the freedesktop bug tracker and will be covered there.

**Comment by NTMan** [comment]
> @NTMan Would you please confirm if the purple hair issue is gone?

Yes, I could confirm that hair in the latest mesa is ok even with LLVM.

**Comment by daniel-schuermann** [comment]
Thank you very much. Feel free to report any further issues you encounter :wink:
