### ISSUE TITLE
RPCS3 - Red Dead Redemption crashes on shader compile

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#78]
# Software information

Red Dead Redemption using RPCS3 emulator crashes at main menu when compiling shader(s) with the following message:

>../src/amd/compiler/aco_instruction_selection.cpp:2308: void aco::{anonymous}::visit_store_output(aco::isel_context*, nir_intrinsic_instr*): Assertion `!ctx->program->info->info.ps.writes_z && "unimplemented"' failed.

# Screenshots
LLVM main menu (image varies on each launch, but it crashes every time either way with ACO):
![LLVM main menu](https://i.imgur.com/uNOCCM5.jpg)

# System information

- GPU: Vega 56
- ACO version: 7157929d52cc9155315bba243749e9a6f575c2e7

# RenderDoc capture
I couldn't manage to get a RenderDoc (with LLVM) as the trace eats all of my RAM then gets killed by OOM.

**Comment by pendingchaos** [comment]
The assertion should be fixed with 1d9a46843ff92157890a45a2695971b2b75f61fe.
