### ISSUE TITLE
Can't build lib32 version without lib32-systemd but conflicts with lib32-eudev

### ISSUE THREAD

**Issue by napejuice** [daniel-schuermann/mesa#79]
**Describe the bug**
lib32-mesa-aco-git won't compile on Artix due to not using systemd but mesa-aco-git will.

**Screenshots**
![Screenshot at 2019-07-15 18-22-23](https://user-images.githubusercontent.com/5185864/61259119-a9769a80-a72d-11e9-838f-a784193df427.png)

**System information:**
 - OS: [Artix Linux OpenRC](https://artixlinux.org)
 - GPU: Radeon R9 380X
 - ACO version: lib32-mesa-aco-git 19.2.0_devel.113855.7157929d52c-1

**Additional context**
Installed with artix-mate-lxde-openrc-community-20190609-x86_64.iso from artixlinux.org

Can this be fixed without having to tell me to change to a systemd based OS? That'd be great. :)

**Comment by Oschowa** [comment]
Just remove the lib32-systemd dependence form the PKGBUILD or build 32 bit radv/aco manually with meson. Also i'm not 100% your GCN3 gpu is even supported by aco currently.
This also has nothing to do with aco at all.

**Comment by pendingchaos** [comment]
R9 380X should be supported, though it might require a hardware bug workaround that we haven't been able to test on actual hardware.

**Comment by napejuice** [comment]
Sorry I didn't think to edit the pkgbuild as I wasn't sure what would happen. If the x64 build doesn't have systemd make dependance why does the i386 build do? Sorry, I'm a novice at this Linux stuff still. :] @pendingchaos can you explain what you mean by 'hardware bug workaround'?

**Comment by pendingchaos** [comment]
Apparently Tonga GPUs (like R9 380X) have issues when different draw calls allocate different numbers of SGPRs without idling the GPU in-between the draws, so we have to use a fixed number of SGPRs. We've implemented the workaround, but have only tested it by spoofing a Tonga GPU and not on actual hardware.

**Comment by napejuice** [comment]
Anything I can do to help with that? @pendingchaos
