### ISSUE TITLE
Redout Enhanced Edition (517710): Objects popping in and out in busy scene

### ISSUE THREAD

**Issue by Gotolei** [daniel-schuermann/mesa#80]
**Describe the bug**
When there are many objects on the screen at once ("objects" being eg. buildings, sections of track, bits of background decoration), some of them start flickering in and out at seemingly random intervals. Flicker appears to be more frequent for more distant objects. 

**Videos**
Since it doesn't appear in stationary shots, linked are two videos of the same scenarios: the first with ACO and the second with LLVM.
ACO: https://youtu.be/-nISuy4ZvME?t=28. Timestamps: 0:28-0:37; 1:00-1:12
LLVM: https://youtu.be/FeEhXuvcItQ?t=25. Timestamps: 0:25-0:35; 0:49-0:58. This does still exhibit some pop-out, but it seems to be predictable and in line with normal expectations for view distance.

**RenderDoc capture:**
Unsure if it's complete, game crashed after capture. Captured with ACO.
https://drive.google.com/open?id=1ouE-LfjRCymJcGf1yS9NedFxIyBZ0f5e
[Corresponding screenshot](https://steamcommunity.com/sharedfiles/filedetails/?id=1807255555)

**System information:**
 - GPU: Radeon RX 580
 - ACO version: 19.1.0+aco+git1563205428-5031ab774a6-1bionic2
 - Proton version: 4.2-9
 - Distro: Xubuntu 18.04 Bionic

**Additional context:**
Mesa and relevant packages just pulled in an update last night, and I only started noticing this behavior today. Previous version looks to be 19.1.0+aco+git1562841159-677bea5144d-1bionic1.

Issue appears on any track with many objects in any game mode. The track in the videos and capture is Cairo Calima, the first track in the game. Graphical settings are shown at the end of the first video and consistent between both, with view distance turned up as high as it can go.

**Comment by pendingchaos** [comment]
Thanks for the report.

Seems to be fixed with a60c307606237ddc9bbc35174a1274506f7974da (master) and 53697efa15f247708d4f06a900b5010490cf5041 (backend).
