### ISSUE TITLE
Update the code with latest mesa.

### ISSUE THREAD

**Issue by Haxk20** [daniel-schuermann/mesa#81]
As far as i know the code is based on really old mesa code.
If it would be possible to update it or maybe even better update it maybe often.

**Comment by pendingchaos** [comment]
The master branch is currently based on 5eaed7ecfce49ae55128c3f6fed37727b14ce6f9 (commited 7th of July) and the backend branch (a less stable version of master) is currently based on f239e22813fe1d10ceb4ca799848e180e3cd0430 (commited 12th of July).

So both are rather recent and we intend to continue to rebase every now and then until upstreaming.

**Comment by daniel-schuermann** [comment]
We try to keep rebasing ~weekly.
