### ISSUE TITLE
Mudrunner Map corruption

### ISSUE THREAD

**Issue by Termuellinator** [daniel-schuermann/mesa#82]
**Describe the bug**
Sometimes the Map gets corrupted (see screenshots). For now this only happened in some Multiplayer, tried some Singleplayer short tests where it never occured. Overriding to LLVM seems to also prevent it. Sometimes alt+tab to another window and tabbing back into the game resolves the issue, sometimes this crashes the game.

**Screenshots**
https://imgur.com/vL8CTuK
https://imgur.com/LcksJUe

**RenderDoc capture:**
renderDoc didn't create a .rpc file when using the launch parameters in steam as described, when trying to launch the mudrunners.exe through the RenderDoc GUI it says "injection failed" - don't know what i'm doing wrong?

**System information:**
 - GPU: Radeon Rx580
 - ACO version: mesa-aco-git 19.2.0_devel.113859.5031ab774a6-1 (AUR on Manjaro)

**Comment by daniel-schuermann** [comment]
Did you try to start steam via command line with
`ENABLE_VULKAN_RENDERDOC_CAPTURE=1 steam` ?
Something else you could test is to create a debug build of ACO and see if the game crashes with some assertion.

**Comment by Termuellinator** [comment]
still no rdc file when running steam with this ENV :/

How do i build a debug build?
The AUR-Packagebuild contains:
```
build () {
    meson setup mesa-aco _build \
       -D b_ndebug=true \
```
so maybe it is already a debug build?
Where would a corresponding log be found? Or do i have to run the game from konsole?
I'll be away for the week, so i won't be able to test until the weekend.

**Comment by Oschowa** [comment]
For a debug build you need
```
-D buildtype=debugoptimized \
-D b_ndebug=false \
...
```
You can then run steam form a terminal to see the output.

As for the renderdoc capture, you need to press F12 to capture a single relevant frame. The capture will show up in /tmp/RenderDoc

edit: Seems like the game is 32-bit, so linux renderdoc won't work with it.

**Comment by Johnnynator** [comment]
```edit: Seems like the game is 32-bit, so linux renderdoc won't work with it.``` Just build a full 32bit version of renderdoc or or just the 32bit lib part (it works fine with the 64bit gui tools)

**Comment by Termuellinator** [comment]
uhm, i'm note sure how to build renderdoc 32bit - there is no mention of it in their wiki and the binary for Linux is also only 64bit.
I'd like to keep it through AUR, so would it be possible to add "CMAKE_C_FLAGS=-m32" to the build-section in the [AUR-PKBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=renderdoc) ? Would that build only 32bit or multilib?

**Comment by Johnnynator** [comment]
@Termuellinator You would also need to clear out the Deps and since Arch doesn't provide 32bit builds of qt5 disable the qt5 part of renderdoc, a PKGBUILD like this might work http://ix.io/1PRx (It probably has conflicting files with renderdoc, so you should have only installed one of them at any point of time)

**Comment by Oschowa** [comment]
I think the biggest problem with 32-bit renderdoc on linux with wine is that it will run out of address space and crash. You can however use 32-bit apitrace to record a d3d11 apitrace and then attach 64-bit renderdoc to the apitrace replay.
You can find apitrace binaries here: https://github.com/apitrace/apitrace/releases

**Comment by Termuellinator** [comment]
i assume you mean doing an apitrace inside wine like [this](https://github.com/apitrace/apitrace/wiki/WINE)?
Never worked with apitrace before - how would the launch-option have to be set? As far as i can tell winedlloverrides should work with proton, but does Proton mount / on Z: by default, too? If so, as mudrunner seems to be using d3d9
```
WINEDLLOVERRIDES='Z:\home\jfonseca\projects\apitrace\build\mingw32\wrappers\d3d9.dll=n'
~/projects/apitrace/build/mingw32/apitrace.exe trace -a d3d9 -v %command%
```
should do it? 
And speaking of which - is this even covered by ACO when it's d3d9? O_o Afaik d9vk is not yet included in proton by default, is it?

**Comment by Oschowa** [comment]
If the game is indeed using d3d9 and you use stock proton, it should run using wined3d on OpenGL and thus not be affected by ACO at all.
You can check if it uses dxvk/vulkan by enabling the dxvk HUD:
`DXVK_HUD=1 %command%`
as launch option in steam

**Comment by daniel-schuermann** [comment]
@Termuellinator can you please confirm if the game runs with OpenGL? You might also want to test with d9vk now that it is included in Proton.

**Comment by Termuellinator** [comment]
Sorry for the delay!
I jus tested and can confirm that the game does indeed run with OpenGL.
With D9VK, the game only has a few FPS during the intro and freezes after a few seconds ingame. But thats the same with or without ACO.
So it seems it has nothing to do with ACO and it was just a coincident that it never occured when i activated RADV_PERFTEST=llvm . Sorry for the hassle!
