### ISSUE TITLE
Prey crashes and system hangs

### ISSUE THREAD

**Issue by Tuatha-De-Danann** [daniel-schuermann/mesa#85]
Running Prey with Proton 4.2-9
Menu loads --> New Game --> Character selection --> Loading Screen goes up to 90%, then the game and the systems hangs and I'm unable to recover.

**RenderDoc capture:**
Can't provide one, as the systems hangs and I have to restart. I'm not sure if I can capture one up to the point of the crash (I might need help to set it up)

**System information:**
Lenovo E585 with AMD 2700U APU
16 GB DDR4 2400 RAM
OS: Arch Linux 
KDE-Plasma-Version: 5.16.3
KDE-Frameworks-Version: 5.60.0
Qt-Version: 5.13.0
Kernel-Version: 5.2.3-arch1-1-ARCH
OS-Type: 64-bit
CPU: 8 × AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx

 - ACO version:
mesa-aco-git 19.2.0_devel.114249.17d9490cef1-1
lib32-mesa-aco-git 19.2.0_devel.114249.17d9490cef1-1

**Comment by daniel-schuermann** [comment]
Hi, thx for the report!
Does this game run with RADV_PERFTEST=llvm for you? You could try to obtain a renderdoc capture with LLVM, but I will only have access to my Raven Ridge computer again in late September or October. This game seems to have worked one week ago with Vega (see https://github.com/daniel-schuermann/mesa/issues/36#issuecomment-513432529). Would you be able to test the branch https://github.com/daniel-schuermann/mesa/tree/master_old_2019_07_23 ?
And as a last note: We don't fully support APUs at the moment. They tend to work fine most of the time, but on page faults (accesses to memory which is currently not mapped), things are likely to fall apart as we are missing the feature to recover and continue from that situation for APUs.

**Comment by Tuatha-De-Danann** [comment]
I can set it up in the next days and will give feedback on it. I'm not very experienced with testing, but can do the LLVM and recompile and do a retest for sure.

**Comment by aufkrawall** [comment]
You don't need to recompile the driver, just state RADV_PERFTEST=llvm as an environment variable.

**Comment by SR-dude** [comment]
Prey works fine for me. Wine 4.12.1.  Not running SteamPlay/Proton, I'm using the steam client wholly under wine. 

> System:    Host: XXXXX Kernel: 5.2.3 x86_64 bits: 64 Desktop: LXDE 0.10.0 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] driver: amdgpu v: kernel 
           Display: server: X.Org 1.20.5 driver: amdgpu unloaded: fbdev,modesetting resolution: 1600x900~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.32.0 5.2.3 LLVM 8.0.0) 
           v: 4.5 Mesa 19.2.0-devel (git-5c6077221d)

**Comment by aqxa1** [comment]
No hangs for me either, Vega 56, Proton 4.11, DXVK master, ACO master (70bb3c0becd).

**Comment by SR-dude** [comment]
Any word on this? I'll give a capture to put your mind at ease.

**Comment by daniel-schuermann** [comment]
No need, it seems to work with Polaris and Vega. The problem is very likely APU-related and will be addressed some time eventually :)

**Comment by Tuatha-De-Danann** [comment]
I tested it a couple of times, newest release was completely corrupting any 3D game, with LLVM option it was kinda visible but still artifacts all over. I then switched back to normal mesa and everything was fine again. I think its a combination of unsupported APU together wih mesa-git (as mentioned above even normal LLVM mode was artifacting)

Tested games:
- Prey works on normal mesa, no luck on ACO (native/LLVM)
- Subnautica: Dito
- Tabletop Simulator: Works on all 3 methods
