### ISSUE TITLE
can't compile GTK3 programs

### ISSUE THREAD

**Issue by Hanouta** [daniel-schuermann/mesa#87]
Not gaming related, but I've noticed that I can't compile gtk3 programs after installing the mesa-aco-git and lib32-mesa-aco-git packages from the AUR. 
When compiling zenmonitor(program for monitoring CPU temps, voltage, etc. for Ryzen CPU's) I got this error:
```
cc -Isrc/include `pkg-config --cflags gtk+-3.0` src/*.c src/ss/*.c -o zenmonitor `pkg-config --libs gtk+-3.0` -lm -no-pie
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'egl', required by 'epoxy', not found
src/gui.c:2:10: schwerwiegender Fehler: gtk/gtk.h: Datei oder Verzeichnis nicht gefunden
    2 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
Kompilierung beendet.
src/zenmonitor.c:1:10: schwerwiegender Fehler: gtk/gtk.h: Datei oder Verzeichnis nicht gefunden
    1 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
Kompilierung beendet.
src/ss/msr.c:1:10: schwerwiegender Fehler: glib.h: Datei oder Verzeichnis nicht gefunden
    1 | #include <glib.h>
      |          ^~~~~~~~
Kompilierung beendet.
src/ss/zenpower.c:1:10: schwerwiegender Fehler: glib.h: Datei oder Verzeichnis nicht gefunden
    1 | #include <glib.h>
      |          ^~~~~~~~
Kompilierung beendet.
make: *** [makefile:2: build] Fehler 1
```

I've also tried other GTK3 programs, I got an error about a missing gtk.h there too.

**System information:**
 - ACO version: 19.2.0_devel.114251.58e0420cb35-1
 - OS: Manjaro

**Comment by daniel-schuermann** [comment]
Probably this issue is related to https://aur.archlinux.org/packages/mesa-aco-git/#comment-701624
If you look at the comments below, it seems you have to install https://aur.archlinux.org/packages/libglvnd-glesv2/ to fix this issue. Does that help?

**Comment by Hanouta** [comment]
Yes, that fixed the issue. Thanks
