### ISSUE TITLE
D9VK and Skyrim Legendary Edition: Artefacts with MSAA enabled

### ISSUE THREAD

**Issue by varris1** [daniel-schuermann/mesa#88]
**Describe the bug**
After I enabled 8x MSAA, artefacts appeared ingame. RADV_PERFTEST=llvm didn't show that behavior

**Screenshots**
![ACO](https://user-images.githubusercontent.com/38386180/62090082-d49fd480-b26b-11e9-821a-d9631582e26a.png)

![LLVM](https://user-images.githubusercontent.com/38386180/62090090-dc5f7900-b26b-11e9-93e2-ed21adf8e6d1.png)

**RenderDoc capture:**
https://mega.nz/#!H2ghxK6J!Vypi1M1xw-WipOqA87KBmjmNmUkLXblDN-ZPcJixCxg

**System information:**
 - GPU: AMD RX 590 (Polaris)
 - ACO version: master branch, commit: 5c6077221dd0718f09c12fc1b1a6f65595416288

**Additional context**
I used Wine & D9VK.

**Comment by daniel-schuermann** [comment]
it works with https://github.com/daniel-schuermann/mesa/tree/master_old_2019_07_12
I'll check back, when I found out what broke.

**Comment by daniel-schuermann** [comment]
Actually, it didn't work. The old branch just misses a feature so that some shadows aren't rendered at all. We'll keep you posted.

**Comment by daniel-schuermann** [comment]
Actually, I think both images are wrong and LLVM just got lucky that it doesn't look so terrible.

![Screenshot from 2019-08-03 08-51-34](https://user-images.githubusercontent.com/13393471/62408640-24640000-b5cc-11e9-8dc2-8f4d8496671f.png)

Can you confirm that this is the expected output?

**Comment by BNieuwenhuizen** [comment]
So is this really Skyrim Legendary Edition + D9VK, or is this Skyrim Special Edition with DXVK? I see a DXVK HUD on there?


nvm, looks like D9VK also has the same HUD.

FWIW I cannot reproduce this with upstream radv & a vega.

**Comment by varris1** [comment]
> Can you confirm that this is the expected output?

![Gallium Nine](https://user-images.githubusercontent.com/38386180/62413623-4469e280-b611-11e9-947c-b51438b6ab85.png)
Here is a screenshot of Gallium Nine. In hindsight the LLVM image doesn't seem to be correct either. 

I will ask @joshua-ashton to take a look at it since it could just be an issue with D9VK itself.

**Comment by daniel-schuermann** [comment]
> FWIW I cannot reproduce this with upstream radv & a vega.

Did you try with PROTON_USE_D9VK=1 ?If I do this, I only get abnormal program termination... but I start to get the impression that this might be a D9VK bug and not the driver.

**Comment by misyltoad** [comment]
Should be closed by
https://github.com/Joshua-Ashton/d9vk/commit/605296b4670340ebf08ff7f81ac3968e8164f00a

'Twas an issue on my end that was not easily apparent visually with LLVM.

**Comment by varris1** [comment]
What Josh said.
