### ISSUE TITLE
Atelier Lydie & Suelle: weird lines in the air

### ISSUE THREAD

**Issue by exolyte** [daniel-schuermann/mesa#89]
**Describe the bug**
There are random lines in the air originating from a fountain. This does not happen with RADV_PERFTEST=llvm.

**Screenshots**
ACO:
![2019-07-30-21:41:25](https://user-images.githubusercontent.com/2102492/62162034-a8419200-b317-11e9-83e8-b4ba24e844cf.png)
LLVM:
![2019-07-30-21:39:51](https://user-images.githubusercontent.com/2102492/62162036-ab3c8280-b317-11e9-818b-6f0c3547a95f.png)

**RenderDoc capture:**
https://mega.nz/#!XRdQkSxJ!EyFYkK1zZ4It5gJBhWuSHhMuBF6nQSkqLU4c10fEEZc

**System information:**
 - GPU: RX570
 - ACO version: master, 5c60772

**Comment by daniel-schuermann** [comment]
fixed with b2bb91dcccff6053f1f2f223f4e00da957190421.
