### ISSUE TITLE
Final Fantasy XII TZA driver crash

### ISSUE THREAD

**Issue by napejuice** [daniel-schuermann/mesa#90]
**Describe the bug**
Upon starting a new game or loading an existing game amdgpu crashes. Have to force quit the game afterwards.

journalctl | grep amdgpu yields this:
>Jul 30 13:51:32 jfpc kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
Jul 30 13:51:32 jfpc kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, but soft recovered
Jul 30 13:51:42 jfpc kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
Jul 30 13:51:42 jfpc kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
Jul 30 13:51:42 jfpc kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=4602392, emitted seq=4602395
Jul 30 13:51:42 jfpc kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process FFXII_TZA.exe pid 20142 thread FFXII_TZA.exe pid 20207
Jul 30 13:51:42 jfpc kernel: amdgpu 0000:01:00.0: GPU reset begin!
Jul 30 13:51:43 jfpc kernel: amdgpu 0000:01:00.0: GPU pci config reset
Jul 30 13:51:43 jfpc kernel: amdgpu 0000:01:00.0: GPU reset succeeded, trying to resume
Jul 30 13:51:43 jfpc kernel: amdgpu 0000:01:00.0: GPU reset(14) succeeded!

**System information:**
 - Arch Linux
 - Kernel: [linux52-tkg-pds  5.2.4-13](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/linux52-tkg)
 - GPU: Radeon R9 380X
 - ACO version: mesa-aco-git  19.2.0_devel.114720.5c6077221dd-1

**Additional context**
Game plays fine with RADV_PERFTEST=llvm

**Comment by daniel-schuermann** [comment]
Hi @BrosephJ , would you be able to create a renderdoc capture with LLVM? Would probably be sufficient to just capture right after loading into the game (where you don't get with ACO). You can verify that you captured the issue by opening the capture with ACO.

**Comment by napejuice** [comment]
I'm unable to help with this now as I had to put my GTX 970 back in since my R9 380X was malfunctioning. As for renderdoc I tried to use it before but couldn't figure it out anyways. Didn't seem like there was any way for me to capture the game. I'm still a newbie in this space. Sorry! >_<

**Comment by SR-dude** [comment]
This should be close if the OP has abandoned the issue.
