### ISSUE TITLE
Monster Hunter World: Graphical corruption and performance hit not present with RADV_PERFTEST=llvm

### ISSUE THREAD

**Issue by ghost** [daniel-schuermann/mesa#92]
**Describe the bug**
Monster Hunter World has severe graphical problems and performance decrease not present with `RADV_PERFTEST=llvm`

**Screenshots**
ACO:
![aco](https://user-images.githubusercontent.com/12925873/62177462-87d40080-b334-11e9-95a7-d231ab4d5d00.jpg)

RADV_PERFTEST=llvm:
![llvm](https://user-images.githubusercontent.com/12925873/62177474-8f93a500-b334-11e9-9ea4-dacabbc08958.jpg)

**System information:**
 - GPU: RX580
 - ACO version: 5c6077221dd0718f09c12fc1b1a6f65595416288 (latest git as of today)

**Additional context**
Pretty sure I ran MHW fine with earlier versions of mesa-aco-git.

**Comment by Johnnynator** [comment]
Haven't checked the latest commit, but even with e.g https://github.com/daniel-schuermann/mesa/commit/a60c307606237ddc9bbc35174a1274506f7974da and some previous commit the game was looking and performing fine, until ~30-60 minutes in where the frame rate dropped sub 1fps and amdgpu (Can make a proper bug report once I have time for it)

**Comment by daniel-schuermann** [comment]
Thx for the report! Could you test with RADV_PERFTEST=llvmvs and see if the problem persists (although it looks like pixel shader) ?
Either way, would you be able to provide a renderdoc capture of the issue?

**Comment by ghost** [comment]
It does still happen with `RADV_PERFTEST=llvmvs`

**Comment by Johnnynator** [comment]
Here is a renderdoc capture: https://void.johnnynator.dev/Monsterhunterworld-renderdoc.tar.gz

**Comment by daniel-schuermann** [comment]
Can you confirm that this issue is fixed with b2bb91dcccff6053f1f2f223f4e00da957190421 ?

**Comment by Johnnynator** [comment]
Yep this fixed the issue.

**Comment by pendingchaos** [comment]
How is performance after that fix?

**Comment by Johnnynator** [comment]
> How is performance after that fix?

Didn't do any exact measurements. Roughly in the position of OP's screenshot it is roughly 1-2 fps more with ACO (~42fps max instead of ~40fps max).

**Comment by pendingchaos** [comment]
ok

**Comment by ghost** [comment]
Also confirming it's fixed for me. Thanks genius (not sarcastic).

I am getting same fps with mesa ACO or `RADV_PERFTEST=llvm`, in a test spot standing in same exact location, however I'm probably CPU bound.
