### ISSUE TITLE
Sunset Overdrive (847370) - GPU hang

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#94]
Sunset Overdrive randomly hangs the GPU. I have also seen it happen with the LLVM compiler in the past, but it would only happen every few hours or so, whereas it happens within seconds/minutes with ACO. It's hard to tell if it's the same bug and ACO just triggers it more reliably, or if it has a different cause. It seems to happen after attacking enemies, but it's hard to tell if there is a particular effect causing the hang.

**RenderDoc capture:**
I have uploaded a RenderDoc [capture](https://drive.google.com/file/d/1Rc35FJnnQYaP2N4MyFhkdHZwiNUDOF9K/view?usp=sharing) with ACO, but it's before the hang occurs so I'm not sure how helpful it will be: 

**System information:**
 - GPU: Vega 56
 - ACO version:  5c6077221dd

**Comment by NTMan** [comment]
I can confirm this hang. In my case occurs on commit 8f5ac45a.

- RADV_PERFTEST=llvm - not reproduced
- RADV_PERFTEST=llvmvs - reproduced [dmesg-s2.txt](https://github.com/daniel-schuermann/mesa/files/3465253/dmesg-s2.txt)
- without RADV_PERFTEST - reproduced [dmesg-s1.txt](https://github.com/daniel-schuermann/mesa/files/3465255/dmesg-s1.txt)


GPU: AMD Radeon VII

**Comment by SR-dude** [comment]
aqxa1,
Do you get any weird kernel messages?

**Comment by aqxa1** [comment]
@SR-dude Just the typical messages you get when a GPU hang occurs. It successfully GPU resets too (as most hangs now do). Kernel 5.2.5, for the record:

`[ 4695.273323] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out or interrupted!
[ 4700.883322] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=587257, emitted seq=587259
[ 4700.883343] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process Sunset.exe pid 14231 thread dxvk-submit pid 14265
[ 4700.883345] amdgpu 0000:0d:00.0: GPU reset begin!
[ 4701.199420] amdgpu 0000:0d:00.0: GPU BACO reset
[ 4701.199559] amdgpu: [powerplay] Failed to send message: 0x26, ret value: 0xffffffff
[ 4701.199733] amdgpu: [powerplay] Failed to send message: 0x63, ret value: 0xffffffff
[ 4701.210884] amdgpu: [powerplay] Failed to send message: 0x26, ret value: 0xffffffff
[ 4701.214217] amdgpu: [powerplay] Failed to send message: 0x63, ret value: 0xffffffff
[ 4701.225794] amdgpu: [powerplay] Failed to send message: 0x26, ret value: 0xffffffff
[ 4701.229127] amdgpu: [powerplay] Failed to send message: 0x63, ret value: 0xffffffff
[ 4701.240705] amdgpu: [powerplay] Failed to send message: 0x26, ret value: 0xffffffff
`

**Comment by aqxa1** [comment]
I managed to record a [RenderDoc trace](https://drive.google.com/file/d/1AnIc0qIevn2lNa8fpDJ9pj32ngwzZiC3/view?usp=sharing) that consistently hangs when replaying. Interestingly, it seems to hang with both ACO and LLVM (with RADV_PERFTEST=llvm and system Mesa).

**Comment by NTMan** [comment]
> I managed to record a RenderDoc trace that consistently hangs when replaying.

When I read messages, I sometimes wonder how people were able to do this, while the computer hangs.

**Comment by aqxa1** [comment]
@NTMan Yeah, it's weird. It didn't actually hang when I recorded the trace (with RADV_PERFTEST=llvm) but when replaying it, hangs occur with both compilers.

**Comment by daniel-schuermann** [comment]
@aqxa1 @NTMan: would you please retest with the new DXVK release + current master?

**Comment by aqxa1** [comment]
@daniel-schuermann All good, played for 30 minutes without a GPU hang. Thanks!

**Comment by aqxa1** [comment]
For the record I encountered another GPU hang with this game, but I suspect it's of the "random, impossible to reproduce reliably type" that the standard driver with LLVM had (and probably still has).
