### ISSUE TITLE
visual glitch Quake Champion

### ISSUE THREAD

**Issue by grinceur** [daniel-schuermann/mesa#95]
**Describe the bug**

Some mesh and the character aren't rendered in game with ACO (from the AUR) and therefor appear gray.

**Screenshots**

ACO:
![Capture d’écran de 2019-08-01 10-57-45](https://user-images.githubusercontent.com/36852305/62281946-fa390380-b44e-11e9-8d7a-f23e1351c897.png)

With RADV_PERFTEST=llvm:
![Capture d’écran de 2019-08-01 11-17-32](https://user-images.githubusercontent.com/36852305/62281993-1046c400-b44f-11e9-8de0-a6bef4c70f49.png)

**RenderDoc capture:**

https://drive.google.com/open?id=1D4DtVlSupvOW8Pr671YdH5inAVY0K_m3

**System information:**
 - GPU: Radeon RX580 8g
 - ACO version: aur/mesa-aco-git 19.2.0_devel.114720.5c6077221dd-1

**Comment by daniel-schuermann** [comment]
fixed with 2d096ea935b6255e42b9cc0ff1206beef4da3a8c
