### ISSUE TITLE
System hangs up with ACO after launching any app.

### ISSUE THREAD

**Issue by Haxk20** [daniel-schuermann/mesa#96]
**Describe the bug**
As the title says the system fully hangs except cursor. Happens on GNOME and any other DE.
Does not happen with pure mesa and this is an issue for a week or so. Master and backend branches are affected.

**System Info**
 - GPU: VEGA8 on Ryzen 5 2500U and RX560X
 - ACO version: Master and backend.

**Comment by daniel-schuermann** [comment]
Which OS are you using? Did you build ACO yourself? What build parameters do you use? Which mesa version do you mean by "pure mesa"? As far as I know, no desktop application nor the desktop itself use Vulkan and ACO is pure mesa from ~ 1 week ago + a new backend which is only used with RADV.

**Comment by Haxk20** [comment]
> Which OS are you using? Did you build ACO yourself? What build parameters do you use? Which mesa version do you mean by "pure mesa"? As far as I know, no desktop application nor the desktop itself use Vulkan and ACO is pure mesa from ~ 1 week ago + a new backend which is only used with RADV.

Im using Arch Linux. Yes i always build software myself. Just default parameters. I mean latest git commit by pure mesa. Yes i know DE doesnt use Vulkan sadly. I think this might be just issue in mesa that got fixed in pure mesa. Could you tell me on which commit is ACO based on ? So that i can build pure mesa and see if the issue appears there too.

**Comment by pendingchaos** [comment]
Both master and backend are based off 08f1cefecd84f851da6d90200bd7af0ecf5bf855.

**Comment by Haxk20** [comment]
Confirming that this is issue with pure mesa too based on that commit. But as the latest commit doesnt have the issue i guess it would be just best to rebase.

**Comment by pendingchaos** [comment]
We've just rebased ACO on a very recent version of Mesa: 5254e53debe3bcfe3d8dc1ba4110fda8b6a616f9

So, the hang should be fixed.

**Comment by Haxk20** [comment]
indeed it is fixed
