### ISSUE TITLE
World of Warships, Path of Exile, Prey rendering issue (blinking chunks)

### ISSUE THREAD

**Issue by anonymous133** [daniel-schuermann/mesa#99]
**Describe the bug**
Blinking chunks

**Screenshots**
removed

**System information:**
 - GPU: Radeon Vega 64
 - ACO version: 19.2.0_devel.114724.fbaabd839e8-1
- Steam Proton 4.2-9

Additional info:
This is the first time a problem occured with mesa-aco for me in Wows. Otherwise it was perfect.

Thank you for your outstanding work!

**Comment by arzardk** [comment]
Same issues on Vega 56 with Path of Exile, Prey after the 19.1.0+aco+git1564695179-fbaabd839e8-1disco1 update.
RenderDoc capture (Vulkan): [MadMax_ACO.7z](https://drive.google.com/open?id=1k_tSfsBILiJInCQ6KaDvpBHjltHYUmh5)

Update: this issue affecting games which are using Vulkan (Native, DXVK,D9VK)

**Comment by SR-dude** [comment]
I just tried Prey with Polaris and it was fine(fbaabd839e). 
This might be a Vega related problem.

**Comment by pendingchaos** [comment]
Seems we broke pretty much everything on Vega.

Should be fixed with e1f60e9b38ad0b7d2f57654db5425e97a6e693cd.

**Comment by anonymous133** [comment]
Thank you, it is fixed!
